# Windows Server 2022/2025 x64, Agent 2 7.0 LTS; default MSI destination.
LogType=file
LogFile=C:\ProgramData\Zabbix\zabbix_agent2.log
LogFileSize=10
Server=192.0.2.10
ServerActive=192.0.2.10:10051
Hostname=windows-app-01
ListenPort=10050
TLSConnect=psk
TLSAccept=psk
TLSPSKIdentity=windows-app-01-psk
TLSPSKFile=C:\ProgramData\Zabbix\agent2.psk
DenyKey=system.run[*]
UnsafeUserParameters=0
Include=C:\Program Files\Zabbix Agent 2\zabbix_agent2.d\plugins.d\*.conf
