            <div class="article-filter-bar">
              <span
                class="article-filter-label"
                id="article-filter-label"
                data-en="Category"
                data-fa="دسته‌بندی"
                >Category</span
              >
              <ul
                class="portfolio-filters isotope-filters article-chip-row"
                role="group"
                aria-labelledby="article-filter-label"
              >
                <li>
                  <button
                    type="button"
                    data-filter="*"
                    data-topic="all"
                    class="filter-active"
                    aria-pressed="true"
                    data-en="All articles"
                    data-fa="همه مقالات"
                  >
                    All articles
                  </button>
                </li>
                <li>
                  <button
                    type="button"
                    data-filter=".filter-microsoft"
                    data-topic="microsoft"
                    aria-pressed="false"
                    data-en="Microsoft"
                    data-fa="مایکروسافت"
                  >
                    Microsoft
                  </button>
                </li>
                <li>
                  <button
                    type="button"
                    data-filter=".filter-linux"
                    data-topic="linux"
                    aria-pressed="false"
                    data-en="Linux"
                    data-fa="لینوکس"
                  >
                    Linux
                  </button>
                </li>
                <li>
                  <button
                    type="button"
                    data-filter=".filter-mikrotik"
                    data-topic="mikrotik"
                    aria-pressed="false"
                    data-en="MikroTik"
                    data-fa="میکروتیک"
                  >
                    MikroTik
                  </button>
                </li>
                <li>
                  <button
                    type="button"
                    data-filter=".filter-vmware"
                    data-topic="vmware"
                    aria-pressed="false"
                    data-en="VMware"
                    data-fa="مجازی‌سازی"
                  >
                    VMware
                  </button>
                </li>
                <li>
                  <button
                    type="button"
                    data-filter=".filter-others"
                    data-topic="other"
                    aria-pressed="false"
                    data-en="Other"
                    data-fa="سایر مقالات"
                  >
                    Other
                  </button>
                </li>
              </ul>
            </div>
