<?php

// Generate the maintained bilingual HTML consumed by the existing legacy importer.
$escape = fn (string $s): string => htmlspecialchars($s, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8');
$slug = 'linux-security-auditor-bash';
$url = 'https://meetaj.ir/articles/'.$slug;
$image = '/assets/img/portfolio/linux-8.png';
$localizations = [
    'en' => [
        'title' => 'Building an Enterprise Linux Security Auditor with Bash',
        'meta_title' => 'Linux Security Auditor with Bash: Architecture and Operations | Meet AJ',
        'description' => 'Read the Linux Security Auditor 2.0.0 architecture, severity-weighted scoring, SSH, patch, firewall and container checks, with practical CLI examples and limits.',
        'keywords' => ['Linux Security Audit', 'Linux Hardening', 'Bash Security Script', 'Ubuntu Security', 'Linux Server Security', 'SSH Hardening', 'Linux Firewall Audit', 'CIS-aligned controls'],
        'faq' => [
            ['Does the auditor change server configuration?', 'It creates private temporary files and requested reports. It does not upgrade packages, change firewall rules or permissions, restart services, or write sysctls.'],
            ['Does a score of 100 mean the server cannot be compromised?', 'No. Points describe observed controls within the selected scope. Unknown evidence reduces coverage, and external exposure, CVEs and recovery need separate validation.'],
            ['Is this a certified CIS Benchmark assessment?', 'No. The profiles select locally implemented CIS-aligned controls. Official benchmark section mappings and certification are not claimed.'],
        ],
    ],
    'fa' => [
        'title' => 'ساخت ابزار بررسی امنیت سرور لینوکس با Bash | Linux Security Auditor',
        'meta_title' => 'بررسی امنیت سرور لینوکس با Bash و Linux Security Auditor | Meet AJ',
        'description' => 'معماری Linux Security Auditor نسخه ۲، امتیازدهی وزنی، بررسی SSH، بسته‌ها، فایروال و کانتینرها با مثال‌های واقعی اجرا و محدودیت‌های ممیزی.',
        'keywords' => ['بررسی امنیت لینوکس', 'امن‌سازی سرور لینوکس', 'اسکریپت امنیتی Bash', 'امنیت اوبونتو', 'امن‌سازی SSH', 'ممیزی فایروال لینوکس', 'کنترل‌های همسو با CIS'],
        'faq' => [
            ['آیا ابزار تنظیمات سرور را تغییر می‌دهد؟', 'فقط فایل‌های موقت خصوصی و گزارش‌های درخواستی ساخته می‌شوند. ابزار بسته‌ها را ارتقا نمی‌دهد، فایروال و مجوزها را تغییر نمی‌دهد، سرویس را Restart نمی‌کند و sysctl نمی‌نویسد.'],
            ['آیا امتیاز ۱۰۰ یعنی سرور قابل نفوذ نیست؟', 'خیر. امتیاز وضعیت کنترل‌های مشاهده‌شده در محدوده منتخب را نشان می‌دهد. شواهد نامشخص پوشش را کم می‌کنند و دسترسی بیرونی، CVE و بازیابی بررسی مستقل می‌خواهند.'],
            ['آیا این گزارش تأییدیه CIS Benchmark است؟', 'خیر. Profileها فقط کنترل‌های محلی پیاده‌سازی‌شده و همسو با CIS را انتخاب می‌کنند. نگاشت رسمی شماره بندها و گواهی انطباق ادعا نمی‌شود.'],
        ],
    ],
];
$node = fn (string $tag, string $en, string $fa): string => '<'.$tag.' data-en="'.$escape($en).'" data-fa="'.$escape($fa).'">'.$escape($en).'</'.$tag.'>';
$p = fn (string $en, string $fa): string => $node('p', $en, $fa);
$code = function (string $s, string $language = 'bash') use ($escape): string {
    $markup = $escape($s);
    if ($language === 'bash') {
        // Tokenize before HTML escaping; preserve every byte of copyable source.
        $tokens = preg_split("~('[^']*'|--[a-z][a-z-]*|\\b(?:sudo|chmod|bash|shellcheck)\\b|\\./security-audit\\.sh)~", $s, -1, PREG_SPLIT_DELIM_CAPTURE);
        $markup = '';
        foreach ($tokens as $i => $token) {
            if ($i % 2 === 0) { $markup .= $escape($token); continue; }
            $type = str_starts_with($token, "'") ? 'string' : (str_starts_with($token, '--') ? 'option' : 'command');
            $markup .= '<span class="code-token-'.$type.'">'.$escape($token).'</span>';
        }
    }
    return '<div class="article-code"><div class="article-code-header"><span class="article-code-label">'.$escape($language).'</span><button type="button" class="article-copy-button">Copy</button></div><pre dir="ltr"><code class="language-'.$language.'">'.$markup.'</code></pre></div>';
};
$sections = [];
$section = function (string $id, string $en, string $fa, string $content) use (&$sections, $node): void {
    $sections[] = ['id' => $id, 'en' => $en, 'fa' => $fa, 'html' => '<section id="'.$id.'" class="article-section">'.$node('h2', $en, $fa).$content.'</section>'];
};

$section('introduction', 'Security review beyond SSH and a firewall', 'بررسی امنیت فراتر از SSH و فایروال',
    $p('An SSH key and an active firewall are useful controls, but they do not describe the whole server. An extra UID 0 account, writable service unit, stale security repository or missing audit trail can undermine that baseline. A useful audit connects identity, configuration, running state and the evidence that remains unavailable.', 'کلید SSH و فایروال فعال بخشی از امنیت سرورند. حساب اضافی با UID صفر، فایل قابل‌نوشتن سرویس، مخزن امنیتی قدیمی یا نبود ردپای Audit می‌تواند همان پایه را تضعیف کند. ممیزی کاربردی باید هویت‌ها، تنظیمات، وضعیت اجرا و شواهدی را که در دسترس نیستند کنار هم بگذارد.')
    .$p('Review authentication, users, password policy and sudo alongside SSH, host filtering, listening sockets and patch management. Filesystem permissions, cron, persistence, systemd, kernel settings, logging, audit rules, AppArmor or SELinux, containers and threat indicators each answer a different operational question.', 'Authentication، کاربران، سیاست رمز و sudo باید کنار SSH، فایروال میزبان، Socketهای شنونده و مدیریت Patch بررسی شوند. مجوز فایل‌ها، Cron، Persistence، systemd، تنظیمات Kernel، Logging، قواعد Audit، AppArmor یا SELinux، کانتینرها و نشانه‌های تهدید هرکدام به پرسشی متفاوت پاسخ می‌دهند.')
    .$p('This article follows the actual security-audit.sh version 2.0.0. Enterprise here means explicit scope, evidence, prioritization and reviewable reports. It is not a claim that a single Bash script replaces a security program.', 'این مقاله بر اساس کد واقعی security-audit.sh نسخه 2.0.0 نوشته شده است. منظور از رویکرد Enterprise، محدوده روشن، شواهد، اولویت‌بندی و گزارش قابل بازبینی است. یک اسکریپت Bash جای برنامه امنیت سازمان را نمی‌گیرد.'));

$section('architecture', 'What the auditor does and how its engine works', 'Linux Security Auditor چیست و موتور آن چگونه کار می‌کند؟',
    $p('The tool is a single-file GNU/Linux posture assessor requiring Bash 4.4 or newer. Modules collect bounded command snapshots and file metadata. They emit records with stable check IDs, category, state, severity, expected and actual values, evidence, risk, evaluation method and a recommended action. The action is text for an operator, not a remediation command that runs automatically.', 'ابزار یک فایل مستقل برای ارزیابی وضعیت GNU/Linux است و Bash نسخه 4.4 یا جدیدتر می‌خواهد. ماژول‌ها Snapshot محدود از فرمان‌ها و Metadata فایل‌ها می‌گیرند. هر رکورد ID پایدار، دسته، وضعیت، Severity، مقدار مورد انتظار و واقعی، شواهد، ریسک، روش ارزیابی و اقدام پیشنهادی دارد. اقدام پیشنهادی متن راهنما برای مدیر است و خودکار اجرا نمی‌شود.')
    .$p('The final emit and calculate functions define the version 2 engine. Do not infer scoring from the early legacy category-weight declarations. The active categories are System, Authentication, PAM, Sudo, SSH, Network, DNS, Firewall, Patching, Filesystem, Permissions, Persistence, Systemd, Kernel, MAC, Logging, Audit, Cryptography, Containers, Threat, Recovery, Resources and Cloud.', 'توابع نهایی emit و calculate موتور نسخه ۲ را تعیین می‌کنند. تعریف وزن دسته‌ها در ابتدای فایل متعلق به ساختار قبلی است و مبنای امتیاز نهایی نیست. دسته‌های فعال عبارت‌اند از System، Authentication، PAM، Sudo، SSH، Network، DNS، Firewall، Patching، Filesystem، Permissions، Persistence، Systemd، Kernel، MAC، Logging، Audit، Cryptography، Containers، Threat، Recovery، Resources و Cloud.')
    .$p('Records also identify automated_check, inventory, manual_evidence_required or coverage. A record count is not a count of successfully verified controls. Missing commands, denied access, timeouts and unavailable external evidence remain visible as UNKNOWN rather than becoming a pass.', 'نوع رکورد نیز با automated_check، inventory، manual_evidence_required یا coverage مشخص می‌شود. تعداد رکوردها به معنی تعداد کنترل‌های موفق و تأییدشده نیست. نبود فرمان، خطای دسترسی، Timeout و شواهد بیرونی ناموجود با UNKNOWN ثبت می‌شوند و به PASS تبدیل نمی‌شوند.')
    .$p('External commands normally have a 12-second limit. File scans default to 30 seconds each. Quick skips selected expensive scans and package integrity verification. Standard bounds selected scans to depth 6; deep expands candidate local mount roots and package verification. Pattern scans retain their own depth and size bounds even in deep mode. --full changes terminal detail, whereas --profile full changes selected policy controls.', 'فرمان‌های خارجی معمولاً سقف ۱۲ ثانیه دارند و Timeout پیش‌فرض هر اسکن فایل ۳۰ ثانیه است. Quick بعضی اسکن‌های پرهزینه و بررسی Integrity بسته را رد می‌کند. Standard عمق بعضی اسکن‌ها را به ۶ محدود می‌کند؛ Deep ریشه‌های Mount محلی و دامنه بررسی بسته‌ها را گسترش می‌دهد. اسکن الگو حتی در Deep محدودیت عمق و اندازه خود را حفظ می‌کند. --full جزئیات ترمینال را تغییر می‌دهد، ولی --profile full انتخاب کنترل‌های سیاست را تغییر می‌دهد.'));

$section('distributions', 'OS detection and the honest support matrix', 'تشخیص سیستم‌عامل و محدوده واقعی پشتیبانی',
    $p('OS fields are parsed from /etc/os-release without sourcing or evaluating the file. ID selects Debian/APT, RHEL/DNF with YUM fallback, or SUSE/ZYPPER; ID_LIKE can select a family for an otherwise unknown ID. A recognized family does not automatically make the release a validated target.', 'فیلدهای /etc/os-release بدون Source کردن فایل یا اجرای محتوای آن خوانده می‌شوند. ID خانواده Debian/APT، RHEL/DNF با مسیر جایگزین YUM، یا SUSE/ZYPPER را انتخاب می‌کند. برای ID ناشناخته، ID_LIKE ممکن است خانواده را تعیین کند. تشخیص خانواده به‌تنهایی به معنی اعتبارسنجی آن Release نیست.')
    .$p('The validation matrix lists partial support for Ubuntu 20.04, 22.04, 24.04 and 26.04; Debian 11, 12 and 13; RHEL, Rocky, AlmaLinux and Oracle Linux 8, 9 and 10; CentOS Stream 9 and 10; and openSUSE Leap/SLES 15 and 16 families. The SUSE code accepts broader version strings, but that must not broaden the documented validation matrix. Other releases receive generic observations without distribution assurance.', 'ماتریس Validation پشتیبانی جزئی را برای Ubuntu نسخه‌های 20.04، 22.04، 24.04 و 26.04؛ Debian نسخه‌های 11، 12 و 13؛ RHEL، Rocky، AlmaLinux و Oracle Linux نسخه‌های 8، 9 و 10؛ CentOS Stream نسخه‌های 9 و 10؛ و خانواده openSUSE Leap/SLES نسخه‌های 15 و 16 ثبت کرده است. کد SUSE رشته نسخه گسترده‌تری می‌پذیرد، اما این موضوع محدوده اعتبارسنجی مستند را گسترش نمی‌دهد. سایر Releaseها فقط مشاهدات عمومی بدون تضمین توزیع دارند.')
    .$p('No distribution is fully validated across every subsystem. The documented native run used an Ubuntu 24.04 container as root in quick and standard modes. OS fixtures test dispatch, not real SELinux, firewall, boot or package-manager integration. Stage the tool on the actual host family before fleet use.', 'هیچ توزیعی در تمام زیرسیستم‌ها اعتبارسنجی کامل ندارد. اجرای Native مستند روی کانتینر Ubuntu 24.04 با root در حالت Quick و Standard انجام شده است. Fixture تشخیص OS فقط Dispatch را می‌آزماید و آزمون واقعی SELinux، فایروال، Boot یا Package Manager نیست. پیش از استفاده در مجموعه سرورها، ابزار را روی خانواده واقعی میزبان در Staging بررسی کنید.'));

$section('scoring', 'Severity-weighted score and evidence coverage', 'امتیاز امنیت و پوشش شواهد چگونه محاسبه می‌شوند؟',
    $p('Scored controls use severity weights: CRITICAL 10, HIGH 6, MEDIUM 3 and LOW 1. Explicit weight-zero records remain unscored. PASS earns full weight, WARN earns half, and FAIL earns zero. UNKNOWN is removed from the known-score denominator but remains in the applicable-weight denominator used for coverage. NA and INFO are excluded from both.', 'وزن کنترل امتیازدار بر اساس Severity است: CRITICAL برابر ۱۰، HIGH برابر ۶، MEDIUM برابر ۳ و LOW برابر ۱. رکوردی که صریحاً وزن صفر دارد بدون امتیاز می‌ماند. PASS وزن کامل، WARN نصف وزن و FAIL صفر می‌گیرد. UNKNOWN از مخرج امتیاز شواهد معلوم حذف می‌شود، اما در مخرج وزن قابل‌اعمال برای پوشش باقی می‌ماند. NA و INFO از هر دو حذف می‌شوند.')
    .$code("raw_score = floor(100 * (PASS_weight + 0.5 * WARN_weight) / known_weight)\ncoverage  = floor(100 * known_weight / applicable_weight)\nscore     = min(raw_score, critical_cap)", 'text')
    .$p('For example, a HIGH pass (6), MEDIUM warning (3), LOW failure (1) and HIGH unknown (6) produce 75 raw points and 62% coverage. Integer arithmetic truncates percentages. Category points use the same formula within each category. The overall score is pooled across control weights, not an average of category percentages. One, two or at least three critical findings cap it at 85, 75 or 65 by default.', 'برای مثال PASS با Severity بالا و وزن ۶، WARN متوسط با وزن ۳، FAIL کم با وزن ۱ و UNKNOWN بالا با وزن ۶، امتیاز خام ۷۵ و پوشش ۶۲ درصد می‌سازند. محاسبات صحیح درصدها را به پایین قطع می‌کنند. امتیاز هر دسته همین فرمول را در محدوده خود دارد. امتیاز کل از وزن کنترل‌ها ساخته می‌شود و میانگین درصد دسته‌ها نیست. یک، دو یا حداقل سه یافته Critical به‌طور پیش‌فرض سقف ۸۵، ۷۵ یا ۶۵ اعمال می‌کند.')
    .$p('The verdict prioritizes critical findings, then high findings, then coverage below 80%. With enough coverage and no high or critical findings, at least 85 points yields STRONG OBSERVED BASELINE; otherwise IMPROVEMENT REQUIRED. A high score with low coverage is incomplete evidence. It is not a percentage of being unhackable or a substitute for a penetration test.', 'Verdict ابتدا یافته Critical، سپس High و بعد پوشش کمتر از ۸۰ درصد را در نظر می‌گیرد. با پوشش کافی و بدون یافته High یا Critical، امتیاز حداقل ۸۵ نتیجه STRONG OBSERVED BASELINE می‌دهد؛ در غیر این صورت IMPROVEMENT REQUIRED نمایش داده می‌شود. امتیاز بالا با پوشش پایین یعنی شواهد ناقص. این عدد درصد غیرقابل‌نفوذ بودن و جایگزین Penetration Test نیست.')
    .$p('The CIS-aligned value is a separate unweighted pass/assessed ratio for selected aligned controls. Benchmark coverage is also separate. Attack-surface points pool Network, Firewall, SSH and Containers. Threat score starts at 100 and subtracts twice each warning/failure weight tagged Threat Indicator, down to zero; inspect threat coverage beside it. Neither this value nor an empty indicator list establishes incident clearance.', 'عدد CIS-aligned نسبت جداگانه و بدون وزن PASS به کنترل‌های ارزیابی‌شده همسو با CIS است و پوشش Benchmark جدا نمایش داده می‌شود. امتیاز Attack Surface از Network، Firewall، SSH و Containers ساخته می‌شود. Threat Score از ۱۰۰ شروع می‌شود و برای هر WARN یا FAIL با برچسب Threat Indicator دو برابر وزن آن کم می‌کند؛ کف صفر است. پوشش Threat را کنار آن بخوانید. این عدد و حتی نبود نشانه، پاک‌بودن میزبان از رخداد امنیتی را اثبات نمی‌کند.'));

$section('statuses', 'Status and severity are different fields', 'تفاوت وضعیت کنترل و شدت ریسک',
    $p('Internal states are PASS, WARN, FAIL, UNKNOWN, NA and INFO. Public status maps WARN to WARNING and NA to NOT_APPLICABLE. A FAIL with HIGH or CRITICAL severity becomes that public status; a LOW or MEDIUM failure becomes WARNING. Therefore a public WARNING can still carry HIGH severity. Read status, severity and evidence together.', 'وضعیت داخلی PASS، WARN، FAIL، UNKNOWN، NA و INFO است. در خروجی عمومی WARN به WARNING و NA به NOT_APPLICABLE تبدیل می‌شود. FAIL با شدت HIGH یا CRITICAL همان Status عمومی را می‌گیرد، ولی FAIL با شدت LOW یا MEDIUM به WARNING تبدیل می‌شود. بنابراین یک WARNING عمومی ممکن است Severity بالا داشته باشد. وضعیت، شدت و شواهد را کنار هم بخوانید.')
    .$p('Severity accepts CRITICAL, HIGH, MEDIUM, LOW and INFO. PASS means the observed local condition met its stated expectation. INFO records context; UNKNOWN records an evidence gap; NOT_APPLICABLE can mean an absent component or exclusion by profile. None of these labels should be read without scope.', 'Severity مقدار CRITICAL، HIGH، MEDIUM، LOW و INFO می‌پذیرد. PASS یعنی شرط محلی مشاهده‌شده با انتظار تعریف‌شده سازگار بوده است. INFO زمینه را ثبت می‌کند؛ UNKNOWN شکاف شواهد است؛ NOT_APPLICABLE می‌تواند نبود مؤلفه یا حذف آن توسط Profile باشد. هیچ‌کدام بدون محدوده بررسی معنی کامل ندارند.'));

$section('installation', 'Download, requirements and first execution', 'دانلود، پیش‌نیاز و اجرای اولیه',
    $p('Download the actual source below, review it, and transfer it to the intended Linux host. No installer or package installation step is built in. Required standard utilities are awk, grep, sed, find, stat, df, timeout, mktemp, tr, cut, head, sort, wc, date and readlink. Optional inspection commands vary by subsystem. Missing optional evidence usually becomes UNKNOWN.', 'فایل واقعی را از لینک زیر دانلود و بازبینی کنید و به میزبان Linux موردنظر منتقل کنید. ابزار Installer یا مرحله نصب بسته داخلی ندارد. ابزارهای استاندارد لازم awk، grep، sed، find، stat، df، timeout، mktemp، tr، cut، head، sort، wc، date و readlink هستند. فرمان‌های اختیاری بر اساس زیرسیستم فرق دارند و نبود شواهد اختیاری معمولاً UNKNOWN می‌شود.')
    .'<p><a href="/docs/linux-security-auditor/security-audit.sh" download="security-audit.sh">'.$node('span', 'Download security-audit.sh (v2.0.0)', 'دانلود security-audit.sh نسخه 2.0.0').'</a></p>'
    .$code("chmod +x security-audit.sh\n./security-audit.sh --version\n./security-audit.sh --help\nsudo ./security-audit.sh --quick --summary\nsudo ./security-audit.sh")
    .$p('The default is standard cost, enterprise profile and summary output. A non-root run is allowed but shadow, firewall, audit and cross-user metadata may be unreadable. Root inside a container still lacks host namespaces and capabilities. Deep scans can consume I/O even though they do not remediate anything.', 'پیش‌فرض هزینه Standard، Profile برابر enterprise و گزارش Summary است. اجرای بدون root مجاز است، اما Shadow، فایروال، Audit و اطلاعات سایر کاربران ممکن است خواندنی نباشند. root داخل کانتینر هم لزوماً Namespace و Capability میزبان را ندارد. اسکن Deep با وجود نداشتن عملیات اصلاحی می‌تواند I/O مصرف کند.'));

$options = [
    ['--quick | --standard | --deep', 'Cost profile; standard default. Deep is not unlimited.', 'حجم بررسی؛ پیش‌فرض Standard است و Deep نامحدود نیست.'],
    ['--full | --summary', 'Terminal detail; summary default.', 'جزئیات ترمینال؛ پیش‌فرض Summary است.'],
    ['--profile cis-l1|cis-l2|enterprise|full', 'Policy selection; enterprise default excludes Level 2 controls. cis-l2 selects Level 1 and Level 2.', 'انتخاب سیاست؛ enterprise پیش‌فرض کنترل Level 2 را کنار می‌گذارد. cis-l2 شامل Level 1 و Level 2 است.'],
    ['--no-color | --color auto|always|never', 'Color policy; auto default.', 'سیاست رنگ؛ پیش‌فرض auto است.'],
    ['--export-json FILE', 'Create a new JSON report; existing targets are refused.', 'گزارش JSON جدید؛ مقصد موجود پذیرفته نمی‌شود.'],
    ['--export-html [FILE]', 'Create standalone HTML; omitting FILE selects a new report directory if none was specified.', 'HTML مستقل؛ بدون FILE در صورت نبود مسیر، پوشه گزارش جدید انتخاب می‌شود.'],
    ['--output-dir ABSOLUTE_PATH', 'Create a new private directory with report.json, report.html and detailed report.txt.', 'ساخت پوشه خصوصی جدید برای report.json، report.html و report.txt کامل.'],
    ['--scan-seconds N', 'Per file scan timeout: 5..300; default 30.', 'Timeout هر اسکن فایل: ۵ تا ۳۰۰؛ پیش‌فرض ۳۰ ثانیه.'],
    ['--disk-thresholds WARN,HIGH,CRIT', 'Increasing values 0..100, default 80,90,95; strictly greater comparisons.', 'اعداد صعودی بین صفر و ۱۰۰؛ پیش‌فرض 80,90,95؛ مقایسه با بزرگ‌ترِ اکید است.'],
    ['--critical-caps ONE,TWO,THREE', 'Nonincreasing values 0..100; default 85,75,65 for 1/2/3+ critical findings.', 'اعداد غیرصعودی بین صفر و ۱۰۰؛ پیش‌فرض 85,75,65 برای ۱، ۲ و حداقل ۳ یافته Critical.'],
    ['--ssh-context SPEC', 'Supply sshd -T -C context.', 'ارسال Context به sshd -T -C.'],
    ['--sshd-config ABSOLUTE_PATH', 'Select an existing daemon configuration file.', 'انتخاب فایل موجود تنظیمات Daemon با مسیر مطلق.'],
    ['--self-test', 'Run isolated local fixtures.', 'اجرای Fixtureهای محلی جدا از ممیزی میزبان.'],
    ['--demo', 'Generate explicitly labeled synthetic findings.', 'ساخت یافته‌های مصنوعی با برچسب روشن Demo.'],
    ['--version', 'Print version and exit.', 'نمایش نسخه و خروج.'],
    ['--help | -h', 'Print help and exit.', 'نمایش راهنما و خروج.'],
];
$table = '<div class="table-responsive"><table class="table"><thead><tr>'.$node('th', 'Option', 'گزینه').$node('th', 'Behavior', 'رفتار').'</tr></thead><tbody>';
foreach ($options as [$flag, $en, $fa]) { $table .= '<tr><td><code>'.$escape($flag).'</code></td>'.$node('td', $en, $fa).'</tr>'; }
$table .= '</tbody></table></div>';
$section('cli', 'Complete CLI reference and report examples', 'تمام گزینه‌های CLI و نمونه گزارش', $table
    .$code("sudo ./security-audit.sh --standard --full --no-color\nsudo ./security-audit.sh --deep --profile full --scan-seconds 60\nsudo ./security-audit.sh --quick --export-json /root/audit-quick.json\nsudo ./security-audit.sh --standard --export-html /root/audit-standard.html\nsudo ./security-audit.sh --output-dir /root/audit-2026-10-05\nsudo ./security-audit.sh --disk-thresholds 80,90,95 --critical-caps 85,75,65\n./security-audit.sh --self-test\n./security-audit.sh --demo --no-color")
    .$p('Each export target and output directory must be new. Parent directories must already exist, contain no symlink components and, for root exports, be trusted root-owned paths; writable non-sticky ancestors are rejected. Use a fresh /root report name. JSON and HTML can use relative filenames, but sudo does not change the working directory, so a relative export in an untrusted directory can fail. --export-html without a filename also defaults under the working directory.', 'هر فایل خروجی و پوشه گزارش باید جدید باشد. والد مسیر باید موجود و بدون مؤلفه Symlink باشد؛ برای خروجی root، مالکیت والدها باید root و قابل اعتماد باشد. والد قابل‌نوشتن بدون Sticky Bit رد می‌شود. نام تازه زیر /root انتخاب کنید. JSON و HTML نام نسبی می‌پذیرند، اما sudo پوشه جاری را عوض نمی‌کند؛ خروجی نسبی در پوشه نامطمئن ممکن است خطا بدهد. --export-html بدون نام فایل نیز زیر پوشه جاری مسیر پیش‌فرض می‌سازد.')
    .$p('Exit 0 means no HIGH/CRITICAL findings and at least 80% coverage, not a guaranteed score threshold. Exit 1 means high or critical findings; 2 means incomplete assessment; 3 means usage or runtime failure; 130 and 143 mean interruption. The risk exit takes precedence over incomplete coverage. Automation should retain the report and branch on these outcomes rather than treating every nonzero exit as a crash.', 'کد خروج صفر یعنی یافته HIGH/CRITICAL وجود ندارد و پوشش حداقل ۸۰ درصد است؛ حداقل امتیاز مشخصی را تضمین نمی‌کند. کد ۱ یافته بالا یا بحرانی، ۲ ممیزی ناقص، ۳ خطای استفاده یا اجرا و ۱۳۰ و ۱۴۳ وقفه هستند. نتیجه ریسک بر پوشش ناقص اولویت دارد. در Automation گزارش را نگه دارید و بر اساس همین نتایج تصمیم بگیرید؛ هر خروج غیرصفر Crash نیست.'));

$section('dashboard', 'Read the dashboard from context to priority findings', 'خواندن Dashboard از مشخصات میزبان تا ریسک‌های اولویت‌دار',
    $p('The terminal dashboard shows hostname, OS, kernel, UTC timestamp, distribution family, package manager, architecture, virtualization, uptime, privilege mode, primary IP, MAC and firewall summaries. It then displays capped posture points, raw points, evidence coverage, severity counts and per-category points and coverage.', 'Dashboard ترمینال نام میزبان، OS، Kernel، زمان UTC، خانواده توزیع، Package Manager، معماری، Virtualization، Uptime، حالت دسترسی، IP اصلی و خلاصه MAC و فایروال را نمایش می‌دهد. سپس امتیاز محدودشده، امتیاز خام، پوشش شواهد، شمارش Severity و امتیاز و پوشش هر دسته را می‌بینید.')
    .$p('System health reports maximum local disk and inode use plus memory pressure. Summary prints up to eight priority findings ordered CRITICAL, HIGH, MEDIUM, LOW and up to five unknown gaps. Findings include evidence and action text. --full adds all controls and technical metadata. Color and bar rendering adapt to terminal capabilities, width and UTF locale, with an ASCII fallback.', 'بخش سلامت سیستم بیشترین مصرف Disk و Inode محلی و فشار حافظه را نشان می‌دهد. Summary تا هشت یافته اولویت‌دار به ترتیب CRITICAL، HIGH، MEDIUM و LOW و تا پنج شکاف UNKNOWN چاپ می‌کند. یافته‌ها شواهد و اقدام پیشنهادی دارند. --full همه کنترل‌ها و Metadata فنی را اضافه می‌کند. رنگ و نمودار با قابلیت ترمینال، عرض و Locale سازگار می‌شوند و مسیر جایگزین ASCII وجود دارد.')
    .'<figure><img class="img-fluid" src="'.$image.'" loading="lazy" alt="Linux Security Auditor dashboard: posture points, category coverage and priority risks | داشبورد ممیزی امنیت لینوکس: امتیاز وضعیت، پوشش دسته‌ها و ریسک‌های اولویت‌دار" />'.$node('p', 'Dashboard illustration. Use your own report for host findings; --demo is synthetic.', 'تصویر Dashboard برای معرفی نمایش گزارش است. یافته‌های میزبان را از گزارش خودتان بخوانید؛ --demo داده مصنوعی می‌سازد.').'</figure>'
    .$p('JSON uses schema_version 2 and includes audit, host, scores, summary, categories, findings and bounded inventory. Finding status, internal state and severity are separate. When no scored evidence exists, scores.security is null, although compatibility aliases and terminal points can still be numeric. HTML has embedded responsive and print CSS, escaped evidence, a CSP and no external assets. The report directory also receives a detailed plain text report.', 'JSON دارای schema_version برابر ۲ و بخش‌های audit، host، scores، summary، categories، findings و Inventory محدود است. status، state داخلی و severity یافته جدا هستند. وقتی شواهد امتیازدار وجود ندارد، scores.security مقدار null دارد، هرچند Alias سازگاری و امتیاز ترمینال ممکن است عددی باشند. HTML دارای CSS داخلی واکنش‌گرا و چاپ، شواهد Escape‌شده، CSP و بدون Asset خارجی است. پوشه خروجی گزارش متن ساده کامل نیز دارد.'));

$section('patching', 'Patch management from cached evidence', 'بررسی Patch Management با شواهد Cache',
    $p('On Debian-family hosts, apt-get simulates upgrade with locking and package-cache writes disabled. Inst rows count pending upgrades; security-origin text flags security-pocket candidates without assigning CVE severity. The newest Packages index timestamp is a freshness heuristic: more than seven days is adverse, a future timestamp is unknown, and a recent index does not prove every repository is current.', 'روی خانواده Debian، apt-get با غیرفعال‌بودن Lock و نوشتن Package Cache، Upgrade را شبیه‌سازی می‌کند. ردیف Inst کاندید ارتقا را می‌شمارد؛ متن مبدأ Security کاندید بسته امنیتی را مشخص می‌کند و Severity مربوط به CVE تعیین نمی‌شود. زمان جدیدترین Index از نوع Packages فقط نشانه تازگی است: بیش از هفت روز نامطلوب، زمان آینده نامشخص و Index جدید هم اثبات به‌روز بودن همه مخازن نیست.')
    .$p('APT checks also cover dpkg --audit diagnostics, held packages, effective apt-config unattended-upgrade settings, insecure trust overrides, trusted source patterns, error-log indicators and apt-daily-upgrade.timer. Configured automation does not prove successful execution. History-log modification time is inventory, not evidence that a security update succeeded.', 'مسیر APT همچنین خروجی dpkg --audit، بسته‌های Hold، تنظیم Unattended Upgrade در apt-config، Override نامطمئن اعتماد، الگوی Source مورد اعتماد، نشانه خطای Log و apt-daily-upgrade.timer را بررسی می‌کند. تنظیم Automation اجرای موفق آن را اثبات نمی‌کند. زمان تغییر History Log اطلاعات موجودی است و مدرک نصب موفق Patch امنیتی نیست.')
    .$p('RHEL-family queries use DNF or YUM with --cacheonly and --noplugins, redirecting log and state paths to private temporary storage. check-update exit 100 is handled as available updates. updateinfo security rows are advisory/package candidates, not unique CVEs. Repository inventory, exclusions and signature-bypass patterns are inspected. Empty or unavailable security metadata remains UNKNOWN; cache completeness and subscription require independent evidence.', 'خانواده RHEL از DNF یا YUM با --cacheonly و --noplugins استفاده می‌کند و مسیر Log و State را به فضای موقت خصوصی می‌برد. خروج ۱۰۰ از check-update به معنی Update موجود پردازش می‌شود. ردیف Security در updateinfo کاندید Advisory یا بسته است و تعداد CVE یکتا نیست. موجودی مخازن، Exclusion و الگوی دورزدن Signature بررسی می‌شوند. Metadata امنیتی خالی یا ناموجود UNKNOWN می‌ماند؛ کامل‌بودن Cache و Subscription شواهد مستقل می‌خواهند.')
    .$p('SUSE runs cached zypper queries only when root can use bwrap with a read-only root mount and isolated network namespace. --no-refresh alone is insufficient because libzypp can rebuild caches. Without that sandbox or a usable cache, results remain UNKNOWN. Repository reachability is never tested.', 'SUSE فقط زمانی Queryهای Cache شده zypper را اجرا می‌کند که root بتواند bwrap را با Mount فقط‌خواندنی ریشه و Network Namespace جدا اجرا کند. --no-refresh به‌تنهایی کافی نیست، چون libzypp ممکن است Cache را بازسازی کند. بدون Sandbox یا Cache قابل استفاده، نتیجه UNKNOWN می‌ماند. دسترس‌پذیری مخزن از شبکه آزمایش نمی‌شود.')
    .$p('Reboot evidence is distribution-specific: Debian uses /run/reboot-required, RPM may use needs-restarting -r, and SUSE reboot status remains unknown. Running kernel and /boot images are inventoried. Debian compares installed package versions only within the running kernel flavor. RPM flavor/EVR correlation, including Oracle UEK/RHCK, is not guessed. SUPPORT_END may provide a local lifecycle hint, but extended entitlement, livepatch, current CVEs and overdue critical advisories remain separate questions.', 'شواهد نیاز به Reboot وابسته به توزیع است: Debian از /run/reboot-required، RPM در صورت وجود از needs-restarting -r استفاده می‌کند و وضعیت Reboot در SUSE نامشخص می‌ماند. Kernel جاری و Imageهای /boot ثبت می‌شوند. Debian نسخه بسته نصب‌شده را فقط در Flavor همان Kernel مقایسه می‌کند. ارتباط Flavor و EVR در RPM، از جمله Oracle UEK/RHCK، حدس زده نمی‌شود. SUPPORT_END ممکن است نشانه محلی چرخه پشتیبانی بدهد، اما Entitlement تمدیدشده، Livepatch، CVE جاری و Advisory بحرانی عقب‌افتاده پرسش‌های جدا هستند.'));

$section('users', 'Local users, password policy, PAM and sudo', 'ممیزی کاربران محلی، رمز، PAM و sudo',
    $p('Account checks use local passwd, group and shadow: extra UID 0 accounts, duplicate UIDs/GIDs, interactive service accounts, empty password fields, legacy or unrecognized hash formats, aging and expiry. Supported hash classifications include yescrypt, SHA-512 crypt and listed bcrypt prefixes. Hash values are neither exported nor cracked. A locked password does not revoke an SSH key or every PAM path.', 'بررسی حساب از passwd، group و shadow محلی استفاده می‌کند: UID صفر اضافی، UID/GID تکراری، حساب سرویس با Shell تعاملی، فیلد رمز خالی، قالب Hash قدیمی یا ناشناخته، Aging و Expiry. دسته‌بندی Hash شامل yescrypt، SHA-512 crypt و Prefixهای مشخص bcrypt است. مقدار Hash صادر یا شکسته نمی‌شود. قفل رمز به معنی لغو کلید SSH یا تمام مسیرهای PAM نیست.')
    .$p('Interactive home existence, ownership and broad permissions are checked, together with .netrc, .rhosts and .forward indicators, shell-history access and .ssh permissions. Authorized-key metadata is assessed without exporting key contents. External directory users and centrally enforced policies are outside this local identity inventory.', 'وجود Home تعاملی، مالکیت و مجوز گسترده آن بررسی می‌شود؛ نشانه .netrc، .rhosts و .forward، دسترسی History و مجوز .ssh نیز ثبت می‌شوند. Metadata کلیدهای مجاز بدون صدور محتوای کلید بررسی می‌شود. کاربران Directory بیرونی و سیاست اعمال‌شده مرکزی خارج از موجودی هویت محلی هستند.')
    .$p('PAM module references cover hashing, history, lockout, quality enforcement for root and nullok candidates. pwquality and faillock numeric settings are inventory because includes, snippets and module arguments may override them. The script does not reconstruct the complete effective PAM stack. Password aging is an organizational policy question, not proof of password strength.', 'Reference ماژول PAM شامل Hashing، History، Lockout، کیفیت رمز برای root و کاندید nullok است. مقادیر عددی pwquality و faillock اطلاعات موجودی‌اند، چون Include، Fragment و آرگومان ماژول ممکن است آن‌ها را تغییر دهند. ابزار کل Stack مؤثر PAM را بازسازی نمی‌کند. Aging رمز موضوع سیاست سازمان است و قوت رمز را اثبات نمی‌کند.')
    .$p('visudo -c validates sudoers syntax when available. Pattern checks flag NOPASSWD or disabled authentication, unrestricted ALL, wildcards, interpreter/editor delegation and SETENV candidates. use_pty, secure_path, logfile and timestamp_timeout references are inventoried without resolving all include order and defaults. Review effective privileges per administrative role before changing access.', 'در صورت وجود، visudo -c صحت Syntax مربوط به sudoers را می‌سنجد. بررسی الگو کاندید NOPASSWD یا Authentication غیرفعال، ALL نامحدود، Wildcard، واگذاری Interpreter/Editor و SETENV را مشخص می‌کند. Referenceهای use_pty، secure_path، logfile و timestamp_timeout بدون حل کامل ترتیب Include و Default ثبت می‌شوند. پیش از تغییر دسترسی، مجوز مؤثر هر نقش مدیریتی را بررسی کنید.'));

$section('ssh', 'SSH effective configuration and Match scope', 'امنیت SSH با تنظیم مؤثر و محدوده Match',
    $p('The auditor asks sshd -T for parsed effective settings. This is more useful than grepping one sshd_config file because the daemon applies defaults and configuration includes. A selected -C context also evaluates relevant Match rules. Without context, the report explicitly leaves Match and daemon-scope coverage unknown.', 'ابزار تنظیمات مؤثر Parse‌شده را از sshd -T می‌گیرد. این روش از grep یک فایل sshd_config کاربردی‌تر است، چون Daemon پیش‌فرض‌ها و Includeها را اعمال می‌کند. Context منتخب با -C نیز Match مرتبط را ارزیابی می‌کند. بدون Context، گزارش پوشش Match و محدوده Daemon را صریحاً نامشخص نگه می‌دارد.')
    .$code("sudo ./security-audit.sh --ssh-context 'user=admin,host=admin.example,addr=192.0.2.10' \\\n  --sshd-config /etc/ssh/sshd_config --full")
    .$p('Replace the example identity, hostname and source address with actual administrative contexts. Audit every allowed role and source range, plus separate sshd instances and custom daemon flags. One successful context is not global SSH assurance.', 'هویت، Hostname و آدرس مبدأ نمونه را با Context واقعی مدیریت جایگزین کنید. تمام نقش‌ها و محدوده مبدأ مجاز، Instanceهای جداگانه sshd و Flagهای سفارشی Daemon را بررسی کنید. موفقیت یک Context تضمین کل SSH نیست.')
    .$p('Checks include root/password/empty-password login, public keys, X11, gateway ports, host-based authentication, rhosts, user environment, authentication attempts and selected legacy crypto patterns. Extended checks cover MaxSessions, LoginGraceTime, StrictModes, alive interval/count, and selected Level 2 tunnel, logging and user-rc restrictions. MaxStartups and identity/MFA directives are inventoried. Root password login becomes critical only when the selected SSH settings and an active local root hash meet the implemented combination.', 'کنترل‌ها ورود root، رمز و رمز خالی، کلید عمومی، X11، Gateway Ports، Authentication مبتنی بر Host، rhosts، محیط کاربر، تعداد تلاش و الگوهای منتخب Crypto قدیمی را پوشش می‌دهند. بررسی تکمیلی MaxSessions، LoginGraceTime، StrictModes، Alive Interval/Count و محدودیت Level 2 برای Tunnel، Logging و User RC را دارد. MaxStartups و Directiveهای هویت و MFA ثبت می‌شوند. ورود root با رمز زمانی Critical می‌شود که تنظیم SSH منتخب و Hash فعال محلی root ترکیب پیاده‌سازی‌شده را تشکیل دهند.')
    .$p('A password-authentication warning is not an instruction to disable keyboard-interactive blindly: that path may implement MFA. Missing sshd tooling is not proof of insecure settings. Keep a tested administrative session and validate policy compatibility before applying any separately approved hardening.', 'هشدار Password Authentication دستور غیرفعال‌کردن کورکورانه Keyboard Interactive نیست؛ این مسیر ممکن است MFA را اجرا کند. نبود ابزار sshd ناامن‌بودن تنظیمات را ثابت نمی‌کند. هنگام اعمال Hardening مستقل و تأییدشده، نشست مدیریتی آزموده‌شده را نگه دارید و سازگاری سیاست را بسنجید.'));

$section('network', 'Firewall evidence and network exposure', 'فایروال و محدوده مواجهه شبکه',
    $p('UFW, nftables, iptables-save and ip6tables-save provide local rule inventories when readable. The auditor checks active UFW incoming defaults and simple broad allow patterns, inventories nft hooks and legacy base policies, and notes duplicate literal iptables rules and concurrent manager indicators. A ruleset being present is not a proof of an effective packet verdict; chain order, priorities, sets, jumps and NAT still matter.', 'UFW، nftables، iptables-save و ip6tables-save در صورت خواندنی‌بودن موجودی Rule محلی می‌دهند. ابزار Default ورودی UFW فعال و الگوهای ساده Allow گسترده را بررسی می‌کند، Hookهای nft و سیاست پایه Legacy را ثبت می‌کند و Rule تکراری لفظی iptables و نشانه Manager همزمان را نشان می‌دهد. وجود Ruleset اثبات Verdict مؤثر Packet نیست؛ ترتیب Chain، Priority، Set، Jump و NAT اهمیت دارند.')
    .$p('ss collects listening TCP/UDP sockets and established connections; ip supplies interfaces and IPv4/IPv6 routes. Non-loopback default-port candidates identify legacy services and databases/caches for review, without proving the protocol or authentication. Socket owners may need root. Custom ports can evade these port lists.', 'ss از Socketهای TCP/UDP شنونده و Connection برقرارشده اطلاعات می‌گیرد؛ ip رابط‌ها و Routeهای IPv4/IPv6 را می‌دهد. کاندید پورت پیش‌فرض روی آدرس غیرLoopback سرویس Legacy و Database/Cache را برای بازبینی مشخص می‌کند، ولی Protocol یا Authentication را اثبات نمی‌کند. دیدن مالک Socket ممکن است root بخواهد. پورت سفارشی ممکن است خارج از این فهرست باشد.')
    .$p('Listening on 0.0.0.0 or :: means a wildcard bind in the observed namespace. It does not establish public internet exposure. NAT, cloud security groups, load balancers, upstream firewalls, routing and source policy determine actual reachability. IPv6 enforcement parity and external reachability remain UNKNOWN because no external probe or cloud API request is performed. Verify both address families from an authorized external vantage point.', 'Listening روی 0.0.0.0 یا :: یعنی اتصال به آدرس Wildcard در Namespace مشاهده‌شده. این وضعیت دسترسی از اینترنت عمومی را ثابت نمی‌کند. NAT، Security Group ابری، Load Balancer، فایروال بالادستی، Routing و سیاست مبدأ دسترس‌پذیری واقعی را تعیین می‌کنند. برابری اجرای IPv6 و دسترسی بیرونی UNKNOWN می‌مانند، چون Probe بیرونی یا درخواست Cloud API انجام نمی‌شود. هر دو خانواده آدرس را از نقطه بیرونی مجاز اعتبارسنجی کنید.'));

$section('persistence', 'Cron, startup paths and systemd persistence', 'Cron، مسیرهای Startup و Persistence در systemd',
    $p('The script inspects system cron paths and per-user spool paths, local systemd directories, rc.local and ld.so.preload permissions. It inventories timers, running/enabled services, failed units, reboot jobs and deferred at jobs. Cron command bodies are withheld from reports because they may contain credentials; the auditor never runs discovered jobs.', 'اسکریپت مسیر Cron سیستمی و Spool کاربران، دایرکتوری محلی systemd، مجوز rc.local و ld.so.preload را بررسی می‌کند. Timer، سرویس Running/Enabled، Unit شکست‌خورده، Job زمان Reboot و Job معوق at ثبت می‌شوند. متن فرمان Cron به دلیل احتمال وجود Credential در گزارش نمایش داده نمی‌شود و ابزار Job کشف‌شده را اجرا نمی‌کند.')
    .$p('Bounded pattern scans flag download-to-shell, execution from temporary storage, base64 decode-to-execution, hidden script paths, reverse-shell syntax and system shell startup injection candidates. Recent modification times are context, not an unauthorized-change verdict. Without an approved baseline, the auditor cannot decide whether a job or timer is unauthorized.', 'اسکن محدود الگو، کاندید Download-to-Shell، اجرا از فضای موقت، Decode کردن Base64 و ارسال به اجرا، مسیر Script مخفی، Syntax مربوط به Reverse Shell و Injection در Startup سیستمی Shell را مشخص می‌کند. زمان تغییر تازه فقط زمینه است و حکم تغییر غیرمجاز نیست. بدون Baseline تأییدشده، ابزار نمی‌تواند غیرمجاز بودن Job یا Timer را تعیین کند.')
    .$p('A sample of up to 30 running services records root/default users, local unit fragments and writable fragments. systemd-analyze security supplies a bounded sandbox summary when available. Its exposure values are hardening suggestions, not vulnerability scores. User units, drop-ins, executables and deployment records still need a complete operator review.', 'نمونه‌ای از حداکثر ۳۰ سرویس Running، کاربر root یا پیش‌فرض، Fragment محلی و Fragment قابل‌نوشتن را ثبت می‌کند. systemd-analyze security در صورت وجود خلاصه محدود Sandbox می‌دهد. مقدار Exposure آن پیشنهاد Hardening است و امتیاز آسیب‌پذیری نیست. Unit کاربر، Drop-in، فایل اجرایی و سابقه Deployment همچنان بازبینی کامل مدیر را می‌خواهند.'));

$section('filesystem', 'Filesystem, permissions and capacity', 'امنیت Filesystem، مجوزها و ظرفیت',
    $p('Permission checks inspect owner and mode bits for passwd/group, shadow/gshadow and backups, sudoers fragments, cron directories, PAM, SSH configuration fragments, bootloader files, logging/audit configuration and other privileged paths. The masks express this tool’s baseline, not every vendor exception. Missing paths can be not applicable; unreadable protected paths are unknown.', 'بررسی Permission مالک و بیت Mode را برای passwd/group، shadow/gshadow و نسخه پشتیبان آن‌ها، Fragmentهای sudoers، Cron، PAM، تنظیم SSH، Bootloader، تنظیم Logging/Audit و مسیرهای حساس دیگر می‌سنجد. Maskها Baseline این ابزارند و همه استثناهای Vendor را پوشش نمی‌دهند. مسیر ناموجود ممکن است غیرقابل‌اعمال و مسیر محافظت‌شده ناخوانا نامشخص باشد.')
    .$p('Bounded local scans find world-writable regular files, unmapped ownership, SUID/SGID files, large files, sensitive filename permission candidates and hidden executables. SUID/SGID is an inventory requiring comparison with a trusted package baseline, not automatic evidence of a vulnerability. Credential filename checks inspect metadata rather than secret contents. Network filesystems are inventoried and excluded from file scans.', 'اسکن محدود محلی فایل عادی World Writable، مالک نامشخص، SUID/SGID، فایل بزرگ، کاندید مجوز نام حساس و Executable مخفی را پیدا می‌کند. SUID/SGID موجودی برای مقایسه با Baseline معتبر بسته است و خودکار مدرک آسیب‌پذیری نیست. بررسی نام Credential متکی به Metadata است و محتوای Secret را نمی‌خواند. Filesystem شبکه ثبت می‌شود و از اسکن فایل کنار می‌رود.')
    .$p('findmnt resolves the containing mount for paths such as /tmp, /var/tmp and /dev/shm, so a nonexistent separate partition is not invented. Sticky bit, nodev, nosuid, noexec and selected separate-mount policies are evaluated with profile and host-role exceptions. Mount restrictions can break workloads and must be tested separately.', 'findmnt، Mount دربرگیرنده مسیرهایی مثل /tmp، /var/tmp و /dev/shm را پیدا می‌کند و Partition جداگانه خیالی ساخته نمی‌شود. Sticky Bit، nodev، nosuid، noexec و سیاست‌های منتخب Mount جدا با توجه به Profile و استثنای نقش میزبان بررسی می‌شوند. محدودیت Mount ممکن است برنامه را مختل کند و باید مستقل آزمایش شود.')
    .$p('df -P -l and df -Pi -l record maximum local disk and inode use. Default thresholds are strictly above 80, 90 and 95 percent, so exactly 90 does not cross the HIGH threshold. A timed-out or inaccessible scan with no matches is inconclusive. Partial matches can produce an additional coverage record instead of silently claiming the whole scope passed.', 'df -P -l و df -Pi -l بیشترین مصرف Disk و Inode محلی را ثبت می‌کنند. آستانه‌های پیش‌فرض بزرگ‌تر از ۸۰، ۹۰ و ۹۵ درصد هستند؛ دقیقاً ۹۰ از آستانه HIGH عبور نمی‌کند. اسکن Timeout شده یا ناخوانا با نتیجه بدون Match قطعی نیست. Match جزئی ممکن است رکورد پوشش اضافی بسازد تا کل دامنه به‌اشتباه PASS معرفی نشود.'));

$section('kernel', 'Kernel hardening checks and role-dependent settings', 'کنترل‌های Kernel Hardening و وابستگی به نقش سرور',
    $p('The base sysctl checks expect randomize_va_space=2, kptr_restrict=2, dmesg_restrict=1, protected_hardlinks=1, protected_symlinks=1, tcp_syncookies=1 and suid_dumpable=0. ptrace_scope accepts the baseline 1 and stricter observed values 2 or 3. IPv4 all/default accept_redirects, send_redirects and accept_source_route, plus IPv6 all/default accept_redirects and all accept_source_route, are checked against zero.', 'کنترل پایه sysctl مقدار randomize_va_space=2، kptr_restrict=2، dmesg_restrict=1، protected_hardlinks=1، protected_symlinks=1، tcp_syncookies=1 و suid_dumpable=0 را انتظار دارد. ptrace_scope مقدار پایه ۱ و مقدار محدودتر ۲ یا ۳ را می‌پذیرد. accept_redirects، send_redirects و accept_source_route در all/default از IPv4، همچنین accept_redirects در all/default و accept_source_route در all از IPv6 با صفر بررسی می‌شوند.')
    .$p('Extended checks cover protected_fifos/protected_regular >=1, unprivileged_bpf_disabled >=1, perf_event_paranoid >=2, default rp_filter >=1, all/default log_martians=1, broadcast/bogus ICMP protections=1 and IPv4 secure_redirects=0 plus IPv6 default accept_source_route=0. Level 2 adds user namespaces=0, IPv6 router advertisements/forwarding=0 and sysrq=0. core_uses_pid=1 is also inspected.', 'کنترل تکمیلی protected_fifos و protected_regular حداقل ۱، unprivileged_bpf_disabled حداقل ۱، perf_event_paranoid حداقل ۲، rp_filter پیش‌فرض حداقل ۱، log_martians در all/default برابر ۱، محافظت Broadcast/Bogus ICMP برابر ۱، secure_redirects در IPv4 برابر صفر و accept_source_route پیش‌فرض IPv6 برابر صفر را دارد. Level 2 فضای نام کاربر صفر، Router Advertisement/Forwarding در IPv6 صفر و sysrq صفر را اضافه می‌کند. core_uses_pid=1 نیز بررسی می‌شود.')
    .$p('The tool observes all.rp_filter, IPv4 forwarding, lockdown, Secure Boot hints, boot security-bypass/debug patterns and selected optional module resolution. modprobe --show-depends does not load or unload modules. Routers, VPNs, containers and asymmetric routing can need different settings; assess those exceptions before remediation. The script never writes sysctls.', 'ابزار all.rp_filter، Forwarding در IPv4، Lockdown، نشانه Secure Boot، الگوی دورزدن امنیت یا Debug در Boot و Resolution ماژول اختیاری منتخب را مشاهده می‌کند. modprobe --show-depends ماژول را Load یا Unload نمی‌کند. Router، VPN، کانتینر و Routing نامتقارن ممکن است تنظیم متفاوت بخواهند؛ پیش از اصلاح استثنا را ارزیابی کنید. ابزار هرگز sysctl نمی‌نویسد.'));

$section('logging', 'Logging, auditing and trustworthy time', 'Logging، Auditing و زمان قابل اعتماد',
    $p('The auditor checks journald state, the persistent journal directory, /var/log permissions, rsyslog service and remote-forwarding indicators, logrotate.timer and configuration permissions. It inventories conventional authentication logs, world-writable logs and recently empty files. A journal directory does not establish effective retention; an empty file may be normal rotation. Remote SIEM delivery and unexplained gaps remain unknown without external receipt and an event baseline.', 'ابزار وضعیت journald، دایرکتوری Journal پایدار، مجوز /var/log، سرویس rsyslog و نشانه Forwarding، logrotate.timer و مجوز تنظیم آن را بررسی می‌کند. Log مرسوم Authentication، Log قابل‌نوشتن عمومی و فایل تازه خالی‌شده ثبت می‌شوند. وجود دایرکتوری Journal سیاست مؤثر Retention را ثابت نمی‌کند و فایل خالی ممکن است نتیجه Rotation عادی باشد. دریافت SIEM بیرونی و Gap توضیح‌ناپذیر بدون Receipt مستقل و Baseline رویداد نامشخص می‌مانند.')
    .$p('auditd activity is separate from rule coverage. auditctl -s supplies enabled, lost and backlog_limit, with event loss receiving an adverse result. auditctl -l is checked for patterns covering identity, sudo, login/logout, privileged execution, module, clock, network and MAC changes. Matches are not proof of complete semantics, architecture coverage or delivered events. Root may still lack CAP_AUDIT_CONTROL.', 'فعال‌بودن auditd با پوشش قواعد فرق دارد. auditctl -s مقدار enabled، lost و backlog_limit را می‌دهد و از دست رفتن رویداد نتیجه نامطلوب می‌گیرد. auditctl -l برای الگوی هویت، sudo، Login/Logout، اجرای ممتاز، تغییر Module، ساعت، شبکه و MAC بررسی می‌شود. Match اثبات Semantics کامل، پوشش Architecture یا دریافت رویداد نیست. حتی root ممکن است CAP_AUDIT_CONTROL نداشته باشد.')
    .$p('timedatectl synchronization and chronyc tracking offset/leap fields provide time evidence. The audit does not initiate an NTP probe. Validate the actual daemon and approved sources, since inaccurate time affects event correlation and package-index age interpretation.', 'Synchronization در timedatectl و Offset/Leap در chronyc tracking شواهد زمان می‌دهند. ممیزی Probe مربوط به NTP آغاز نمی‌کند. Daemon واقعی و Source تأییدشده را بررسی کنید، چون زمان اشتباه تطبیق رخدادها و تفسیر سن Index بسته را مختل می‌کند.'));

$section('mac', 'AppArmor and SELinux without assuming missing means disabled', 'AppArmor و SELinux؛ نبود ابزار به معنی غیرفعال‌بودن نیست',
    $p('RHEL-family detection selects SELinux as the expected MAC; other families default to AppArmor, with observed SELinux enforcing/permissive state adjusting the selection. getenforce and /etc/selinux/config distinguish runtime and configured mode. Policy type, recent AVC indicators and unconfined service contexts are inspected. Denials are counted without exporting audit records or automatically generating allow rules.', 'تشخیص خانواده RHEL، SELinux را MAC مورد انتظار انتخاب می‌کند؛ سایر خانواده‌ها به‌طور پیش‌فرض AppArmor دارند و مشاهده Enforcing/Permissive در SELinux انتخاب را اصلاح می‌کند. getenforce و /etc/selinux/config وضعیت اجرا و تنظیم را جدا می‌کنند. Policy Type، نشانه AVC اخیر و Context سرویس Unconfined بررسی می‌شوند. Denial بدون صدور رکورد Audit یا ساخت خودکار Allow Rule شمرده می‌شود.')
    .$p('aa-status provides AppArmor enabled and loaded/enforced/complain/unconfined counts when readable. Complain profiles need review, and loaded profiles do not prove every service is confined. Missing inspection commands become UNKNOWN or NOT_APPLICABLE according to scope, not an automatic disabled verdict. Confirmed disabled expected MAC can become critical outside the explicitly handled docker/lxc environments.', 'aa-status در صورت خواندنی‌بودن وضعیت AppArmor و تعداد Loaded، Enforced، Complain و Unconfined را می‌دهد. Profile در حالت Complain بازبینی می‌خواهد و تعداد Loaded پوشش همه سرویس‌ها را ثابت نمی‌کند. نبود فرمان بررسی با توجه به محدوده UNKNOWN یا NOT_APPLICABLE است و خودکار Disabled تلقی نمی‌شود. MAC مورد انتظار که غیرفعال‌بودنش تأیید شود می‌تواند خارج از محیط‌های صریح docker/lxc نتیجه Critical بگیرد.'));

$section('containers', 'Docker and Podman through existing local APIs', 'ممیزی Docker و Podman از API محلی موجود',
    $p('Docker is queried through /var/run/docker.sock with an isolated client configuration. Podman uses its existing service Unix socket, /run/podman/podman.sock for root or the selected user runtime socket without root. The local Podman storage CLI is avoided because it may initialize storage. Remote daemon contexts are not inherited, and the tool does not start a missing Podman service.', 'Docker از /var/run/docker.sock با Client Configuration جدا Query می‌شود. Podman از Service Unix Socket موجود، برای root در /run/podman/podman.sock یا Socket Runtime کاربر منتخب در اجرای بدون root، استفاده می‌کند. CLI محلی Storage در Podman کنار گذاشته شده چون ممکن است Storage را Initialize کند. Context مربوط به Daemon دوردست به ارث نمی‌رسد و سرویس Podman ناموجود راه‌اندازی نمی‌شود.')
    .$p('Up to 100 running containers are sampled for privileged mode, host network/PID/IPC, root or unspecified user, SYS_ADMIN/ALL/SYS_PTRACE capabilities, writable root filesystem, missing no-new-privileges, runtime socket mounts, host-root/sensitive/writable host mounts, published ports and unconfined security options. Names, environment and command arguments are not collected. Missing or partially readable runtime evidence is explicit.', 'حداکثر ۱۰۰ کانتینر Running برای Privileged Mode، Host Network/PID/IPC، کاربر root یا نامشخص، Capabilityهای SYS_ADMIN/ALL/SYS_PTRACE، Root Filesystem قابل‌نوشتن، نبود no-new-privileges، Mount سوکت Runtime، ریشه میزبان یا مسیر حساس و Host Mount قابل‌نوشتن، Published Port و گزینه Unconfined نمونه‌برداری می‌شوند. نام، Environment و آرگومان فرمان جمع‌آوری نمی‌شوند. نبود یا خوانایی ناقص Runtime صریح ثبت می‌شود.')
    .$p('API socket permissions, exited-container counts, insecure-registry configuration candidates and port 2375/2376 listener candidates add host context. A world-writable runtime socket is critical. Published ports do not prove internet exposure, and those TCP ports do not prove an unauthenticated Docker API. Image currency remains UNKNOWN or not applicable: image age cannot establish vulnerabilities. Use a separate approved image scanner and registry policy.', 'مجوز API Socket، تعداد کانتینر Exited، کاندید تنظیم Insecure Registry و Listener پورت 2375/2376 زمینه میزبان را اضافه می‌کنند. Runtime Socket قابل‌نوشتن عمومی Critical است. Published Port دسترسی اینترنت را ثابت نمی‌کند و این پورت‌های TCP هم API بدون Authentication را اثبات نمی‌کنند. وضعیت به‌روز بودن Image نامشخص یا غیرقابل‌اعمال می‌ماند؛ سن Image آسیب‌پذیری را مشخص نمی‌کند. Scanner مستقل Image و سیاست Registry تأییدشده لازم است.'));

$section('threat', 'Threat indicators, cryptography and recovery gaps', 'نشانه‌های تهدید، رمزنگاری و شکاف بازیابی',
    $p('Threat paths observe /proc executable links, deleted-but-running executables, temporary/home execution, writable root-owned running files, shell processes owned by web identities, mining-name patterns and hidden executables. CPU and memory snapshots describe health. Software upgrades can explain deleted executables; deployment tasks can explain temporary binaries. These are investigation leads, not a malware diagnosis or forensic clearance.', 'مسیر Threat لینک Executable در /proc، فایل حذف‌شده ولی Running، اجرا از Temp/Home، فایل اجرایی Running متعلق به root با مجوز Write گسترده، Shell با هویت Web، الگوی نام Miner و Executable مخفی را مشاهده می‌کند. Snapshot مربوط به CPU و حافظه وضعیت سلامت است. Upgrade ممکن است فایل حذف‌شده Running و Deployment ممکن است Binary موقت را توضیح دهد. این‌ها سرنخ تحقیق‌اند و تشخیص Malware یا تأیید Forensic پاک‌بودن نیستند.')
    .$p('Standard mode verifies selected core packages; deep uses broader dpkg -V or rpm -Va --noscripts. Changed configuration files may be legitimate, and local package metadata may itself be tampered with. Independent signed baselines and EDR/SIEM correlation are needed for stronger assurance.', 'Standard بسته‌های اصلی منتخب را Verify می‌کند؛ Deep از dpkg -V گسترده‌تر یا rpm -Va --noscripts استفاده می‌کند. تغییر Configuration ممکن است مجاز باشد و Metadata محلی بسته هم ممکن است دستکاری شده باشد. برای اطمینان بیشتر Baseline مستقل امضاشده و تطبیق با EDR/SIEM لازم است.')
    .$p('Crypto checks inventory OpenSSL vendor version, flag selected legacy TLS/cipher configuration patterns and inspect up to 100 public .crt files in /etc/ssl/certs outside quick mode for expiry and 30-day expiry candidates. Trust-store certificates are not necessarily served certificates. No live TLS handshake is performed, and private-key contents are not opened by this certificate path. Credential filename and cloud-init permission candidates likewise require local confirmation.', 'کنترل Crypto نسخه Vendor مربوط به OpenSSL، الگوهای منتخب تنظیم TLS/Cipher قدیمی و خارج از Quick حداکثر ۱۰۰ فایل عمومی .crt در /etc/ssl/certs را برای Expiry و انقضای ۳۰ روز آینده بررسی می‌کند. Certificate در Trust Store لزوماً Certificate ارائه‌شده سرویس نیست. Handshake زنده TLS انجام نمی‌شود و این مسیر بررسی Certificate محتوای Private Key را باز نمی‌کند. کاندید نام Credential و مجوز Cloud-init نیز تأیید محلی می‌خواهد.')
    .$p('Cloud identification uses DMI hints without calling metadata endpoints. IMDS/IAM policy, actual disk encryption coverage, backup recoverability and workload security remain manual evidence gaps. A backup agent or recent backup filename cannot prove an off-host copy or a working restore.', 'شناسایی Cloud از نشانه DMI بدون فراخوانی Metadata Endpoint استفاده می‌کند. سیاست IMDS/IAM، پوشش واقعی Encryption دیسک، قابلیت بازیابی Backup و امنیت Workload شکاف شواهد دستی می‌مانند. وجود Backup Agent یا نام فایل Backup تازه، کپی Off-host یا Restore موفق را اثبات نمی‌کند.'));

$section('read-only', 'Read-only design and private evidence', 'طراحی Read-Only و حفاظت از گزارش',
    $p('The auditor does not refresh repositories, install or upgrade packages, change firewall rules, chmod/chown audited files, restart services, load/unload modules or write sysctls. The chmod command in the setup example is an operator action to make the downloaded script executable. It is not host remediation by the auditor.', 'ممیز مخزن را Refresh نمی‌کند، بسته نصب یا Upgrade نمی‌کند، Rule فایروال را تغییر نمی‌دهد، روی فایل ممیزی‌شده chmod/chown اجرا نمی‌کند، سرویس Restart و Module Load/Unload نمی‌کند و sysctl نمی‌نویسد. chmod در مثال آماده‌سازی، اقدام مدیر برای Executable شدن فایل دانلودی است و اصلاح میزبان توسط ممیز نیست.')
    .$p('Read-only refers to inspected configuration and workloads, not zero filesystem writes. umask 077, a private temporary directory under /tmp and requested private reports are part of normal execution. Temporary files are cleaned on exit; reports remain. Self-test also writes isolated fixtures. No network probes or package downloads run, though local daemon sockets are used for container inspection.', 'Read-Only به تنظیمات و Workload ممیزی‌شده اشاره دارد و به معنی صفر نوشتن در Filesystem نیست. umask برابر 077، دایرکتوری موقت خصوصی زیر /tmp و گزارش خصوصی درخواستی بخشی از اجرای عادی هستند. فایل موقت در خروج پاک می‌شود و گزارش باقی می‌ماند. Self-test نیز Fixture جدا می‌نویسد. Probe شبکه و Download بسته انجام نمی‌شود، ولی برای بررسی کانتینر از Socket محلی Daemon استفاده می‌شود.')
    .$p('Reports can contain hostnames, accounts, paths and network metadata. Bounded inventories redact selected comments and descriptions; process arguments, environments and cron command bodies are withheld. Redaction is not permission to publish a report. Keep it in approved private storage and share only the evidence needed for a remediation ticket.', 'گزارش می‌تواند Hostname، حساب، مسیر و Metadata شبکه داشته باشد. Inventory محدود، Comment و Description منتخب را حذف می‌کند و آرگومان Process، Environment و متن فرمان Cron صادر نمی‌شوند. حذف بعضی داده‌ها مجوز انتشار عمومی گزارش نیست. گزارش را در Storage خصوصی مجاز نگه دارید و برای Ticket اصلاح فقط شواهد لازم را به اشتراک بگذارید.'));

$section('validation', 'Validation evidence and what remains unverified', 'شواهد Validation و موارد تأییدنشده',
    $p('The supplied VALIDATION.md records a passing bash -n check and isolated self-test with 22 OS detection fixtures, color/ASCII, scoring, status mapping, JSON, temporary-path and utility/privilege checks. It reports a historical 67-test regression suite, but that suite and the claimed live report/catalogue files are not included in the supplied two-file package. These historical results are documented evidence, not a new run performed by this article.', 'VALIDATION.md تحویلی موفقیت bash -n و Self-test جدا با ۲۲ Fixture تشخیص OS، رنگ/ASCII، امتیاز، نگاشت وضعیت، JSON، مسیر موقت و ابزارها/Privilege را ثبت کرده است. سند از ۶۷ تست Regression تاریخی می‌گوید، اما آن Suite و فایل گزارش زنده و Catalogue ادعاشده در بسته دو فایلی تحویلی وجود ندارند. این نتایج سابقه مستند هستند و اجرای تازه توسط مقاله محسوب نمی‌شوند.')
    .$code("bash -n security-audit.sh\n./security-audit.sh --self-test")
    .$p('ShellCheck was unavailable in the documented environment, so no successful ShellCheck result is claimed. Native non-root integration and syscall-level tracing were blocked; browser-rendered verification of exported HTML was also unavailable there. On an appropriate Linux staging host, rerun syntax/self-test, validate actual distro commands, and optionally run shellcheck security-audit.sh when installed. The command is a suggested next check, not evidence that it already passed.', 'ShellCheck در محیط مستند موجود نبوده و موفقیت آن ادعا نمی‌شود. Integration واقعی بدون root و Trace سطح Syscall مسدود بوده؛ بررسی بصری HTML خروجی در Browser نیز آنجا انجام نشده است. روی Linux مناسب در Staging، Syntax/Self-test و فرمان واقعی توزیع را بررسی کنید و در صورت نصب، shellcheck security-audit.sh را اجرا کنید. این دستور بررسی پیشنهادی است و مدرک موفقیت قبلی نیست.')
    .$p('The observed registry lists 427 records: 108 inventory, 293 automated checks, 24 manual-evidence gaps and 2 coverage records. Those are scoped observations, not a guaranteed fixed count per run. The historical summary contains many UNKNOWN results and two HIGH findings. A risk exit 1 is expected in such a run; it is not evidence of a crash or a verdict on your own server.', 'Registry مشاهده‌شده ۴۲۷ رکورد دارد: ۱۰۸ Inventory، ۲۹۳ کنترل خودکار، ۲۴ شکاف شواهد دستی و ۲ رکورد پوشش. این تعداد به دامنه اجرای ثبت‌شده محدود است و تعداد ثابت تضمین‌شده هر اجرا نیست. خلاصه تاریخی UNKNOWN زیاد و دو یافته HIGH دارد. کد خروج ریسک ۱ در چنین اجرا طبیعی است و مدرک Crash یا نتیجه درباره سرور شما نیست.'));

$section('limitations', 'Limits and an operational review workflow', 'محدودیت‌ها و روند بازبینی عملیاتی',
    $p('This is not a full CVE scanner, penetration test, certified CIS Benchmark assessment or malware detector. Selected CIS labels lack verified official section mappings. Profiles choose a local policy subset and can exclude relevant controls. Compliance, attack-surface and threat values always need their coverage and scope alongside them.', 'این ابزار CVE Scanner کامل، Penetration Test، ممیزی دارای گواهی CIS Benchmark یا Malware Detector نیست. برچسب CIS منتخب نگاشت رسمی تأییدشده شماره بند ندارد. Profile زیرمجموعه سیاست محلی را انتخاب می‌کند و ممکن است کنترل مرتبط را حذف کند. عدد Compliance، Attack Surface و Threat همیشه باید همراه پوشش و محدوده خوانده شود.')
    .$p('A compromised host may lie through its tools or local metadata. Point-in-time snapshots are not continuous monitoring. Timeouts, namespace boundaries, absent utilities, distribution differences and root capability restrictions limit conclusions. Public reachability, application authentication, vendor backports, subscription and recovery cannot be inferred from a few local settings.', 'میزبان آلوده ممکن است از طریق ابزار یا Metadata محلی اطلاعات غلط بدهد. Snapshot لحظه‌ای Monitoring پیوسته نیست. Timeout، مرز Namespace، ابزار ناموجود، تفاوت توزیع و محدودیت Capability حتی برای root نتیجه را محدود می‌کنند. دسترسی عمومی، Authentication برنامه، Backport شرکت سازنده، Subscription و Recovery از چند تنظیم محلی قابل استنتاج نیستند.')
    .$p('Begin with quick mode on a staging host, then run standard with a fresh private report directory. Record version, profile, privilege, timestamps and gaps. Triage critical/high evidence against the real server role, open reviewed remediation tasks, and collect external evidence for unknown controls. After approved changes, rerun with the same profile and scope and compare both coverage and findings, not only the headline score.', 'از Quick در Staging شروع کنید و سپس Standard را با پوشه گزارش خصوصی تازه اجرا کنید. نسخه، Profile، Privilege، زمان و شکاف‌ها را ثبت کنید. شواهد Critical/High را با نقش واقعی سرور تطبیق دهید، کار اصلاح قابل بازبینی بسازید و برای UNKNOWN شواهد بیرونی بگیرید. پس از تغییر تأییدشده با Profile و محدوده یکسان دوباره اجرا کنید و پوشش و یافته را مقایسه کنید؛ فقط امتیاز اصلی کافی نیست.'));

$links = '<ul>';
foreach ([
    ['enable-ssh-linux-complete-guide', 'SSH administration and access validation', 'مدیریت SSH و اعتبارسنجی دسترسی'],
    ['linux-security-account-access-management', 'Linux accounts and restricted sudo', 'حساب Linux و دسترسی محدود sudo'],
    ['ubuntu-date-time-settings', 'Ubuntu time synchronization with Chrony', 'همگام‌سازی زمان Ubuntu با Chrony'],
    ['nginx-installation-configuration-ubuntu', 'NGINX deployment and service configuration', 'استقرار NGINX و تنظیم سرویس'],
] as [$target, $en, $fa]) {
    if (! is_file(__DIR__.'/../../../legacy/articles/'.$target.'.html')) { throw new RuntimeException('Missing internal target: '.$target); }
    $links .= '<li><a href="/articles/'.$target.'">'.$node('span', $en, $fa).'</a></li>';
}
$links .= '</ul>';
$section('related-reading', 'Related operational reading', 'مطالعه مرتبط برای عملیات سرور', $links);
$faq = '';
foreach ($localizations['en']['faq'] as $i => [$q, $a]) { $faq .= '<div class="article-faq-item">'.$node('h3', $q, $localizations['fa']['faq'][$i][0]).$p($a, $localizations['fa']['faq'][$i][1]).'</div>'; }
$section('faq', 'Frequently asked questions', 'پرسش‌های متداول', $faq);
$section('conclusion', 'Turn findings into reviewed infrastructure work', 'تبدیل یافته به کار عملیاتی قابل بازبینی',
    $p('For Linux administrators, DevOps, security and infrastructure engineers, the useful output is a defensible list of observations, risks and unanswered questions. The script makes a broad local review repeatable while keeping configuration changes outside the audit. Use its evidence to prioritize work, validate exceptions and ask for the external checks that a host-only assessment cannot supply.', 'برای Linux Admin، DevOps، Security Engineer و Infrastructure Engineer خروجی ارزشمند، فهرست قابل دفاع مشاهدات، ریسک‌ها و پرسش‌های بی‌پاسخ است. اسکریپت بازبینی گسترده محلی را تکرارپذیر می‌کند و تغییر تنظیمات را بیرون از ممیزی نگه می‌دارد. از شواهد برای اولویت کار، تأیید استثنا و درخواست بررسی بیرونی که ارزیابی داخل Host نمی‌دهد استفاده کنید.'));

$toc = '';
$body = '';
foreach ($sections as $s) {
    $toc .= '<li class="article-nav-item"><a href="#'.$s['id'].'">'.$node('span', $s['en'], $s['fa']).'</a></li>'."\n";
    $body .= $s['html']."\n";
}
$schema = ['@context' => 'https://schema.org', '@type' => 'Article', 'headline' => $localizations['en']['title'], 'description' => $localizations['en']['description'], 'inLanguage' => 'en', 'url' => $url, 'mainEntityOfPage' => $url, 'image' => 'https://meetaj.ir'.$image, 'datePublished' => '2026-10-05T00:00:00+03:30', 'dateModified' => '2026-10-05', 'author' => ['@type' => 'Person', 'name' => 'AmirHossein Jalalian']];
$json = fn ($value): string => json_encode($value, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES | JSON_HEX_TAG | JSON_HEX_AMP | JSON_THROW_ON_ERROR);
$html = '<!doctype html><html lang="en" dir="ltr" data-article-language="en"><head><meta charset="UTF-8" />'
    .'<title>'.$escape($localizations['en']['meta_title']).'</title><meta name="viewport" content="width=device-width, initial-scale=1" />'
    .'<meta name="description" content="'.$escape($localizations['en']['description']).'" /><meta name="keywords" content="'.$escape(implode(', ', $localizations['en']['keywords'])).'" />'
    .'<meta name="article:content-language" content="en" /><meta name="author" content="AmirHossein Jalalian" /><meta name="robots" content="index, follow" /><link rel="canonical" href="'.$url.'" />'
    .'<meta property="og:type" content="article" /><meta property="og:title" content="'.$escape($localizations['en']['title']).'" /><meta property="og:description" content="'.$escape($localizations['en']['description']).'" /><meta property="og:url" content="'.$url.'" /><meta property="og:image" content="https://meetaj.ir'.$image.'" /><meta name="twitter:card" content="summary_large_image" />'
    .'<script type="application/ld+json">'.$json($schema).'</script><script id="article-localizations" type="application/json">'.$json($localizations).'</script>'
    .'</head><body class="article-page theme-linux"><header><nav><ul>'.$toc.'</ul></nav></header><main>'
    .'<section class="article-hero article-header hero"><span class="article-category" data-en="Linux" data-fa="لینوکس">Linux</span>'
    .'<h1 class="article-title hero-title" data-en="'.$escape($localizations['en']['title']).'" data-fa="'.$escape($localizations['fa']['title']).'">'.$escape($localizations['en']['title']).'</h1>'
    .'<p class="article-excerpt hero-subtitle" data-en="'.$escape($localizations['en']['description']).'" data-fa="'.$escape($localizations['fa']['description']).'">'.$escape($localizations['en']['description']).'</p>'
    .'<img class="article-hero-thumbnail" src="'.$image.'" alt="Linux Security Auditor dashboard | داشبورد بررسی امنیت لینوکس" /></section>'
    .'<article class="article-body">'.$body.'</article></main></body></html>'."\n";
file_put_contents(__DIR__.'/../../../legacy/articles/'.$slug.'.html', $html);
echo 'Generated '.$slug.' with '.count($sections)." bilingual sections.\n";
