<?php
// Editorial source: bilingual Catalyst-only runbook; generated HTML feeds the existing importer.
$root = dirname(__DIR__);
$slug = 'cisco-catalyst-layer-2-layer-3-switch-hardening';
$title = ['en'=>'Cisco Layer 2 & Layer 3 Switch Hardening Best Practices', 'fa'=>'هاردنینگ امنیتی سوئیچ‌های Cisco لایه 2 و لایه 3'];
$desc = ['en'=>'Enterprise Cisco Catalyst IOS/IOS XE hardening: AAA, SSH, SNMPv3, DHCP Snooping, DAI, STP, management ACLs and independent L2/L3 configurations.', 'fa'=>'راهنمای عملیاتی هاردنینگ Cisco Catalyst در IOS و IOS XE؛ امنیت مدیریت، DHCP Snooping، DAI، STP، ACL و پیکربندی مستقل سوئیچ لایه ۲ و لایه ۳.'];
$parts = []; $toc = [];
function e($v) { return htmlspecialchars($v, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8'); }
function dual($tag, $en, $fa, $attrs='') { return '<'.$tag.' '.$attrs.' data-en="'.e($en).'" data-fa="'.e($fa).'">'.e($en).'</'.$tag.'>'; }
function p($en,$fa) { global $parts; $parts[]=dual('p',$en,$fa); }
function code($v) { global $parts; $parts[]='<pre dir="ltr"><code class="language-cisco">'.e(trim($v)).'</code></pre>'; }
function sec($id,$en,$fa) { global $parts,$toc; if ($toc) $parts[]='</section>'; $toc[]=[$id,$en,$fa]; $parts[]='<section id="'.$id.'">'.dual('h2',$en,$fa); }
function note($en,$fa) { global $parts; $parts[]='<div class="article-callout article-callout--warning" role="note">'.dual('p',$en,$fa).'</div>'; }
function dependency($en,$fa) { p($en.' Verify command availability for your Catalyst platform and IOS/IOS XE release before deployment.', $fa.' Verify command availability for your Catalyst platform and IOS/IOS XE release before deployment.'); }
function feature($goal,$risk,$cfg,$how,$verify,$prod) {
    p('Goal: '.$goal[0], 'هدف: '.$goal[1]); p('Security risk: '.$risk[0], 'ریسک امنیتی: '.$risk[1]);
    p('Configuration — global configuration mode unless an interface or line context is shown.', 'پیکربندی — در حالت Global Configuration اجرا کنید مگر آنکه Context اینترفیس یا Line مشخص شده باشد.'); code($cfg);
    p('Operation: '.$how[0], 'نحوه عملکرد: '.$how[1]); p('Verification: '.$verify[0], 'اعتبارسنجی: '.$verify[1]); p('Production: '.$prod[0], 'نکات Production: '.$prod[1]);
}
function table($headers,$rows) { global $parts; $html='<table><thead><tr>'; foreach($headers as $h) $html.=dual('th',...$h); $html.='</tr></thead><tbody>'; foreach($rows as $r) { $html.='<tr>'; foreach($r as $c) $html.=dual('td',...$c); $html.='</tr>'; } $parts[]=$html.'</tbody></table>'; }
function figure($filename,$en,$fa) {
    global $root,$parts;
    $path='/assets/img/articles/content/'.$filename;
    $source=$root.'/resources'.$path;
    if (!is_file($source)) throw new RuntimeException('Missing article image: '.$source);
    $destination=$root.'/public'.$path;
    if (!is_dir(dirname($destination))) mkdir(dirname($destination),0775,true);
    copy($source,$destination);
    $size=getimagesize($source);
    $parts[]='<figure><img src="'.e($path).'" alt="'.e($en).'" width="'.$size[0].'" height="'.$size[1].'" loading="lazy" decoding="async"><figcaption>'.dual('span',$en,$fa).'</figcaption></figure>';
}

sec('architecture','Architecture and deployment contract','معماری و الزامات استقرار');
figure('Modern Network Switch Hardening Topology.png','Cisco Catalyst hardening topology and separate management network','توپولوژی هاردنینگ Cisco Catalyst و شبکهٔ مدیریت مجزا');
p('This runbook is for Network Administrators, Network Engineers and Infrastructure Engineers operating Cisco Catalyst Layer 2 and Layer 3 switches with Cisco IOS or IOS XE. Management Plane protects administrative access and telemetry; Control Plane protects STP, routing adjacencies and CPU resources; Data Plane / Layer 2 Security protects endpoint traffic and trust boundaries.', 'این راهنما برای Network Administrator، Network Engineer و Infrastructure Engineer و صرفاً سوئیچ‌های Cisco Catalyst لایه ۲ و ۳ با IOS یا IOS XE است. Management Plane دسترسی مدیریتی و Telemetry، Control Plane پروتکل STP و همسایگی Routing و منابع CPU، و Data Plane / Layer 2 Security ترافیک کاربران و مرزهای اعتماد را محافظت می‌کند.');
code("Internet / WAN\n      |\nFirewall\n      |\nCore / L3 Switch\n      |\nDistribution\n      |\nAccess L2 Switches\n      |\nUsers / Phones / AP / Printers\n\nVLAN 99 - Management\nNMS / Zabbix / Syslog / NTP");
p('The firewall is only an architectural boundary; this article configures Catalyst switches exclusively. VLAN 99 is a separate management broadcast domain, not an authorization mechanism. Restrict its routing and physical access. Examples use RFC1918 networks: users 10.10.10.0/24, management 10.99.99.0/24, transit 10.255.255.0/30. These are invented examples, not organization addresses.', 'Firewall فقط مرز معماری است و پیکربندی مقاله منحصراً مربوط به Catalyst است. VLAN 99 یک Broadcast Domain جدا برای مدیریت است و به‌تنهایی کنترل دسترسی ایجاد نمی‌کند؛ Routing و دسترسی فیزیکی آن را محدود کنید. شبکه‌های نمونه RFC1918 عبارت‌اند از کاربران 10.10.10.0/24، مدیریت 10.99.99.0/24 و Transit برابر 10.255.255.0/30؛ همگی مثال ساختگی‌اند.');
dependency('The baseline assumes IPv4, a global routing table, classic interface syntax and a tested Rapid-PVST design. Dedicated management ports in a VRF need VRF-specific routes and service syntax. Licenses, ASIC resources, interface types, VTY counts, crypto policies and release behavior differ; validate each block with CLI help and the matching command reference.', 'فرض نمونه‌ها IPv4، جدول Routing عمومی، Syntax کلاسیک اینترفیس و طراحی آزموده‌شده Rapid-PVST است. پورت مدیریت داخل VRF به Route و Syntax سرویس مخصوص VRF نیاز دارد. License، منابع ASIC، نوع پورت، تعداد VTY، سیاست رمزنگاری و رفتار نسخه‌ها متفاوت است؛ هر بلوک را با CLI Help و Command Reference متناظر بررسی کنید.');
note('Production-ready means a reviewed deployment template, not blind paste. Preserve existing configuration, use console/out-of-band access, stage changes on one port/VLAN, test a new SSH session, and save only after validation. These IPv4 controls do not secure IPv6: separately assess IPv6 management ACLs, RA Guard and DHCPv6 Guard on supported Catalyst releases.', 'Production-Ready یعنی Template قابل بازبینی و استقرار، نه اجرای کورکورانه. تنظیمات فعلی را حفظ کنید، Console یا Out-of-Band در دسترس داشته باشید، ابتدا یک پورت/VLAN را تست کنید، SSH جدید باز کنید و فقط پس از اعتبارسنجی Save کنید. کنترل‌های IPv4 این مقاله IPv6 را امن نمی‌کنند؛ ACL مدیریتی IPv6، RA Guard و DHCPv6 Guard را جداگانه در نسخه پشتیبانی‌شده بررسی کنید.');

sec('prechecks','1. Pre-Hardening Checks','۱. بررسی پیش از هاردنینگ');
code("show version\nshow inventory\nshow running-config\nshow vlan brief\nshow interfaces status\nshow interfaces trunk\nshow spanning-tree\nshow ip interface brief\nshow ip route\nshow users\nshow logging");
table([['Command','فرمان'],['Check before change','بررسی پیش از تغییر']], array_map(fn($r)=>[[$r[0],$r[0]],[$r[1],$r[2]]],[
['show version','Image, release, uptime and capabilities','Image، نسخه، Uptime و قابلیت‌ها'],['show inventory','PID, modules and stack members','PID، ماژول‌ها و اعضای Stack'],['show running-config','AAA, ACLs, services and existing dependencies','AAA، ACL، سرویس‌ها و وابستگی موجود'],['show vlan brief','User, voice, management and unused VLANs','VLAN کاربر، Voice، مدیریت و پورت بلااستفاده'],['show interfaces status','Port roles, speed and err-disabled ports','نقش پورت، سرعت و وضعیت err-disabled'],['show interfaces trunk','Allowed/native VLANs and uplinks','VLANهای Allowed و Native و Uplink'],['show spanning-tree','Root, blocked ports and STP mode','Root، پورت مسدود و Mode پروتکل'],['show ip interface brief','SVI addresses and up/up state','IP و وضعیت up/up در SVI'],['show ip route','L3 routes and default route; limited on L2','Routeهای L3 و Default؛ خروجی محدود در L2'],['show users','Active sessions and their source addresses','Session فعال و آدرس مبدأ'],['show logging','Existing faults and security events','خطاهای موجود و رخداد امنیتی']]));
p('Back up running and startup configurations to an approved encrypted repository before changes. A local flash copy is convenient but does not protect against device loss. Do not overwrite a known-good startup configuration just to take a backup. Record VLAN/port maps, root placement, DHCP paths, static hosts, phone/AP behavior and telemetry baselines.', 'پیش از تغییر، Running و Startup Configuration را در Repository رمزنگاری‌شده مجاز Backup بگیرید. کپی Flash مفید است اما از خرابی یا از دست‌رفتن دستگاه محافظت نمی‌کند. برای Backup، Startup سالم را با Running تأییدنشده جایگزین نکنید. نقشه پورت/VLAN، محل Root، مسیر DHCP، میزبان ثابت، رفتار Phone/AP و Baseline ترافیک را ثبت کنید.');
code("copy running-config flash:pre-hardening-running.cfg\ncopy startup-config flash:pre-hardening-startup.cfg");
dependency('Confirm the filesystem name and available space; protect and retire backups because they can contain secrets. Prepare the exact inverse commands or a platform-tested configuration restore procedure; merging a backup does not necessarily remove newly added commands.', 'نام Filesystem و فضای آزاد را بررسی کنید؛ Backup می‌تواند Secret داشته باشد و باید محافظت و پس از دوره نگهداری حذف شود. فرمان معکوس یا روش Restore آزموده‌شده تهیه کنید؛ Merge کردن Backup الزاماً فرمان‌های جدید را حذف نمی‌کند.');

$identity="hostname <HOSTNAME>\nno ip domain-lookup\nip domain-name <DOMAIN.LOCAL>";
$aaa="username <ADMIN> privilege 15 secret <STRONG-PASSWORD>\naaa new-model\naaa authentication login default local\naaa authorization exec default local";
sec('baseline','2. Common Hardening Baseline: Identity and AAA','۲. تنظیمات مشترک: Identity و AAA');
figure('Cisco Secure Network Management Infographic.png','Secure switch management: AAA, SSH, ACLs and monitoring','مدیریت امن سوئیچ: AAA، SSH، ACL و مانیتورینگ');
feature(['Identify the switch and authenticate every administrator.','شناسایی سوئیچ و احراز هویت تمام مدیران.'],['Shared passwords and anonymous privileged access prevent accountability.','رمز مشترک و دسترسی ممتاز بدون هویت، پاسخ‌گویی را از بین می‌برد.'],$identity."\n".$aaa,['hostname and domain identify the device; no ip domain-lookup prevents unintended DNS lookups. AAA uses the local user database for login and exec authorization.','hostname و Domain هویت دستگاه‌اند؛ no ip domain-lookup از DNS Lookup ناخواسته جلوگیری می‌کند. AAA احراز هویت Login و مجوز Exec را از دیتابیس محلی می‌گیرد.'],['Open a second SSH session and confirm the expected privilege with show privilege; inspect show running-config and show users.','SSH دوم باز کنید؛ با show privilege سطح دسترسی و با show running-config و show users تنظیمات و Session را بررسی کنید.'],['Create and test the emergency local account before enabling AAA. Enterprise environments should use TACACS+ or RADIUS with centralized policy and accounting; keep the local account in a vault and test fallback during server outage. A local method after a server group normally runs on server error/unavailability, not a deliberate authentication rejection.','پیش از فعال‌سازی AAA حساب Emergency محلی را بسازید و تست کنید. در Enterprise از TACACS+ یا RADIUS با Policy و Accounting مرکزی استفاده کنید؛ حساب محلی در Vault باقی بماند و Fallback هنگام قطعی سرور تست شود. Local بعد از Server Group معمولاً در خطا یا عدم دسترسی سرور اجرا می‌شود، نه Reject عمدی احراز هویت.']);
code("! Prefer Type 9 if supported; use instead of the generic username above\nusername <ADMIN> privilege 15 algorithm-type scrypt secret <STRONG-PASSWORD>\n! Type 8 alternative: choose one algorithm, not both\n! username <ADMIN> privilege 15 algorithm-type sha256 secret <STRONG-PASSWORD>");
dependency('Type 8 is PBKDF2-SHA-256; Type 9 uses scrypt. Never put plaintext after secret 8 or secret 9: those forms expect an encoded hash. The generic secret command may produce a weaker type on old IOS; inspect the stored type. service password-encryption Type 7 is reversible and is not a substitute.', 'Type 8 از PBKDF2-SHA-256 و Type 9 از scrypt استفاده می‌کند. بعد از secret 8 یا secret 9 متن ساده وارد نکنید؛ این Syntax نیازمند Hash آماده است. secret عمومی در IOS قدیمی ممکن است Type ضعیف‌تر تولید کند؛ Type ذخیره‌شده را بررسی کنید. Type 7 در service password-encryption برگشت‌پذیر است و جایگزین Hash امن نیست.');

$ssh="crypto key generate rsa modulus 2048\nip ssh version 2\nip ssh time-out 60\nip ssh authentication-retries 3\nip access-list standard MGMT-SSH\n permit <ADMIN-SUBNET> <WILDCARD>\n deny any log\nexit\nline vty 0 15\n login authentication default\n transport input ssh\n exec-timeout 10 0\n access-class MGMT-SSH in\nexit\nline console 0\n login authentication default\n exec-timeout 10 0\n logging synchronous\nexit";
sec('ssh','3. SSH Hardening','۳. امنیت SSH');
feature(['Permit SSHv2 administration from approved source networks only.','مدیریت SSHv2 فقط از مبدأ مجاز.'],['Telnet exposes credentials; an unrestricted VTY permits remote guessing.','Telnet رمز را افشا می‌کند و VTY بدون محدودیت امکان حدس رمز را می‌دهد.'],$ssh,['transport input ssh excludes Telnet on the covered VTY lines. The access-class checks the actual source IP seen by the switch; exec-timeout closes idle sessions. Console logging synchronous improves usability, not security.','transport input ssh روی VTYهای تحت پوشش Telnet را حذف می‌کند. access-class مبدأ واقعی مشاهده‌شده را کنترل می‌کند؛ exec-timeout نشست بی‌کار را می‌بندد. logging synchronous روی Console صرفاً خوانایی را بهتر می‌کند.'],['show ip ssh must report version 2. Test SSH from permitted and denied hosts and confirm Telnet fails; inspect all VTY ranges.','show ip ssh باید نسخه ۲ نشان دهد. SSH را از میزبان مجاز و غیرمجاز تست کنید؛ Telnet باید رد شود و همه Rangeهای VTY بررسی شوند.'],['Keep the current session and console open while testing a fresh login. Add jump-host/NAT sources before applying the ACL. Do not regenerate working RSA keys without scheduling host-key changes. A 2048-bit key is the example minimum; use the approved supported key size and SSH algorithms.','تا زمان تست Login جدید، Session فعلی و Console باز بماند. مبدأ Jump Host یا NAT را پیش از اعمال ACL مجاز کنید. کلید RSA موجود را بدون برنامه تغییر Host Key دوباره نسازید. ۲۰۴۸ بیت حداقل نمونه است؛ اندازه کلید و الگوریتم SSH مصوب و پشتیبانی‌شده را انتخاب کنید.']);
dependency('Some switches expose only VTY 0–4, others more than 15. Apply policy to every existing VTY. RSA generation and SSH cipher/MAC controls vary by crypto image and release; modern policy may need additional algorithm restrictions.', 'بعضی سوئیچ‌ها فقط VTY 0 تا 4 و بعضی بیش از 15 دارند؛ Policy باید همه VTYهای موجود را پوشش دهد. ساخت RSA و کنترل Cipher/MAC به Crypto Image و نسخه وابسته است؛ Policy جدید ممکن است محدودیت الگوریتم بیشتری بخواهد.');

$services="no ip http server\nno ip http secure-server\nno service pad\nno ip source-route";
sec('services','4. Disable Unnecessary Services','۴. غیرفعال‌سازی سرویس غیرضروری');
feature(['Reduce unused management and packet-processing exposure.','کاهش سطح حمله سرویس مدیریت و پردازش غیرضروری.'],['Unused HTTP interfaces and legacy functions add attack surface.','HTTP بلااستفاده و قابلیت Legacy سطح حمله اضافه می‌کنند.'],$services,['The first two commands disable HTTP and HTTPS management servers. no service pad disables legacy X.25 PAD; no ip source-route rejects IPv4 source-route processing.','دو فرمان اول HTTP و HTTPS مدیریتی را غیرفعال می‌کنند. no service pad قابلیت قدیمی X.25 PAD را می‌بندد؛ no ip source-route پردازش Source Routing در IPv4 را منع می‌کند.'],['Inspect show running-config and, if supported, show ip http server status. Verify the switch no longer accepts web-management connections.','show running-config و در صورت پشتیبانی show ip http server status را بررسی کنید؛ اتصال وب مدیریتی باید بسته باشد.'],['Disabling HTTPS can interrupt WebUI and HTTP-based automation such as RESTCONF. Inventory those dependencies first. Missing no commands in show running-config can indicate defaults; verify operational state.','بستن HTTPS می‌تواند WebUI و Automation وابسته به HTTP مانند RESTCONF را قطع کند؛ ابتدا وابستگی‌ها را بررسی کنید. نبودن فرمان no در Running ممکن است به معنی Default باشد؛ وضعیت عملیاتی را تست کنید.']);
dependency('PAD is a legacy/obsolete feature, unavailable or deprecated in some Catalyst images. Source-route and HTTP commands also require matching platform documentation; do not assume every old IOS knob exists in current IOS XE.', 'PAD قابلیت منسوخ عملیاتی است و در بعضی Imageهای Catalyst موجود نیست یا Deprecated است. فرمان Source Route و HTTP نیز باید با مستندات پلتفرم تطبیق داده شود؛ همه تنظیمات قدیمی IOS در IOS XE جدید وجود ندارند.');

sec('l2','5. Layer 2 Switch Hardening','۵. هاردنینگ سوئیچ لایه ۲');
figure('Layer 2 Switch Security Infographic.png','Layer 2 security controls for Cisco Catalyst access switches','کنترل‌های امنیت لایهٔ ۲ برای سوئیچ‌های Access در Cisco Catalyst');
feature(['Provide a management endpoint without inter-VLAN routing on the access switch.','ایجاد Endpoint مدیریتی بدون Routing بین VLANها در Access.'],['Accidental routing changes the security boundary; an unreachable SVI prevents management.','Routing ناخواسته مرز امنیت را تغییر می‌دهد و SVI قطع، مدیریت را متوقف می‌کند.'],"vlan <MGMT-VLAN>\n name MANAGEMENT\nexit\ninterface Vlan<MGMT-VLAN>\n ip address <MGMT-IP> <MASK>\n no shutdown\nexit\nno ip routing\nip default-gateway <GATEWAY>",['The SVI terminates management traffic. ip default-gateway serves locally originated off-subnet traffic while routing is disabled.','SVI ترافیک مدیریتی دستگاه را خاتمه می‌دهد. در حالت Routing غیرفعال، ip default-gateway مسیر ترافیک تولیدشده دستگاه به خارج Subnet است.'],['show ip interface brief should show management up/up; test same-subnet and routed administrator access.','SVI مدیریت در show ip interface brief باید up/up باشد؛ دسترسی مدیر داخل و خارج Subnet را تست کنید.'],['The VLAN must exist and normally have an active forwarding member/trunk. no ip routing belongs only to the L2 role. The complete standalone access template is in section 22.','VLAN باید وجود داشته و معمولاً Member یا Trunk فعال در حالت Forwarding داشته باشد. no ip routing فقط متعلق به نقش L2 است. قالب کامل مستقل Access در بخش ۲۲ قرار دارد.']);

$snoop="ip dhcp snooping\nip dhcp snooping vlan <USER-VLANS>\nno ip dhcp snooping information option\ninterface <UPLINK>\n ip dhcp snooping trust\nexit\ninterface range <ACCESS-PORTS>\n ip dhcp snooping limit rate <RATE>\nexit";
sec('dhcp','6. DHCP Snooping','۶. DHCP Snooping');
feature(['Accept DHCP server messages only across the approved boundary.','پذیرش پیام DHCP Server فقط از مرز مجاز.'],['A rogue server can assign a malicious gateway or DNS server.','DHCP Rogue می‌تواند Gateway یا DNS مخرب تحویل دهد.'],$snoop,['Untrusted endpoint ports cannot originate accepted server replies. Snooping builds IP/MAC/VLAN/port lease bindings for downstream controls. trust applies to ingress, not a port label.','پاسخ Server از پورت کاربر Untrusted پذیرفته نمی‌شود. Snooping نگاشت Lease شامل IP/MAC/VLAN/Port را برای کنترل‌های بعدی می‌سازد. trust به ترافیک ورودی مربوط است، نه نام پورت.'],['show ip dhcp snooping: correct VLANs and only approved trusted interfaces; show ip dhcp snooping binding: leases for DHCP endpoints after renew.','در show ip dhcp snooping فقط VLAN و پورت Trusted مجاز دیده شود؛ پس از Renew، جدول show ip dhcp snooping binding باید Lease کاربران را داشته باشد.'],['Never trust an endpoint port merely to fix DHCP. Choose rate from boot storms, phone+PC and downstream fan-out; a low limit can err-disable a port. Disabling Option 82 is a compatibility choice here, not a universal security requirement; preserve it where relay/server policy relies on it.','برای رفع DHCP، پورت کاربر را Trusted نکنید. Rate را با Boot Storm، Phone+PC و تعداد میزبان پایین‌دست تعیین کنید؛ حد پایین می‌تواند پورت را err-disable کند. حذف Option 82 در این مثال انتخاب سازگاری است، نه الزام عمومی؛ اگر Policy سرور/Relay به آن وابسته است حفظ شود.']);
dependency('Validate rate units and EtherChannel behavior. Plan supported DHCP snooping database persistence and reload/stack failover recovery before DAI/IPSG; dynamic bindings may be lost on reload. Verify database agent status and test renew before enforcing dependent filters.', 'واحد Rate و رفتار EtherChannel را بررسی کنید. پیش از DAI/IPSG برای ذخیره پایدار دیتابیس و بازیابی Reload یا Stack Failover برنامه داشته باشید؛ Binding پویا ممکن است پس از Reload از دست برود. وضعیت Database Agent و Renew را پیش از اعمال فیلتر وابسته تست کنید.');

sec('dai','7. Dynamic ARP Inspection','۷. Dynamic ARP Inspection');
feature(['Validate ARP on user-facing VLANs.','اعتبارسنجی ARP در VLAN کاربر.'],['ARP spoofing redirects or intercepts local traffic.','ARP Spoofing ترافیک محلی را منحرف یا شنود می‌کند.'],"ip arp inspection vlan <USER-VLANS>\ninterface <UPLINK>\n ip arp inspection trust\nexit",['Untrusted ingress ARP is checked against DHCP snooping bindings or configured ARP ACLs. Trusted ingress bypasses inspection; select that boundary separately from DHCP trust.','ARP ورودی Untrusted با Binding DHCP یا ARP ACL بررسی می‌شود. ورودی Trusted از Inspection عبور می‌کند؛ این مرز را مستقل از DHCP Trust انتخاب کنید.'],['show ip arp inspection and show ip arp inspection interfaces: enabled VLANs, trust and rates; test ARP and inspect drop counters.','show ip arp inspection و show ip arp inspection interfaces باید VLAN فعال، Trust و Rate صحیح نشان دهند؛ ARP و شمارنده Drop را تست کنید.'],['Static hosts require explicit allowances before enabling DAI. Do not trust every inter-switch link: a downstream switch may carry attackers. ARP bursts and aggregated links require measured limits and error-disable monitoring.','میزبان Static پیش از فعال‌سازی DAI به مجوز صریح نیاز دارد. هر لینک بین سوئیچی را Trusted نکنید؛ سوئیچ پایین‌دست ممکن است مهاجم داشته باشد. Burst ARP و لینک تجمیعی نیازمند Rate اندازه‌گیری‌شده و مانیتور err-disable است.']);
code("arp access-list STATIC-HOSTS\n permit ip host 10.10.10.50 mac host 0011.2233.4455\nexit\nip arp inspection filter STATIC-HOSTS vlan 10");
dependency('The ARP ACL above is illustrative: replace the IP/MAC with inventory. Without the static keyword, unmatched ARP can fall back to DHCP bindings; with static, unmatched hosts are denied rather than checked against bindings. Explicit deny entries also override bindings. Test mixed static/DHCP populations.', 'ARP ACL نمونه است؛ IP/MAC را از Inventory جایگزین کنید. بدون کلیدواژه static، ARP تطبیق‌نیافته می‌تواند با Binding DHCP بررسی شود؛ با static، میزبان تطبیق‌نیافته به جای بررسی Binding رد می‌شود. Deny صریح بر Binding نیز تقدم دارد. ترکیب Static و DHCP را تست کنید.');

sec('ipsg','8. IP Source Guard','۸. IP Source Guard');
feature(['Bind endpoint IPv4 source addresses to access ports.','محدودسازی IP مبدأ کاربر به پورت مجاز.'],['Source spoofing bypasses address-based policy.','جعل IP مبدأ Policy مبتنی بر آدرس را دور می‌زند.'],"interface range <ACCESS-PORTS>\n ip verify source\nexit",['This IP-only example programs source filters from DHCP snooping or manual bindings on suitable Layer 2 switchports; it is not a routed-SVI ACL.','این نمونه IP-only روی Switchport لایه ۲ مناسب از Binding DHCP یا نگاشت دستی فیلتر مبدأ می‌سازد؛ ACL روی SVI Routed نیست.'],['show ip verify source and show ip dhcp snooping binding: the expected IP/VLAN/interface appears; verify legitimate traffic and controlled spoofed traffic in a lab.','show ip verify source و show ip dhcp snooping binding باید IP/VLAN/Port صحیح نشان دهند؛ ترافیک مجاز و جعل کنترل‌شده را در Lab تست کنید.'],['Do not enable this block on static servers, printers, AP uplinks or infrastructure ports without a supported binding design. An empty table can block legitimate IP traffic.','این بلوک را بدون طراحی Binding پشتیبانی‌شده روی Server، Printer، AP Uplink یا پورت زیرساخت Static فعال نکنید. جدول خالی می‌تواند IP مجاز را مسدود کند.']);
code('ip source binding <STATIC-MAC> vlan <STATIC-VLAN> <STATIC-IP> interface <STATIC-PORT>');
dependency('Static binding and device-tracking-based IPSG are platform-specific alternatives; static ARP allowances alone do not automatically provide an IPSG binding. Check TCAM capacity and voice/data behavior.', 'Binding دستی و IPSG مبتنی بر Device Tracking گزینه‌های وابسته به پلتفرم‌اند؛ ARP ACL به‌تنهایی Binding برای IPSG ایجاد نمی‌کند. ظرفیت TCAM و رفتار Voice/Data بررسی شود.');

$stp="spanning-tree mode rapid-pvst\nspanning-tree portfast bpduguard default\ninterface range <ACCESS-PORTS>\n spanning-tree portfast\n spanning-tree bpduguard enable\nexit\n! Only on a reviewed downstream boundary\n! interface <ROOT-GUARD-PORT>\n!  spanning-tree guard root";
sec('stp','9. STP Hardening','۹. هاردنینگ STP');
feature(['Preserve the intended root and block accidental edge switches.','حفظ Root طراحی‌شده و جلوگیری از سوئیچ ناخواسته در Edge.'],['Unexpected BPDUs or missing BPDUs can create topology changes and loops.','BPDU غیرمنتظره یا قطع BPDU می‌تواند تغییر توپولوژی یا Loop ایجاد کند.'],$stp,['Global BPDU Guard protects operational PortFast ports; explicit interface BPDU Guard rejects any received BPDU on that edge port. Root Guard blocks superior BPDUs on reviewed designated boundaries.','BPDU Guard سراسری پورت PortFast عملیاتی را حفاظت می‌کند؛ تنظیم صریح اینترفیس هر BPDU ورودی آن Edge را رد می‌کند. Root Guard روی مرز Designated بررسی‌شده Superior BPDU را مسدود می‌کند.'],['show spanning-tree and show spanning-tree inconsistentports: expected root and no unexplained inconsistent ports; inspect err-disabled interfaces for BPDU Guard.','show spanning-tree و show spanning-tree inconsistentports باید Root مورد انتظار و نبود Inconsistent غیرعادی را نشان دهند؛ err-disabled ناشی از BPDU Guard را بررسی کنید.'],['Changing STP mode is a topology change; preserve MST where designed. Never enable PortFast/BPDU Guard blindly on switch uplinks. Place root priorities deliberately on the core/distribution. Root Guard is not an all-trunk default.','تغییر STP Mode تغییر توپولوژی است؛ در طراحی MST آن را حفظ کنید. PortFast/BPDU Guard را کورکورانه روی Uplink سوئیچ فعال نکنید. Priority Root در Core/Distribution آگاهانه تعیین شود. Root Guard تنظیم پیش‌فرض همه Trunkها نیست.']);
table([['Guard','محافظ'],['Placement / trigger','محل / محرک'],['Result / recovery','نتیجه / بازیابی']],[[['BPDU Guard','BPDU Guard'],['Endpoint edge; any BPDU','Edge کاربر؛ هر BPDU'],['Err-disable; investigate then recover','Err-disable؛ بررسی علت و بازیابی']], [['Root Guard','Root Guard'],['Designated downstream boundary; superior BPDU','مرز پایین‌دست Designated؛ BPDU برتر'],['Root-inconsistent; automatic recovery after superior BPDUs stop','Root-inconsistent؛ بازیابی خودکار پس از توقف BPDU برتر']], [['Loop Guard','Loop Guard'],['Non-edge root/alternate ports; expected BPDUs disappear','Root/Alternate غیر Edge؛ توقف BPDU مورد انتظار'],['Loop-inconsistent; recovery when BPDUs resume','Loop-inconsistent؛ بازیابی با بازگشت BPDU']]]);
dependency('Loop Guard uses spanning-tree guard loop on selected ports; Root Guard and Loop Guard must not be combined on the same interface. PortFast edge syntax varies by release; match the existing STP design.', 'Loop Guard با spanning-tree guard loop روی پورت منتخب اعمال می‌شود؛ Root Guard و Loop Guard را روی یک اینترفیس ترکیب نکنید. Syntax PortFast edge به نسخه وابسته است؛ طراحی موجود را رعایت کنید.');

$portsecurity="interface range <ACCESS-PORTS>\n switchport mode access\n switchport port-security\n switchport port-security maximum 3\n switchport port-security violation restrict\n switchport port-security mac-address sticky\nexit";
sec('port-security','10. Port Security','۱۰. Port Security');
feature(['Limit learned endpoint MAC identities on selected access ports.','محدودسازی MACهای یادگرفته‌شده روی Access منتخب.'],['Uncontrolled MAC learning permits unauthorized attachment and table pressure.','یادگیری نامحدود MAC اتصال غیرمجاز و فشار جدول ایجاد می‌کند.'],$portsecurity,['Sticky MACs are learned into running configuration. They persist after reboot only when saved. This limits attachment, but MAC addresses can be spoofed; it is not user authentication.','Sticky MAC در Running ثبت می‌شود و فقط با Save پس از Reboot باقی می‌ماند. این کنترل اتصال را محدود می‌کند اما MAC قابل جعل است و احراز هویت کاربر نیست.'],['show port-security and show port-security interface <INTERFACE>: expected maximum, secure MACs and violation count.','show port-security و show port-security interface <INTERFACE> باید Maximum، MAC مجاز و شمارنده Violation صحیح داشته باشند.'],['Maximum 3 is an example, not a phone policy. Count phone, attached PC and voice/data VLAN learning; test boot and replacement. APs, hypervisors, downstream switches, EtherChannels and 802.1X/MAB designs require separate support/design review. Remove stale sticky entries through a controlled replacement process.','Maximum برابر ۳ فقط مثال است. MAC تلفن، PC متصل و یادگیری Voice/Data را شمارش و Boot و تعویض را تست کنید. AP، Hypervisor، سوئیچ پایین‌دست، EtherChannel و طراحی 802.1X/MAB نیازمند بررسی جداگانه است. Sticky قدیمی را در فرایند تعویض کنترل‌شده پاک کنید.']);
table([['Mode','حالت'],['Effect','عملکرد']],[[['Protect','Protect'],['Drops violating traffic without normal violation notifications','Drop ترافیک متخلف بدون اعلان معمول Violation']], [['Restrict','Restrict'],['Drops violating traffic; increments counters and generates notifications','Drop همراه شمارنده و اعلان']], [['Shutdown','Shutdown'],['Err-disables the port; restore only after investigating','پورت را err-disable می‌کند؛ بازیابی پس از بررسی علت']]]);
dependency('Port Security support and interactions differ across Catalyst interface types, authentication modes and software releases.', 'پشتیبانی Port Security و تعامل آن با نوع پورت، حالت احراز هویت و نسخه متفاوت است.');

$storm="interface range <ACCESS-PORTS>\n storm-control broadcast level 1.00 0.50\n storm-control multicast level 2.00 1.00\n storm-control action trap\nexit";
sec('storm','11. Storm Control','۱۱. Storm Control');
feature(['Contain broadcast and multicast storms at the edge.','مهار Storm پخش همگانی و Multicast در Edge.'],['A loop or faulty endpoint can exhaust link and switch resources.','Loop یا Endpoint معیوب می‌تواند لینک و منابع سوئیچ را اشباع کند.'],$storm,['The sample uses rising/falling percentages of interface bandwidth: 1%/0.5% broadcast and 2%/1% multicast. Suppression drops the affected traffic; action trap adds notification, not trap-only monitoring.','مثال از درصد پهنای باند برای آستانه صعود/نزول استفاده می‌کند: Broadcast برابر ۱٪/۰٫۵٪ و Multicast برابر ۲٪/۱٪. Suppression ترافیک مربوط را Drop می‌کند؛ action trap اعلان اضافه می‌کند و به معنی صرفاً مانیتورینگ نیست.'],['show storm-control, counters and receiver telemetry should agree with measured traffic. Confirm the release-specific SNMP storm trap enablement and delivery.','show storm-control، شمارنده و Telemetry مقصد باید با ترافیک اندازه‌گیری‌شده سازگار باشند. فعال‌سازی و تحویل SNMP Trap مخصوص Storm را برای نسخه بررسی کنید.'],['Fixed thresholds are not suitable for every port. Baseline multicast video, discovery, backups and phone boots; start with a small pilot. Percentage on a 10G link permits much more traffic than on 1G.','آستانه ثابت برای همه پورت‌ها مناسب نیست. Multicast Video، Discovery، Backup و Boot تلفن را Baseline بگیرید و Pilot کوچک اجرا کنید. درصد یکسان روی 10G ترافیک بسیار بیشتری از 1G اجازه می‌دهد.']);
dependency('Supported traffic types, pps/bps units and EtherChannel measurement vary by platform. Verify storm-control action and trap behavior before relying on alerts.', 'نوع ترافیک پشتیبانی‌شده، واحد pps/bps و اندازه‌گیری EtherChannel به پلتفرم وابسته است؛ رفتار Action و Trap پیش از اتکا به هشدار تست شود.');

$trunk="interface <UPLINK>\n switchport mode trunk\n switchport trunk native vlan <NATIVE-VLAN>\n switchport trunk allowed vlan <VLAN-LIST>\n switchport nonegotiate\nexit";
sec('trunk','12. Trunk Hardening','۱۲. هاردنینگ Trunk');
feature(['Make VLAN transport explicit between switches.','تعریف صریح VLAN مجاز بین سوئیچ‌ها.'],['DTP negotiation, excess allowed VLANs and native mismatches expand exposure.','DTP، VLAN اضافی و Native Mismatch سطح دسترسی را افزایش می‌دهند.'],$trunk,['Static trunk plus nonegotiate suppresses DTP. The allowed list limits data VLAN transport; match the native VLAN on both ends.','Trunk ثابت با nonegotiate مذاکره DTP را متوقف می‌کند. Allowed List انتقال Data VLAN را محدود می‌کند و Native باید دو سمت یکسان باشد.'],['show interfaces trunk: static trunk, matching native and only intended allowed/active/forwarding VLANs.','show interfaces trunk باید Trunk ثابت، Native یکسان و VLANهای Allowed/Active/Forwarding مورد انتظار را نشان دهد.'],['Use an unused native VLAN such as 998 with no SVI or endpoint ports, separate from management and parking VLAN 999. Exclude VLAN 1 and unnecessary VLANs from user transport, and do not use VLAN 1 for management. Removing VLAN 1 from an allowed list does not necessarily stop all control protocols. Audit the trunk peer before changing the list because the command replaces the existing list.','از Native بلااستفاده مانند 998 بدون SVI یا Endpoint، جدا از مدیریت و Parking 999 استفاده کنید. VLAN 1 و VLAN اضافی از انتقال Data حذف شوند و مدیریت در VLAN 1 نباشد. حذف VLAN 1 از Allowed الزاماً همه Control Protocolها را متوقف نمی‌کند. پیش از تغییر، Peer را بررسی کنید چون فرمان Allowed List لیست موجود را جایگزین می‌کند.']);
dependency('Native VLAN tagging, DTP and trunk encapsulation options vary. Fixed 802.1Q Catalyst platforms do not need switchport trunk encapsulation dot1q. Native tagging changes require matching peer behavior and a planned migration.', 'Native Tagging، DTP و گزینه Encapsulation وابسته‌اند. Catalyst با 802.1Q ثابت به switchport trunk encapsulation dot1q نیاز ندارد. تغییر Native Tagging باید با Peer و برنامه مهاجرت سازگار باشد.');

sec('unused','13. Unused Ports','۱۳. پورت بلااستفاده');
feature(['Park and administratively disable unused switchports.','انتقال پورت بلااستفاده به VLAN Parking و خاموشی اداری.'],['An unused live port permits unauthorized attachment.','پورت روشن بلااستفاده امکان اتصال غیرمجاز می‌دهد.'],"vlan 999\n name UNUSED-PORTS\nexit\ninterface range <UNUSED-PORTS>\n switchport mode access\n switchport access vlan 999\n shutdown\nexit",['VLAN 999 has no SVI or routed access; shutdown is the actual port-disabling control.','VLAN 999 بدون SVI و دسترسی Routed است؛ shutdown کنترل واقعی قطع پورت است.'],['show interfaces status: unused ports disabled; show vlan brief: parking membership matches inventory.','در show interfaces status پورت Disabled و در show vlan brief عضویت Parking مطابق Inventory باشد.'],['Do not include uplinks, stack links, APs, phones or reserve infrastructure interfaces in this range. Remove parking VLAN from trunk allowed lists.','Uplink، Stack Link، AP، Phone یا پورت رزرو زیرساخت در این Range نباشد. VLAN Parking را در Trunk Allow نکنید.']);

sec('l3','14. Layer 3 Switch Hardening','۱۴. هاردنینگ سوئیچ لایه ۳');
figure('Cisco Layer 2 vs Layer 3 Hardening Guide.png','Comparing Layer 2 access security and Layer 3 routing hardening','مقایسهٔ امنیت Access لایهٔ ۲ و هاردنینگ Routing لایهٔ ۳');
feature(['Route deliberately and separate user and management policy.','Routing آگاهانه و جداسازی Policy کاربر و مدیریت.'],['Incorrect routing or SVI behavior bypasses segmentation and interrupts services.','Routing یا رفتار SVI نادرست Segmentation را دور می‌زند و سرویس را قطع می‌کند.'],"ip routing\ninterface Vlan<MGMT-VLAN>\n ip address <MGMT-IP> <MASK>\n no shutdown\nexit\ninterface Vlan10\n description USERS-GATEWAY\n ip address 10.10.10.1 255.255.255.0\n no ip redirects\n no ip proxy-arp\n no shutdown\nexit",['ip routing enables inter-VLAN forwarding. no ip redirects stops sending ICMP redirects; no ip proxy-arp stops answering ARP on behalf of other addresses on that SVI. Neither replaces an ACL.','ip routing انتقال بین VLANها را فعال می‌کند. no ip redirects ارسال ICMP Redirect و no ip proxy-arp پاسخ ARP به نمایندگی آدرس دیگر در آن SVI را می‌بندد. هیچ‌کدام جای ACL نیستند.'],['show ip route should show connected SVIs and a valid default or intended dynamic routes; inspect show ip interface Vlan10 for redirects/proxy ARP state.','show ip route باید SVIهای Connected و Default یا Dynamic Route مورد انتظار را نشان دهد؛ وضعیت Redirect/Proxy ARP در show ip interface Vlan10 بررسی شود.'],['Check dependencies on redirects and proxy ARP before disabling them. Use an explicit route or a designed dynamic protocol, not ip default-gateway, when routing is active. The standalone section 22 example uses a routed /30 uplink and static default route.','پیش از غیرفعال‌سازی وابستگی Redirect و Proxy ARP را بررسی کنید. در Routing فعال از Route صریح یا Dynamic Protocol طراحی‌شده استفاده کنید، نه ip default-gateway. نمونه مستقل بخش ۲۲ یک Uplink Routed با /30 و Static Default Route دارد.']);
dependency('Routing license, SVI count and routed-port support differ between Catalyst models; a Layer 2-only image cannot implement this template.', 'License Routing، تعداد SVI و پشتیبانی Routed Port بین مدل‌ها متفاوت است؛ Image صرفاً لایه ۲ نمی‌تواند این Template را اجرا کند.');

$useracl="ip access-list extended USERS-TO-MGMT\n remark Approved shared infrastructure exceptions\n permit udp 10.10.10.0 0.0.0.255 host 10.99.99.10 eq domain\n permit tcp 10.10.10.0 0.0.0.255 host 10.99.99.10 eq domain\n permit udp 10.10.10.0 0.0.0.255 host 10.99.99.20 eq ntp\n deny ip 10.10.10.0 0.0.0.255 10.99.99.0 0.0.0.255\n permit ip any any\nexit\ninterface Vlan10\n ip access-group USERS-TO-MGMT in\nexit";
sec('svi-acl','15. Layer 3 ACL Hardening','۱۵. هاردنینگ ACL لایه ۳');
feature(['Block users from the management subnet while preserving approved dependencies.','مسدودسازی دسترسی کاربر به مدیریت همراه حفظ وابستگی مجاز.'],['User-originated lateral access can compromise switches and monitoring systems.','حرکت جانبی از VLAN کاربر می‌تواند سوئیچ و مانیتورینگ را آلوده کند.'],$useracl,['Ingress on Vlan10 filters packets arriving from Users 10.10.10.0/24 toward routed destinations. DNS 10.99.99.10 and NTP 10.99.99.20 are explicit illustrative exceptions; the final permit preserves other IPv4 traffic and prevents an accidental implicit-deny outage.','ACL ورودی Vlan10 ترافیک کاربران 10.10.10.0/24 به مقصد Routed را کنترل می‌کند. DNS برابر 10.99.99.10 و NTP برابر 10.99.99.20 استثناهای نمونه‌اند. Permit نهایی ترافیک دیگر IPv4 را حفظ و از قطعی ناشی از Implicit Deny جلوگیری می‌کند.'],['show access-lists and show ip interface Vlan10 must show placement and matching counters. Test DNS over UDP/TCP, NTP, normal business traffic, denied management SSH and permitted admin SSH from a separate subnet.','show access-lists و show ip interface Vlan10 باید محل اعمال و Counter تطبیق نشان دهند. DNS روی UDP/TCP، NTP، ترافیک کاری، SSH مدیریتی ممنوع کاربر و SSH مجاز مدیر از Subnet جدا تست شود.'],['Inventory DHCP relay/server, directory, monitoring probes and application flows before deployment; add narrow exceptions above the deny or place shared services outside management. This ACL is stateless: it also blocks user replies to management-initiated sessions unless explicitly permitted. It does not filter same-VLAN bridging, IPv6, or substitute for VTY/SNMP ACLs. Do not apply it to the management SVI blindly.','پیش از استقرار DHCP Relay/Server، Directory، Probe مانیتورینگ و Application را بررسی و استثنای محدود قبل از Deny اضافه کنید یا Shared Service را خارج مدیریت قرار دهید. ACL بدون State است؛ پاسخ کاربر به Session آغازشده از مدیریت نیز بدون Permit صریح مسدود می‌شود. Bridging همان VLAN و IPv6 را فیلتر نمی‌کند و جای ACL مربوط به VTY/SNMP نیست. آن را کورکورانه روی SVI مدیریت اعمال نکنید.']);
note('Lockout risk: apply from console or a separate approved administrator path. Test ACL order and actual source addresses, retain the previous policy, and use an exact rollback such as removing the new ip access-group before restoring the previous ACL.', 'خطر Lockout: از Console یا مسیر جدا و مجاز مدیر اعمال کنید. ترتیب ACL و آدرس مبدأ واقعی تست شود؛ Policy قبلی حفظ و Rollback دقیق مانند حذف ip access-group جدید و بازیابی ACL قبلی آماده باشد.');

sec('routing','16. Routing Protocol Security — OSPF','۱۶. امنیت پروتکل Routing — OSPF');
feature(['Form routing adjacencies only on intended transit interfaces.','تشکیل Neighbor فقط روی Transit مجاز.'],['An unintended neighbor can inject routes or disturb convergence.','Neighbor ناخواسته می‌تواند Route تزریق یا Convergence را مختل کند.'],"router ospf <PROCESS-ID>\n passive-interface default\n no passive-interface <OSPF-TRANSIT>\nexit",['Passive interfaces do not send OSPF hellos or form neighbors; advertise only reviewed prefixes using the existing interface/area design. Configure supported authentication consistently at both ends and restrict OSPF protocol 89 at appropriate routed boundaries.','Passive Interface پیام Hello ارسال نمی‌کند و Neighbor نمی‌سازد؛ فقط Prefix بررسی‌شده با طراحی موجود Interface/Area اعلان شود. Authentication پشتیبانی‌شده دو سمت یکسان تنظیم و پروتکل 89 در مرز Routed مناسب محدود شود.'],['show ip ospf neighbor: only approved peers; show ip ospf interface and show ip protocols: correct passive interfaces and authentication; show ip route ospf: intended routes.','show ip ospf neighbor فقط Peer مجاز؛ show ip ospf interface و show ip protocols وضعیت Passive و Authentication صحیح؛ show ip route ospf مسیر مورد انتظار را نشان دهد.'],['Apply only when dynamic routing is already part of the design. Prefer supported cryptographic authentication and coordinated key rollover. Route filtering must match OSPF behavior: an inbound distribute-list affects local route installation and does not generally suppress LSA flooding. Use supported ABR/ASBR policies for the appropriate LSA type.','فقط وقتی Dynamic Routing بخشی از طراحی است اعمال شود. Authentication رمزنگاری‌شده پشتیبانی‌شده با Key Rollover هماهنگ انتخاب کنید. Route Filtering باید با OSPF سازگار باشد؛ distribute-list ورودی بر نصب Route محلی اثر می‌گذارد و معمولاً LSA Flooding را متوقف نمی‌کند. Policy پشتیبانی‌شده ABR/ASBR برای نوع LSA مناسب استفاده شود.']);
dependency('OSPFv2 and OSPFv3 authentication syntax, SHA/HMAC support and licenses vary. Do not copy an OSPFv3 authentication trailer example into OSPFv2. No universal authentication stanza is included in the static-routing final template.', 'Syntax احراز هویت OSPFv2 و OSPFv3، پشتیبانی SHA/HMAC و License متفاوت است. مثال Authentication Trailer پروتکل OSPFv3 را در OSPFv2 کپی نکنید. در Template نهایی Static Routing بلوک Authentication عمومی قرار نگرفته است.');
p('Control-plane protection: review the platform’s existing system CoPP/CPP policy with show policy-map control-plane where supported. Baseline CPU, punt drops and protocol counters before adjusting policing; preserve STP, DHCP, ARP, routing and management requirements. Do not replace a Catalyst system policy with a generic policy from another platform.', 'حفاظت Control Plane: Policy فعلی CoPP/CPP سیستم را در صورت پشتیبانی با show policy-map control-plane بررسی کنید. پیش از تغییر Policing، CPU، Punt Drop و Counter پروتکل را Baseline بگیرید؛ نیاز STP، DHCP، ARP، Routing و مدیریت حفظ شود. Policy سیستم Catalyst را با Policy عمومی پلتفرم دیگر جایگزین نکنید.');

$ntp="clock timezone <TZ-NAME> <OFFSET>\nntp source Vlan<MGMT-VLAN>\nntp server <NTP-IP> prefer";
sec('ntp','17. NTP Hardening','۱۷. امنیت NTP');
feature(['Keep reliable timestamps from approved time servers.','حفظ Timestamp معتبر از Time Server مجاز.'],['Incorrect time breaks event correlation and authentication troubleshooting.','زمان نادرست Correlation رخداد و عیب‌یابی احراز هویت را مختل می‌کند.'],$ntp,['ntp source fixes the source interface. prefer favors a configured server among acceptable sources; it does not authenticate it. Timezone changes display, not NTP UTC synchronization.','ntp source اینترفیس مبدأ را تعیین می‌کند. prefer سرور را میان منابع قابل‌قبول ترجیح می‌دهد و احراز هویت نیست. Timezone نمایش زمان را تغییر می‌دهد، نه همگام‌سازی UTC در NTP.'],['show clock and show ntp associations: correct time and a selected synchronized peer; also inspect show ntp status where supported.','show clock و show ntp associations باید زمان صحیح و Peer منتخب همگام نشان دهند؛ در صورت پشتیبانی show ntp status نیز بررسی شود.'],['Provide redundant approved sources and restrict NTP exposure through supported NTP ACLs and upstream policy. For Iran, a display example is clock timezone IRST 3 30. Replace OFFSET with hours and optional minutes.','منابع مجاز Redundant و محدودیت NTP با ACL پشتیبانی‌شده و Policy بالادست فراهم کنید. مثال نمایش ایران clock timezone IRST 3 30 است؛ OFFSET را با ساعت و در صورت نیاز دقیقه جایگزین کنید.']);
code("! Optional legacy symmetric authentication; server must use the same key\nntp authenticate\nntp authentication-key <KEY-ID> md5 <NTP-SHARED-KEY>\nntp trusted-key <KEY-ID>\nntp server <NTP-IP> key <KEY-ID> prefer");
dependency('The MD5 syntax above is a legacy compatibility example, not a claim of modern cryptographic strength. Use stronger supported authentication if both ends implement it; protect keys and test matching server behavior. Authentication algorithms, access-group syntax and VRF support vary.', 'Syntax MD5 مثال سازگاری Legacy است و ادعای قدرت رمزنگاری مدرن ندارد. اگر دو سمت پشتیبانی می‌کنند الگوریتم قوی‌تر انتخاب کنید؛ کلید محافظت و سازگاری سرور تست شود. الگوریتم، access-group و VRF وابسته به نسخه است.');

$syslog="service timestamps log datetime msec localtime show-timezone\nlogging host <SYSLOG-IP>\nlogging source-interface Vlan<MGMT-VLAN>\nlogging trap warnings\nlogging buffered 16384 informational";
sec('syslog','18. Syslog','۱۸. Syslog');
feature(['Export actionable events with stable identity and timestamps.','ارسال رخداد قابل اقدام با هویت و زمان ثابت.'],['Without centralized logs, security incidents and port faults are missed.','بدون Log مرکزی رخداد امنیتی و خطای پورت دیده نمی‌شود.'],$syslog,['warnings exports severity 0–4; informational in the 16384-byte ring buffer keeps 0–6 locally. Lower severity numbers are more urgent. The source SVI must be reachable.','warnings سطح ۰ تا ۴ را Export و informational سطح ۰ تا ۶ را در Ring Buffer محلی ۱۶۳۸۴ بایتی نگهداری می‌کند. عدد پایین‌تر فوری‌تر است؛ SVI مبدأ باید قابل دسترسی باشد.'],['show logging and collector search: expected source, timestamps and a known test event; watch dropped messages and buffer rollover.','show logging و جست‌وجو در Collector باید مبدأ، Timestamp و رخداد تست مشخص را نشان دهند؛ Drop و چرخش Buffer بررسی شود.'],['Warning-only remote logging can omit severity-5 login, link or configuration events. Use notifications or informational centrally when those are required, with capacity and retention planning. Default UDP syslog is not encrypted or delivery-guaranteed; select supported secure transport when required. Avoid continuous debugging and high-volume ACL logging.','ارسال فقط Warning می‌تواند Login، Link یا تغییر تنظیمات Severity 5 را حذف کند. در صورت نیاز سطح notifications یا informational مرکزی با برنامه Capacity و Retention انتخاب کنید. Syslog پیش‌فرض UDP رمزنگاری و تضمین تحویل ندارد؛ در صورت الزام از Transport امن پشتیبانی‌شده استفاده کنید. Debug دائم و ACL Log پرتعداد مناسب نیست.']);

$snmp="ip access-list standard SNMP-ACL\n permit host <MONITORING-IP>\n deny any log\nexit\nsnmp-server view NMS-READ iso included\nsnmp-server group NMS-GROUP v3 priv read NMS-READ access SNMP-ACL\nsnmp-server user <SNMP-USER> NMS-GROUP v3 auth sha <SNMP-AUTH-PASSWORD> priv aes 128 <SNMP-PRIV-PASSWORD>";
sec('snmp','19. SNMP — AuthPriv First','۱۹. SNMP با اولویت AuthPriv');
feature(['Provide authenticated, encrypted and source-restricted read-only monitoring.','مانیتورینگ فقط خواندنی با احراز هویت، رمزنگاری و مبدأ محدود.'],['Communities and unauthenticated SNMP expose data and credentials.','Community و SNMP بدون احراز هویت، داده و Credential را افشا می‌کند.'],$snmp,['v3 priv requires authentication and encryption; the group has a read view and no write view. SNMP-ACL restricts polling sources. The broad iso view is a working baseline; narrow it to required OIDs after testing.','v3 priv احراز هویت و رمزنگاری الزام می‌کند؛ Group دارای Read View و بدون Write View است. SNMP-ACL مبدأ Poll را محدود می‌کند. View گسترده iso Baseline قابل کار است؛ پس از تست آن را به OID لازم محدود کنید.'],['show snmp, show snmp group and show snmp user; poll from the approved NMS with authPriv and verify an unauthorized source fails. SNMPv3 user secrets may not appear in running-config.','show snmp، show snmp group و show snmp user را بررسی کنید؛ Poll از NMS مجاز با authPriv موفق و مبدأ غیرمجاز ناموفق باشد. Secret کاربر SNMPv3 ممکن است در Running نمایش داده نشود.'],['Use separate vault-managed auth/privacy passwords. The sha keyword in this compatibility example is SHA-1, not SHA-256; prefer SHA-2 where switch and NMS support it. Remove existing v1/v2c communities after migration. Traps require separate destination/notification enablement and must be tested; polling alone does not guarantee storm alerts.','رمز Auth و Privacy جدا و تحت Vault انتخاب شود. sha در این مثال سازگاری SHA-1 است نه SHA-256؛ اگر Switch و NMS پشتیبانی می‌کنند SHA-2 ترجیح دارد. پس از مهاجرت Community نسخه ۱/۲ حذف شود. Trap نیازمند مقصد و Enable Notification جدا و تست است؛ Poll به‌تنهایی هشدار Storm را تضمین نمی‌کند.']);
dependency('SHA-2 keywords, AES variants, SNMP ACL types, engine-ID behavior and notification syntax vary. Changing engine ID can require user recreation.', 'کلیدواژه SHA-2، گونه AES، نوع ACL، رفتار Engine ID و Syntax Notification متفاوت است؛ تغییر Engine ID ممکن است ساخت مجدد User را لازم کند.');
p('Legacy only: SNMPv2c below is unencrypted. Keep it only for a documented migration exception; never add it alongside v3 merely for convenience. Primary recommendation: SNMPv3 + Authentication + Encryption + ACL.', 'فقط Legacy: SNMPv2c زیر رمزنگاری ندارد. صرفاً در استثنای مهاجرت مستند نگه دارید؛ برای سهولت آن را کنار v3 اضافه نکنید. توصیه اصلی: SNMPv3 + Authentication + Encryption + ACL.');
code("ip access-list standard SNMP-ACL\n permit host <MONITORING-IP>\n deny any log\nexit\nsnmp-server community <COMMUNITY> RO SNMP-ACL");

$login="login block-for 120 attempts 5 within 60";
sec('login','20. Login Attack Protection','۲۰. حفاظت در برابر حمله Login');
feature(['Throttle repeated failed remote logins.','مهار Login ناموفق تکراری.'],['Password guessing consumes resources and threatens admin accounts.','حدس رمز منابع را مصرف و حساب مدیر را تهدید می‌کند.'],$login,['Five failed attempts within 60 seconds trigger a 120-second quiet period for remote login access. This is device-wide protection, not simply a per-user lockout.','پنج تلاش ناموفق در ۶۰ ثانیه، Quiet Period برابر ۱۲۰ ثانیه برای Login راه دور ایجاد می‌کند. این حفاظت در سطح دستگاه است و صرفاً Lockout یک User نیست.'],['show login should report configured thresholds and quiet-mode status. Test failures in a maintenance window using console recovery.','show login باید Threshold و وضعیت Quiet Mode صحیح نشان دهد. تست شکست Login در Maintenance Window با Console آماده انجام شود.'],['An attacker can deliberately trigger quiet mode. Consider a narrowly scoped login quiet-mode access-class <BREAKGLASS-ACL> if supported and approved; never exempt a broad user subnet.','مهاجم می‌تواند عمدی Quiet Mode ایجاد کند. در صورت پشتیبانی و تأیید Policy، login quiet-mode access-class <BREAKGLASS-ACL> با Scope محدود بررسی شود؛ User Subnet گسترده معاف نشود.']);
dependency('Login enhancement support and interaction with AAA differ; inspect show login on the actual image.', 'پشتیبانی Login Enhancement و تعامل AAA متفاوت است؛ show login روی Image واقعی بررسی شود.');

sec('verification','21. Verification and Acceptance','۲۱. اعتبارسنجی و پذیرش');
code("show running-config\nshow users\nshow ip ssh\nshow login\nshow access-lists\nshow spanning-tree\nshow spanning-tree inconsistentports\nshow port-security\nshow port-security interface <INTERFACE>\nshow ip dhcp snooping\nshow ip dhcp snooping binding\nshow ip arp inspection\nshow ip arp inspection interfaces\nshow logging\nshow clock\nshow ntp associations\nshow snmp\nshow ip interface brief\nshow ip route");
table([['Group','گروه'],['Expected result','نتیجه مورد انتظار']],[[['Management / AAA / SSH / ACL','مدیریت / AAA / SSH / ACL'],['Fresh approved SSH login succeeds; denied source/Telnet fails; privilege and counters match','SSH جدید مجاز موفق، مبدأ غیرمجاز و Telnet ناموفق؛ Privilege و Counter صحیح']], [['STP / Port Security','STP / Port Security'],['Planned root, no unexpected inconsistent/err-disabled ports, correct learned MACs','Root طراحی‌شده، نبود Inconsistent/err-disabled غیرمنتظره و MAC درست']], [['DHCP / DAI / IPSG','DHCP / DAI / IPSG'],['DHCP renew succeeds, bindings match inventory, only selected ingress trusted, static hosts work','Renew موفق، Binding مطابق Inventory، Trust محدود ورودی و Static Host سالم']], [['Telemetry','Telemetry'],['Collector receives chosen severities; NTP selected peer; authorized authPriv polling succeeds','Collector سطح انتخاب‌شده را دریافت کند؛ Peer NTP منتخب؛ Poll مجاز authPriv موفق']], [['SVI / Routing','SVI / Routing'],['Management up/up; L3 connected/default routes and service exceptions valid; L2 management gateway reachable','مدیریت up/up؛ Route متصل/Default و استثنای سرویس در L3 صحیح؛ Gateway مدیریتی L2 قابل دسترسی']]]);
p('Command output alone is insufficient: test permitted and denied traffic, DHCP renewal, phone reboot, static printer access, NMS polling, failover and reload binding recovery. Use show ip verify source and show storm-control where supported. Save with copy running-config startup-config only after acceptance and capture a post-change backup. Retain an operational rollback procedure.', 'خروجی Show کافی نیست؛ ترافیک مجاز و غیرمجاز، DHCP Renew، Reboot تلفن، Printer Static، Poll NMS، Failover و بازیابی Binding پس از Reload تست شود. در صورت پشتیبانی show ip verify source و show storm-control استفاده کنید. فقط پس از پذیرش copy running-config startup-config و Backup بعد از تغییر انجام شود. Rollback عملیاتی حفظ شود.');

sec('final-configs','22. Final Independent Configurations','۲۲. پیکربندی‌های نهایی مستقل');
p('Each file includes its own management baseline; no earlier block must be pasted to complete it. Replace every placeholder. The L2 role has an upstream trunk; the L3 role has a routed uplink to the upstream boundary and a downstream trunk to inspected access switches. ACCESS-PORTS means reviewed DHCP endpoint ports only. Static devices, AP trunks and infrastructure ports require their own profiles. USER-VLANS must include all intended DHCP user/voice VLANs, and each VLAN must be created; VLAN10 is the shown data example.', 'هر فایل Baseline مدیریت خودش را دارد و برای تکمیل نیازمند کپی بلوک قبلی نیست. تمام Placeholderها جایگزین شوند. نقش L2 دارای Trunk بالادست و نقش L3 دارای Uplink Routed به مرز بالادست و Trunk پایین‌دست به Accessهای دارای Inspection است. ACCESS-PORTS فقط پورت Endpoint DHCP بررسی‌شده است. Static Device، AP Trunk و Infrastructure به Profile جدا نیاز دارند. USER-VLANS شامل VLANهای DHCP کاربر/Voice لازم باشد و همه VLANها ساخته شوند؛ VLAN10 مثال Data است.');
table([['Placeholder','Placeholder'],['Meaning / example','معنی / مثال']],array_map(fn($r)=>[[$r[0],$r[0]],[$r[1],$r[2]]],[
['<HOSTNAME> / <SWITCH-NAME>','Unique switch identity','نام یکتای سوئیچ'],['<MGMT-VLAN> / <MGMT-IP> / <MASK>','99; L2 10.99.99.2 or L3 10.99.99.1; 255.255.255.0','99؛ L2 برابر 10.99.99.2 یا L3 برابر 10.99.99.1؛ Mask برابر 255.255.255.0'],['<ADMIN-SUBNET> / <WILDCARD>','Approved admin sources, e.g. 10.99.99.128 / 0.0.0.31; not all management by default','مبدأ مدیر مجاز؛ مثال 10.99.99.128 / 0.0.0.31؛ نه کل مدیریت به‌صورت پیش‌فرض'],['<SYSLOG-IP> / <NTP-IP> / <MONITORING-IP>','Example: 10.99.99.30 / 10.99.99.20 / 10.99.99.40','مثال: 10.99.99.30 / 10.99.99.20 / 10.99.99.40'],['<UPLINK> / <DOWNLINK-TRUNK>','Reviewed physical interface or supported port-channel; ranges must not overlap','اینترفیس یا Port-channel پشتیبانی‌شده و بررسی‌شده؛ Rangeها هم‌پوشانی نداشته باشند'],['<ACCESS-PORTS> / <UNUSED-PORTS>','Disjoint tested interface ranges','Rangeهای تست‌شده و بدون اشتراک'],['<USER-VLANS> / <VLAN-LIST>','10 (plus reviewed voice VLANs); 10,99 and required VLANs only','10 و Voice بررسی‌شده؛ 10,99 و فقط VLAN لازم'],['<GATEWAY>','L2 management gateway: 10.99.99.1','Gateway مدیریت L2: 10.99.99.1'],['<TRANSIT-IP> / <TRANSIT-MASK> / <UPSTREAM-NEXT-HOP>','10.255.255.2 / 255.255.255.252 / 10.255.255.1','10.255.255.2 / 255.255.255.252 / 10.255.255.1'],['<RATE> / <ARP-RATE>','Measured DHCP/ARP packets per second, not universal defaults','Packet/s اندازه‌گیری‌شده DHCP/ARP؛ Default عمومی نیست'],['<BCAST-RISE> / <BCAST-FALL> / <MCAST-RISE> / <MCAST-FALL>','Measured percentages; earlier 1/0.5 and 2/1 are illustrative','درصد اندازه‌گیری‌شده؛ 1/0.5 و 2/1 قبلی صرفاً مثال'],['<ADMIN> / <STRONG-PASSWORD> / <DOMAIN.LOCAL>','Vault-managed credentials and organization domain','Credential در Vault و Domain سازمان'],['<SNMP-USER> / <SNMP-AUTH-PASSWORD> / <SNMP-PRIV-PASSWORD>','NMS account and two independent secrets','حساب NMS و دو Secret مستقل'],['<TZ-NAME> / <OFFSET>','Display timezone; IRST / 3 30 is an example','Timezone نمایش؛ مثال IRST / 3 30']]));
$common=$identity."\nusername <ADMIN> privilege 15 algorithm-type scrypt secret <STRONG-PASSWORD>\naaa new-model\naaa authentication login default local\naaa authorization exec default local\n".$services."\n".$login."\n".$ssh."\n".$ntp."\n".$syslog."\n".$snmp;
$vlans="vlan 10\n name USERS\nexit\nvlan <MGMT-VLAN>\n name MANAGEMENT\nexit\nvlan 998\n name UNUSED-NATIVE\nexit\nvlan 999\n name UNUSED-PORTS\nexit";
$edge="interface range <ACCESS-PORTS>\n description REVIEWED-DHCP-ENDPOINTS\n switchport mode access\n switchport access vlan 10\n switchport nonegotiate\n spanning-tree portfast\n spanning-tree bpduguard enable\n ip dhcp snooping limit rate <RATE>\n ip arp inspection limit rate <ARP-RATE>\n ip verify source\n switchport port-security\n switchport port-security maximum 3\n switchport port-security violation restrict\n switchport port-security mac-address sticky\n storm-control broadcast level <BCAST-RISE> <BCAST-FALL>\n storm-control multicast level <MCAST-RISE> <MCAST-FALL>\n storm-control action trap\n no shutdown\nexit";
$park="interface range <UNUSED-PORTS>\n switchport mode access\n switchport access vlan 999\n shutdown\nexit";
$global="spanning-tree mode rapid-pvst\nspanning-tree portfast bpduguard default\nip dhcp snooping\nip dhcp snooping vlan <USER-VLANS>\nno ip dhcp snooping information option\nip arp inspection vlan <USER-VLANS>";
$l2="! Cisco Layer 2 Access Switch Hardened Configuration\n! Replace placeholders; apply in reviewed stages, not as a blind paste.\nconfigure terminal\n".$vlans."\n".$common."\nno ip routing\nip default-gateway <GATEWAY>\ninterface Vlan<MGMT-VLAN>\n description MANAGEMENT\n ip address <MGMT-IP> <MASK>\n no shutdown\nexit\n".$global."\ninterface <UPLINK>\n description TRUSTED-UPSTREAM-TO-CORE\n switchport mode trunk\n switchport trunk native vlan 998\n switchport trunk allowed vlan <VLAN-LIST>\n switchport nonegotiate\n ip dhcp snooping trust\n ip arp inspection trust\n no shutdown\nexit\n".$edge."\n".$park."\nend\n! Validate, then separately run: copy running-config startup-config\n";
$l3="! Cisco Layer 3 Switch Hardened Configuration\n! Routed upstream; inspected access switches on downstream trunk.\n! Ensure DHCP service/relay and upstream return routes already exist.\nconfigure terminal\n".$vlans."\n".$common."\nip routing\ninterface Vlan<MGMT-VLAN>\n description MANAGEMENT\n ip address <MGMT-IP> <MASK>\n no ip redirects\n no ip proxy-arp\n no shutdown\nexit\ninterface Vlan10\n description USERS-GATEWAY\n ip address 10.10.10.1 255.255.255.0\n no ip redirects\n no ip proxy-arp\n no shutdown\nexit\ninterface <UPLINK>\n description ROUTED-UPSTREAM\n no switchport\n ip address <TRANSIT-IP> <TRANSIT-MASK>\n no ip redirects\n no ip proxy-arp\n no shutdown\nexit\nip route 0.0.0.0 0.0.0.0 <UPSTREAM-NEXT-HOP>\n".$useracl."\n".$global."\ninterface <DOWNLINK-TRUNK>\n description TO-INSPECTED-ACCESS-SWITCH\n switchport mode trunk\n switchport trunk native vlan 998\n switchport trunk allowed vlan <VLAN-LIST>\n switchport nonegotiate\n ! DHCP replies originate locally/upstream: this downstream ingress is untrusted.\n ! ARP trust only because downstream Catalyst enforces DAI on every endpoint port.\n ip arp inspection trust\n no shutdown\nexit\n".$edge."\n".$park."\nend\n! Validate, then separately run: copy running-config startup-config\n";
note('Template prerequisites: Type 9, VTY 0–15 and feature syntax must be supported. DHCP service or relay is existing infrastructure, not created here; verify the full request/reply path on the L3 platform. The downstream L3 trunk stays DHCP-untrusted because servers are local/upstream, but DAI-trusted only when downstream enforcement is verified. Aggregation switches do not necessarily learn bindings for all remote endpoints. Change these boundaries to match the real topology. The L3 edge Port Security block is optional; remove it if no directly connected endpoint ports exist.', 'پیش‌نیاز Template: Type 9، VTY 0 تا 15 و Syntax قابلیت‌ها باید پشتیبانی شوند. سرویس یا Relay DHCP از قبل وجود دارد و اینجا ساخته نمی‌شود؛ کل مسیر درخواست/پاسخ روی L3 بررسی شود. Trunk پایین‌دست L3 برای DHCP همچنان Untrusted است چون سرور Local/Upstream است؛ فقط با تأیید Inspection پایین‌دست برای DAI Trusted می‌شود. سوئیچ تجمیع الزاماً Binding همه کاربران دور را یاد نمی‌گیرد. مرزها را با توپولوژی واقعی تطبیق دهید. بلوک Port Security پورت Edge در L3 اختیاری است؛ اگر Endpoint مستقیم ندارید آن را حذف کنید.');
dependency('The final templates are complete role-specific baselines, not replacements for live routing, voice, authentication, CoPP or DHCP infrastructure configuration. Merge deliberately. Root Guard and Loop Guard are excluded until port roles are reviewed; authenticated NTP and centralized AAA use the separately reviewed deployment choices above.', 'قالب نهایی Baseline کامل مخصوص نقش است، نه جایگزین Routing، Voice، Authentication، CoPP یا زیرساخت DHCP موجود. با بررسی Merge کنید. Root Guard و Loop Guard تا تعیین نقش پورت اضافه نشده‌اند؛ NTP احرازشده و AAA مرکزی به انتخاب استقرار بررسی‌شده بخش‌های قبلی نیاز دارند.');
p('Cisco Layer 2 Access Switch Hardened Configuration','پیکربندی امن مستقل Cisco Layer 2 Access Switch'); code($l2);
p('Cisco Layer 3 Switch Hardened Configuration','پیکربندی امن مستقل Cisco Layer 3 Switch'); code($l3);
global $parts;
foreach(['l2-access.cfg'=>'Download the L2 access template','l3-switch.cfg'=>'Download the L3 switch template'] as $file=>$label) $parts[]=dual('a',$label,$file==='l2-access.cfg'?'دانلود پیکربندی L2 Access':'دانلود پیکربندی L3', 'href="/downloads/'.$slug.'/'.$file.'"');

sec('warnings','23. Important Warnings','۲۳. هشدارهای مهم');
foreach([
['SSH lockout: keep console/OOB access and a tested local account; validate a fresh session before closing the current one.','SSH Lockout: Console/OOB و حساب Local تست‌شده در دسترس باشد؛ پیش از بستن نشست فعلی SSH جدید را تست کنید.'],
['DHCP trust: trusting an access endpoint allows rogue server replies. Trust only approved ingress from legitimate server paths.','DHCP Trust: Trust کردن Endpoint پاسخ Rogue را مجاز می‌کند؛ فقط ورودی مسیر سرور معتبر Trusted باشد.'],
['DAI and static hosts: install reviewed ARP ACLs before enforcement; otherwise legitimate ARP may be dropped.','DAI و Static Host: ARP ACL بررسی‌شده قبل از Enforcement اعمال شود؛ وگرنه ARP مجاز Drop می‌شود.'],
['IPSG and static hosts: DHCP bindings may be absent; use supported manual bindings or a reviewed static-host design.','IPSG و Static Host: ممکن است Binding DHCP وجود نداشته باشد؛ Binding دستی پشتیبانی‌شده یا طراحی Static بررسی‌شده لازم است.'],
['Phone plus PC: maximum MAC and voice/data behavior must be tested; a generic maximum can reject a legitimate phone or replacement device.','Phone و PC: Maximum MAC و رفتار Voice/Data تست شود؛ Maximum عمومی می‌تواند تلفن یا دستگاه جایگزین مجاز را رد کند.'],
['BPDU Guard on uplinks: received BPDUs can err-disable the link and isolate the switch. Use only on intended endpoint edges.','BPDU Guard روی Uplink: BPDU می‌تواند لینک را err-disable و سوئیچ را جدا کند؛ فقط روی Edge Endpoint مورد نظر استفاده شود.'],
['Root Guard on the wrong link: a legitimate upstream root can become root-inconsistent and disconnect service.','Root Guard روی لینک نادرست: Root معتبر بالادست می‌تواند Root-inconsistent و سرویس قطع شود.'],
['Management ACL: wrong wildcard, NAT source or ordering can deny every administrator. Check actual source and every VTY range.','Management ACL: Wildcard، مبدأ NAT یا ترتیب اشتباه می‌تواند همه مدیران را رد کند؛ مبدأ واقعی و تمام VTYها بررسی شود.'],
['no ip routing on an L3 switch disables routed forwarding and can stop inter-VLAN service immediately. Never use the L2 template on the L3 role.','no ip routing روی سوئیچ L3 انتقال Routed را غیرفعال و سرویس بین VLANها را فوراً قطع می‌کند؛ Template لایه ۲ روی نقش لایه ۳ اجرا نشود.']
] as [$en,$fa]) note($en,$fa);

sec('checklist','24. Final Hardening Checklist','۲۴. چک‌لیست نهایی');
p('Mark Status only after verification. L3 checks for Layer 2 protections refer to Layer 2 switchports/VLANs present on that L3 Catalyst, not routed interfaces; pure transit cores may not need those controls locally.', 'Status فقط پس از تست تکمیل شود. کنترل‌های Layer 2 در ستون L3 مربوط به Switchport/VLAN لایه ۲ موجود در آن Catalyst است، نه اینترفیس Routed؛ Core صرفاً Transit ممکن است محلی به آن‌ها نیاز نداشته باشد.');
table([['Security Control','کنترل امنیتی'],['L2','L2'],['L3','L3'],['Status','وضعیت']],array_map(fn($r)=>[[$r[0],$r[0]],[$r[1],$r[1]],[$r[2],$r[2]==='Optional'?'اختیاری':$r[2]],['','']],[['AAA','✓','✓'],['SSHv2','✓','✓'],['Management ACL','✓','✓'],['SNMPv3','✓','✓'],['Syslog','✓','✓'],['NTP','✓','✓'],['DHCP Snooping','✓','✓'],['DAI','✓','✓'],['IP Source Guard','✓','Optional'],['BPDU Guard','✓','✓'],['Port Security','✓','Optional'],['Storm Control','✓','✓'],['Routing Hardening','N/A','✓'],['SVI ACL','N/A','✓']]));

sec('references','Official Cisco References','منابع رسمی Cisco');
p('Reviewed on 2026-10-07. References describe particular Catalyst releases or software families; consult the matching guide, release notes and security advisories for the deployed PID/image. Examples are editorially reviewed against Cisco documentation; they have not been executed on your switches.', 'بررسی منابع: 2026-10-07. منابع مربوط به نسخه یا خانواده نرم‌افزاری مشخص‌اند؛ راهنمای منطبق، Release Note و Security Advisory مربوط به PID/Image واقعی بررسی شود. مثال‌ها با مستندات Cisco بازبینی شده‌اند؛ روی سوئیچ شما اجرا نشده‌اند.');
$sources=[
['https://sec.cloudapps.cisco.com/security/center/resources/IOS_XE_hardening','Cisco IOS XE Software Hardening Guide'],
['https://www.cisco.com/c/en/us/support/docs/ip/access-lists/13608-21.html','Cisco IOS device hardening guidance'],
['https://www.cisco.com/c/en/us/td/docs/switches/lan/catalyst9300/software/release/17-11/command_reference/b_1711_9300_cr/security_commands.html','Catalyst 9300 security command reference: passwords, AAA and controls'],
['https://www.cisco.com/c/en/us/td/docs/switches/lan/catalyst9300/software/release/17-7/configuration_guide/sec/b_177_sec_9300_cg/configuring_secure_shell__ssh_.html','Catalyst 9300: Secure Shell'],
['https://www.cisco.com/c/en/us/td/docs/switches/lan/catalyst9300/software/release/17-12/configuration_guide/ip/b_1712_ip_9300_cg/configuring_dhcp.html','Catalyst 9300: DHCP and snooping'],
['https://www.cisco.com/c/en/us/td/docs/switches/lan/catalyst9300/software/release/17-18/configuration_guide/sec/b_1718_sec_9300_cg/configuring_dynamic_arp_inspection.html','Catalyst 9300: Dynamic ARP Inspection'],
['https://www.cisco.com/c/en/us/td/docs/switches/lan/catalyst9300/software/release/17-12/configuration_guide/sec/b_1712_sec_9300_cg/configuring_ip_source_guard.html','Catalyst 9300: IP Source Guard'],
['https://www.cisco.com/c/en/us/support/docs/switches/lan-switch-software/222274-troubleshoot-dynamic-arp-inspection-dai.html','Catalyst: troubleshooting DAI and IPSG'],
['https://www.cisco.com/c/en/us/td/docs/switches/lan/catalyst9300/software/release/17-14/configuration_guide/lyr2/b_1714_lyr2_9300_cg/configuring_optional_spanning_tree_features.html','Catalyst 9300: PortFast, BPDU Guard, Root Guard and Loop Guard'],
['https://www.cisco.com/c/en/us/td/docs/switches/lan/catalyst9300/software/release/17-12/command_reference/b_1712_9300_cr/security_commands.html','Catalyst 9300: Port Security and Storm Control commands'],
['https://www.cisco.com/c/en/us/td/docs/switches/lan/catalyst9300/software/release/16-6/configuration_guide/nmgmt/b_166_nmgmt_9300_cg/b_166_nmgmt_9300_cg_chapter_010.html','Catalyst 9300: SNMP groups, views and users'],
['https://www.cisco.com/c/en/us/td/docs/switches/lan/catalyst9300/software/release/16-12/configuration_guide/sys_mgmt/b_1612_sys_mgmt_9300_cg.pdf','Catalyst 9300: system management, NTP and logging'],
['https://www.cisco.com/c/en/us/td/docs/switches/lan/catalyst9300/software/release/16-12/configuration_guide/rtng/b_1612_rtng_9300_cg.pdf','Catalyst 9300: IP routing and authentication variants'],
['https://www.cisco.com/c/en/us/td/docs/switches/lan/catalyst9300/software/release/17-3/configuration_guide/vlan/b_173_vlan_9300_cg/configuring_vlan_trunks.html','Catalyst 9300: VLAN trunks and DTP'],
['https://www.cisco.com/c/en/us/td/docs/switches/lan/catalyst9300/software/release/16-8/configuration_guide/sec/b_168_sec_9300_cg/configuring_ipv4_acls.html','Catalyst 9300: IPv4 ACLs'],
['https://www.cisco.com/c/en/us/td/docs/switches/lan/catalyst9300/software/release/17-6/configuration_guide/sec/b_176_sec_9300_cg/configuring_control_plane_policing.html','Catalyst 9300: Control Plane Policing'],
['https://www.cisco.com/c/en/us/td/docs/switches/lan/catalyst9300/software/release/17-7/configuration_guide/rtng/b_177_rtng_9300_cg/configuring_ip_unicast_routing.html','Catalyst 9300: unicast routing and Proxy ARP'],
];
foreach($sources as [$url,$label]) $parts[]='<p>'.dual('a',$label,'مرجع رسمی: '.$label,'href="'.e($url).'" rel="noopener"').'</p>';
$parts[]='</section>';
$keywords=['Cisco Catalyst','Switch Hardening','Cisco IOS','IOS XE','Layer 2 Security','Layer 3 ACL','DHCP Snooping','Dynamic ARP Inspection','SNMPv3'];
$local=[]; foreach(['en','fa'] as $lang) $local[$lang]=['title'=>$title[$lang],'meta_title'=>$title[$lang],'description'=>$desc[$lang],'keywords'=>$keywords,'faq'=>[]];
$nav=''; foreach($toc as [$id,$en,$fa]) $nav.='<li class="article-nav-item">'.dual('a',$en,$fa,'href="#'.$id.'"').'</li>';
$url='https://meetaj.ir/articles/'.$slug;
$html='<!doctype html><html lang="en" dir="ltr" data-article-language="en"><head><meta charset="UTF-8"><title>'.e($title['en']).'</title><meta name="article:content-language" content="en"><meta name="description" content="'.e($desc['en']).'"><meta name="keywords" content="'.e(implode(', ',$keywords)).'"><meta property="og:title" content="'.e($title['en']).'"><meta property="og:description" content="'.e($desc['en']).'"><meta property="og:type" content="article"><link rel="canonical" href="'.$url.'"><script id="article-localizations" type="application/json">'.json_encode($local,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES).'</script></head><body class="article-page theme-other"><header><nav><ul>'.$nav.'</ul></nav></header><main><section class="article-hero article-header hero">'.dual('span','Networking','شبکه','class="article-category"').dual('h1',$title['en'],$title['fa'],'class="article-title hero-title"').dual('p',$desc['en'],$desc['fa'],'class="article-excerpt hero-subtitle"').'</section><article class="article-body" lang="en" dir="ltr">'.implode("\n",$parts).'</article></main></body></html>';
$html=str_replace('theme-other','theme-cisco',$html);
$html=str_replace(dual('span','Networking','شبکه','class="article-category"'),dual('span','Cisco','سیسکو','class="article-category"'),$html);
$schema=['@context'=>'https://schema.org','@type'=>'Article','headline'=>$title['en'],'description'=>$desc['en'],'inLanguage'=>'en','datePublished'=>'2026-10-07T00:00:00+03:30','dateModified'=>'2026-10-07','author'=>['@type'=>'Person','name'=>'AmirHossein Jalalian']];
$banner='/assets/img/articles/banners/Cisco Switch Hardening Best Practices.png';
$bannerSource=$root.'/resources'.$banner;
if (is_file($bannerSource)) {
    $bannerDestination=$root.'/public'.$banner;
    if (!is_dir(dirname($bannerDestination))) mkdir(dirname($bannerDestination),0775,true);
    copy($bannerSource,$bannerDestination);
    $schema['image']=$banner;
    $html=str_replace('</head>','<meta property="og:image" content="'.e($banner).'"></head>',$html);
    $html=str_replace('</section><article class="article-body"','<img class="article-hero-thumbnail" src="'.e($banner).'" alt="Cisco Catalyst L2 and L3 switch hardening"></section><article class="article-body"',$html);
}
$html=str_replace('</head>','<script type="application/ld+json">'.json_encode($schema,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES).'</script></head>',$html);
require_once dirname(__DIR__).'/app/Services/ArticleStructure.php';
$html = (new \App\Services\ArticleStructure)->repair($html, $slug);
file_put_contents($root.'/resources/legacy/articles/'.$slug.'.html',$html);
$download=$root.'/public/downloads/'.$slug; if(!is_dir($download)) mkdir($download,0775,true);
file_put_contents($download.'/l2-access.cfg',$l2); file_put_contents($download.'/l3-switch.cfg',$l3);
echo 'Built '.$slug.': '.count($toc).' bilingual sections and two independent configuration downloads.'.PHP_EOL;
