"""Editorial English counterparts. Code is inherited verbatim from the Persian source."""
from pathlib import Path
import json

EN = {}
def add(slug, title, description, intro, scenario, prerequisites, architecture, installation, security, monitoring, troubleshooting, recovery, practices, compatibility, faq):
    title = title.replace('Enterprise Boot Media', 'Bootable USB Media').replace('Enterprise IMAP and POP3', 'IMAP vs POP3')
    scenario = scenario.removeprefix('Illustrative scenario at fictional Arya: ')
    scenario = scenario[:1].upper() + scenario[1:]
    EN[slug] = dict(title=title,description=description,keywords=[title.split(':')[0],slug.replace('-',' '),'infrastructure operations','production operations','troubleshooting'],intro=intro,scenario=scenario,prerequisites=prerequisites,architecture=architecture,installation=installation,security=security,monitoring=monitoring,troubleshooting=troubleshooting,recovery=recovery,practices=practices,compatibility=compatibility,faq=faq)

UBUNTU='Ubuntu Server 24.04 LTS, Bash 5 and systemd. Record installed package patches with dpkg-query before making changes.'
HW='Example lab capacity: 2 vCPUs, 2 GiB RAM and 20 GiB storage. These are planning assumptions, not vendor minimums; size the service for measured load.'
ROS='MikroTik RouterOS v7. Record the exact patch and architecture with /system resource print. Review v6 commands before using them on v7.'
ROSHW='Use a router or isolated CHR lab with separate interfaces. Measure CPU, RAM and connection tracking under representative load.'
ROSPERM='Connect from the management network with the required write policies. Before changing configuration, enable Safe Mode with Ctrl+X, save an off-device export and arrange independent console access.'
WIN='Windows Server 2022/2025 or Windows 11 with 64-bit Windows PowerShell 5.1. Server cmdlets require their corresponding roles and modules.'
WINHW='Use an authorized existing host; diagnostic tools need no additional hardware. A sample lab VM can use 2 vCPUs, 4 GiB RAM and 60 GiB storage.'

add('enable-ssh-linux-complete-guide','Production SSH: Key Authentication, Security Hardening and Access Recovery',
'Configure production SSH with key authentication, bastion access, effective configuration checks, independent login validation and a tested rollback path.',
'An authentication change can leave a healthy server unreachable by the operations team. This runbook pairs access controls with an independent login test and a recovery path.',
'Illustrative scenario at fictional Arya: operations manages 40 VMs through a bastion on 10.20.30.0/24. Public Internet login is blocked, and changes reach a canary first.',
[UBUNTU,HW,'Install openssh-server on the server and openssh-client on the workstation. Authorized sudo and console access are required. Replace opsadmin and 10.20.30.10 with approved account and address values.'],
'Workstation → VPN/MFA → bastion → management Firewall → sshd → personal account → sudo. Keep the private key on the workstation and verify the server fingerprint through the console.',
['Record the version, listener and service state first. Install only the SSH package; do not combine this change with a full system upgrade.',
'On the workstation, generate a passphrase-protected key and install it for an account that already exists. Compare the host fingerprint before accepting the connection.',
'On the server, inspect ownership and permissions as that account. After the second session succeeds, write the configuration from an authorized sudo session.',
'Successful sshd -t produces no output. Effective configuration from -T must show passwordauthentication no. Keep the first session open and verify key login plus sudo in a third session. Include all required human and automation accounts in AllowUsers before deployment.'],
'Restrict upstream TCP/22 access to the bastion. The example ufw allow from 10.20.30.0/24 to any port 22 proto tcp applies only to an existing UFW deployment; do not enable an unplanned Firewall remotely. Changing the port does not replace authentication. Use MFA on the bastion. If SSH itself uses PAM MFA, reconcile KbdInteractiveAuthentication no with that design. Under FIPS policy, check Ed25519 acceptance and use RSA with SHA-2 signatures where required.',
'Use journalctl -u ssh.service --since "15 minutes ago" to investigate logins. Monitor TCP availability and authorized login separately in Zabbix. More than 10 failed logins in five minutes is an illustrative threshold. Include hostname, source IP and UTC time in alerts; exclude private keys and tokens.',
['Connection refused points to a listener or reject response; timeouts more often indicate routing or dropped traffic. Inspect the server and client independently with these commands.',
'For Permission denied with bad ownership in the log, correct HOME and .ssh ownership. If a valid key is rejected, inspect AllowUsers, Match blocks and effective configuration using -T -C. Ubuntu may use ssh.socket; a port change requires checking both sshd and its socket listener for that patch. This runbook leaves the port unchanged.'],
['The /etc/ssh backup contains host keys: encrypt it and restrict access. To roll back this change from the console or an open session, move out only the new snippet, validate and reload.',
'If existing settings were changed, restore their recorded backup. VM recovery must not create duplicate host keys across different servers.'],
'Manage personal accounts, passphrases, departed staff keys and sudo reviews in one lifecycle. Before closing the last session, verify login, privileges and auditing through the real management path.',
'Do not apply Ubuntu commands unchanged to RHEL: the service is commonly sshd and the package manager differs. The old PermitRootLogin yes recommendation is retired for production. A restart does not necessarily terminate every established session; inspect daemon and systemd behavior separately.',
[['Is changing the SSH port enough?','No. Source restrictions, keys, account lifecycle controls and audit records are still required.'],['What must pass before password login is disabled?','Key login and sudo in an independent session, with console recovery available.']])

add('set-static-ip-ubuntu-server-netplan','Ubuntu Server Netplan: Static IP Changes with Validation and Rollback',
'Change Ubuntu Server addressing through Netplan with IPAM checks, YAML ownership, client validation and console-based rollback.',
'An IP change over SSH can interrupt management, DNS and backup traffic together. Apply Netplan changes with explicit file ownership, preflight checks and confirmation from a separate client.',
'Illustrative scenario at fictional Arya: an application VM in VLAN 30 moves from DHCP to 10.20.30.10/24. NetBox holds the reservation, and networking has validated the trunk and ACLs.',
[UBUNTU,HW,'Use netplan.io and systemd-networkd with sudo, console access and an IPAM reservation. ens160, 10.20.30.10, gateway and DNS values form a complete lab example; replace them for your environment.'],
'Netplan YAML → generator → systemd-networkd → NIC/VLAN → gateway. systemd-resolved owns DNS. Multiple YAML files merge; adding a new file does not automatically remove earlier settings.',
['Record the current state from the console and back up the entire directory.',
'This configuration targets a single-NIC VM with one authoritative network file. Identify the active file and remove conflicting YAML ownership. If cloud-init generates it, transfer ownership deliberately or update the cloud configuration source.',
'Before accepting netplan try, test the gateway, SSH and DNS from another client. Expect the specified address on ens160, only the intended default route and no generator errors. Test timeout rollback on the target platform; keep console recovery available rather than relying on it alone.'],
'Mode 600 limits access to sensitive YAML content. A static IP does not replace a Firewall. Preserve internal DNS and management routing; a successful ping does not prove all services are available. Configure IPv6 according to organizational policy and evaluate its routes too.',
'Monitor availability, packet loss and address changes in Zabbix; node_exporter exposes interface errors to Prometheus. Alert networking on route changes or more than two consecutive missed polls. Run application health checks from the consumer subnet.',
['YAML errors commonly arise from indentation or tabs; generate identifies their location. Multiple default routes can come from merged files or remaining DHCP settings.',
'Correct IP with an unreachable gateway: inspect VLANs, mask and ARP. Working routing with broken DNS: inspect the resolver and port-53 ACLs. Settings that revert after reboot indicate cloud-init or automation still owns the configuration; correct its source.'],
['From the console, remove the new file and restore the previous YAML from backup. Do not blindly merge backups containing overlapping definitions.',
'Keep IPAM, VLAN and routing records outside the VM. After rollback, test access from both management and application subnets.'],
'Do not change NIC, VLAN and IP simultaneously. Check address conflicts, keep a live console and validate a canary before accepting the rollout.',
'Replace older gateway4 examples with routes. Desktop deployments may use NetworkManager; this example uses networkd. netplan try has rollback limitations for some virtual-link configurations.',
[['Does netplan try guarantee recovery?','No. Review rollback limitations and retain an independent console.'],['Why do settings revert after reboot?','Cloud-init or a configuration management tool usually still generates the file.']])

add('linux-security-account-access-management','Linux Access Management: Account Lifecycle, Restricted sudo and Offboarding',
'Build a Linux access model with personal accounts, command-specific sudo, negative permission tests and complete credential revocation.',
'Locking a password does not necessarily revoke access for a departing employee. SSH keys, tokens and existing sessions may remain valid. Access control must follow identity and account lifecycle.',
'Illustrative scenario at fictional Arya: shift support can inspect Nginx status but cannot restart it or edit service files. Offboarding revokes bastion and VM access.',
[UBUNTU,HW,'Use sudo and OpenSSH with an administrator who has console access. opsreader and its permission mapping are examples. Organizational directory access needs a separate review of SSSD/LDAP configuration.'],
'Identity → group → SSH admission → sudo command allowlist → audit. Separate human and service accounts, and use rotatable credentials for automation.',
['Check that the name is available, then create the account without sudo-group membership.',
'Place the complete rule below in the file. The systemctl path must match the host. --no-pager prevents privilege escape through an interactive pager.',
'Expect syntax OK and permission for only this exact command. An inactive service makes status return nonzero; that is not necessarily a permission error. In staging, also verify that a restart is denied.'],
'Do not grant broadly privileged shells, editors, package managers or wildcards as supposedly restricted sudo access: many can execute root code. Service accounts should not have interactive login. During offboarding, review keys, directory membership, API tokens, cron, sudo and active sessions. passwd -l locks only the password.',
'Forward sudo and SSH events from journalctl to central logging. Use auditd to monitor changes to /etc/passwd, /etc/group and /etc/sudoers.d. The UID-zero baseline should contain only the authorized account.',
['Use sudo -l to separate privilege failures from service errors. visudo -cf identifies parse problems. A user who logs in despite a locked password may be using a key.',
'Distinguish directory access from local groups: identity caches and old sessions may persist until logout. Terminate a session only after confirming its user ID and assessing running jobs.'],
'Version policies, UID/GID mappings and permissions. Store shadow and private keys only in encrypted backups. Roll back this grant by removing its snippet and validating with visudo. Retain HOME according to policy during offboarding; revoke access and transfer organizational data to its owner.',
'Define permissions using exact commands and negative tests. Keep emergency credentials in a vault, personal accounts in the directory and changes linked to tickets.',
'usermod -aG sudo grants broad privileges and is unsuitable for this read-only role. Password locking is not equivalent to disabling every authentication method.',
[['Does passwd -l disable an SSH key?','No. Keys and other credentials require separate revocation.'],['Why include --no-pager in a sudo rule?','A pager may provide a shell using the privileges of the invoking command.']])

add('nginx-installation-configuration-ubuntu','Production Nginx: Reverse Proxy, TLS and Upstream Troubleshooting',
'Deploy Nginx with a complete TLS reverse proxy, bounded timeouts, independent upstream checks, monitoring and validated reloads.',
'A healthy Nginx process does not prove the application is healthy. A reverse proxy needs bounded timeouts, request IDs, valid TLS and independent upstream checks so 502 failures can be traced.',
'Illustrative scenario at fictional Arya: an internal application listens on loopback and clients reach only the TLS proxy. Changes reach one canary VM before the Load Balancer.',
[UBUNTU,'Example capacity: 2 vCPUs and 2 GiB RAM. Determine worker and file-descriptor settings through load testing. A working backend at 127.0.0.1:8080 is required.','Use sudo, nginx, curl and DNS for the placeholder app.example.com. Provision a valid certificate chain and private key from organizational PKI at the paths below.'],
'Client → TCP/443 Nginx → loopback HTTP:8080 → application. For multi-host deployments, move the upstream to a private subnet with restricted Firewall access. Do not trust forwarding headers from arbitrary proxies.',
['Check the backend first and preserve existing configuration. Install the package from the operating system repository.',
'The health endpoint must return HTTP 200 and its expected application payload. Before writing configuration, install the certificate chain and private key below; the key must have root ownership and mode 600.',
'Create the symlink only on first installation; inspect its existing destination otherwise. nginx -t must report syntax is ok and test is successful. Point canary DNS or --resolve at the canary VM. Resolve existing default-host or server_name conflicts before reloading.'],
'Do not bind the backend to a public IP. Protect the private key from ordinary users. Permit management traffic and 443 through the Firewall; port 80 is only needed for redirects or ACME. Trial HSTS with a short max-age and no includeSubDomains. Tune rate limits to paths and measured traffic rather than copied values.',
'Expose the Prometheus exporter only to monitoring. Track 5xx rate, upstream latency, handshake failures and certificate age. A 5xx rate above 1% for five minutes is an example threshold, subject to baseline. Grafana should show total and successful requests together, with request IDs in logs.',
['502 indicates failed connectivity or an invalid upstream response; 504 indicates a timeout; 403 points to permissions or policy. Test the upstream directly first.',
'connect() failed with Connection refused identifies a missing backend listener. permission denied may involve a socket or AppArmor; chmod 777 is not a fix. nginx -T can expose sensitive configuration, so record it only in a protected location.'],
'Back up /etc/nginx and certificate secrets with restricted access. Application data and databases need separate backups. For rollback, restore the previous enterprise-app file, run nginx -t and reload. On first deployment, remove only the new symlink and validate the prior configuration. Stop/start is not the normal rollback mechanism.',
'Reload only after syntax checks, health tests and explicit acceptance criteria. Coordinate global worker changes with service limits and benchmark results.',
'This example uses listen 443 ssl for Ubuntu-package compatibility. HTTP/2 syntax differs between Nginx branches. The previous ellipsis-based example is not executable configuration and remains only in historical material.',
[['Does nginx -t verify application health?','No. It validates configuration; application health needs a separate check.'],['Should a 504 be fixed by increasing the timeout?','Inspect upstream latency and dependencies first; a longer timeout can increase queueing.']])

add('ubuntu-date-time-settings','Ubuntu Production Time: Chrony, Offset Monitoring and NTP Troubleshooting',
'Operate Chrony on Ubuntu with approved NTP sources, source selection checks, offset alerts and controlled recovery from clock drift.',
'Clock skew can disrupt Kerberos, TLS, log ordering and replication. A timezone change does not correct the underlying clock; inspect sources, offsets and synchronization separately.',
'Illustrative scenario at fictional Arya: two internal NTP servers use different upstream sources. Application and database servers use them; central logs use UTC timestamps.',
[UBUNTU,HW,'Use sudo, chrony and UDP/123 access to organizational NTP. 10.20.30.53 and .54 are example sources.'],
'Authoritative time → internal NTP → chronyd client → kernel clock → application. Timezones change display; clock changes affect workloads.',
['Record the current state. Only one daemon should own synchronization. Installing chrony normally replaces timesyncd, but verify the resulting service states.',
'Review existing pool/server lines and generated sourcedir entries in /etc/chrony/chrony.conf. Remove conflicting sources only after identifying their ownership. These complete source lines replace public sources with approved internal ones.',
'Expect a source marked ^*, Reach approaching 377 over multiple polls and Leap status: Normal. Reverse DNS may change the displayed source name. Do not run makestep on production with a large offset until its effects on databases and scheduling have been assessed.'],
'An NTP client should not accidentally become a public time server. Restrict egress to approved sources. Where authenticated time is required, design NTS with a supporting server. Two servers with the same upstream dependency do not provide source diversity.',
'Monitor offset, stratum, Reach and source changes. An offset above 100 ms for five minutes is an example alert; sensitive workloads need explicit thresholds. Zabbix or a Prometheus exporter must not treat an active process as evidence of synchronization.',
['^? means a source is not yet usable; inspect UDP connectivity, DNS and the source clock. ^x can identify an inconsistent source.',
'Reach zero with an active daemon means polls are not succeeding. Repeated VM clock jumps require reviewing hypervisor time synchronization and assigning a single owner. Changing timezone does not repair an expired TLS certificate.'],
'This procedure introduces no application data state. Version Chrony configuration, timezone policy and source inventory. Restore prior sources during rollback and inspect tracking. After prolonged downtime, confirm synchronization before starting sensitive workloads. Manually stepping time is not database recovery.',
'Use UTC for logs and local timezones for display. Manual clock changes and NTP-source changes need their own workload assessment and change record.',
'timesyncd remains an option for simple clients; this baseline uses chrony. timedatectl timesync-status reports timesyncd status and does not establish Chrony health.',
[['Does a wrong timezone cause TLS failure?','TLS relies on the actual clock; timezone settings change only its display.'],['Does an active chrony service mean it is synchronized?','No. Check selected sources, offset and Leap status.']])

add('linux-cli-common-commands','Linux Incident Runbook: CPU, Memory, Storage, Services and Networking',
'Diagnose Linux incidents with timestamped evidence, resource checks, service logs and dependency tests before changing production state.',
'Random restarts or log deletion during an incident can destroy evidence. This runbook moves from symptoms to resources and then service dependencies.',
'Illustrative scenario at fictional Arya: Nginx is slow despite low CPU use. Operations checks memory, disks, inodes and upstream services, recording a hypothesis before making changes.',
[UBUNTU,HW,'Use coreutils, procps, iproute2 and curl. Read-only commands normally need no sudo; protected logs require appropriate privileges.'],
'Incident → time and impact → CPU/RAM/IO → service logs → network/DNS → dependency → limited change → validation. Retain timestamped evidence for before-and-after comparisons.',
['These tools are normally installed. Add a missing package from the matching OS repository only when needed. Start with a read-only evidence snapshot.',
'Interpret load against CPU count and IO wait. Low free RAM without considering available memory is not evidence of a crisis. df -i separately reports inode pressure.',
'example.com is a public test destination; substitute the actual endpoint during an incident. curl checks only that endpoint. du -x avoids traversing other filesystems, but can still add load to a busy disk.'],
'Use sudo only for protected information. Environment variables, configuration and process arguments may contain secrets. Restrict chmod/chown to verified paths and owners; broad recursive permission changes are not a general incident fix.',
'Use Prometheus node_exporter for CPU, available memory, filesystems and inodes, with Zabbix for services and reachability. Capacity trends and time-to-full are often more useful than a fixed percentage. Show application latency beside resource metrics in Grafana.',
['A full df result with a small du total can indicate a deleted file still held open or data hidden by a mount. If lsof is installed, these diagnostics identify relevant processes and deleted files.',
'After identifying the PID, use the service-supported log reopen or reload procedure rather than an arbitrary kill. An active service with a failing endpoint suggests dependencies or application configuration. Investigate permission errors with namei -l on the actual path and AppArmor policy.'],
'Diagnostic commands create no service state. Preserve configuration with its ownership before changes; recover application data through that service’s backup procedure. During disk-full incidents, check retention and backups before deleting files.',
'Record timestamps, exit codes and hypothesis outcomes in the incident ticket. Perform read-only checks before reversible changes. Reboot only when supported by evidence.',
'This baseline uses systemd and iproute2. Legacy ifconfig/netstat are not installed everywhere. In containers, /proc and diagnostics may report only the container namespace.',
[['Why can df and du disagree?','Open deleted files, mount layout and traversal scope can account for the difference.'],['Does high load always indicate a CPU bottleneck?','No. Tasks waiting on IO can also increase load.']])
add('downgrade-mikrotik-routeros-firmware-safely','Safe RouterOS Downgrade: Version Checks, Backup and Recovery',
'Plan a RouterOS downgrade around supported device versions, encrypted backups, local recovery access and routing/VPN acceptance tests.',
'A router downgrade can change routing, VPN behavior and configuration syntax. Tie the decision to a specific regression, an allowed target version and service acceptance tests.',
'Illustrative scenario at fictional Arya: a branch tunnel fails after a patch. The team tests the path on CHR, then changes the router in a maintenance window with a local console available.',
[ROS,ROSHW,ROSPERM],
'Inventory → backup/export → architecture and factory-version checks → complete package set → reboot → routing/VPN tests → acceptance. RouterBOOT has a separate lifecycle from RouterOS.',
['Record versions and hardware restrictions first. CHR does not necessarily expose RouterBOARD information.',
'Replace the password placeholder with a unique secret. Download both .backup and .rsc files off the device and protect them. Check factory-software and the minimum installable version. Upload the complete, matching-version package set for the correct architecture from the official download page to the root of Files; remove unrelated old packages.',
'Downgrade reboots the router. After boot, the package version must match the target exactly. Working WinBox access alone is insufficient for acceptance.',
'From the LAN, test DNS, VPN and the branch application. If management does not return within the recorded normal boot time plus its allowance, use the console and recovery plan. Avoid repeated blind reboots.'],
'Do not select a target with a known relevant vulnerability. Binary backups contain secrets: encrypt them and store them off-device. Allow SSH/WinBox only from management networks and obtain packages from the official source.',
'Use restricted Zabbix/SNMP credentials to observe uptime, version, interfaces and tunnels. Link version changes and reboots to the change ticket. Run application probes from both the branch and headquarters.',
['A wrong architecture or a version below the device minimum causes package rejection. Compare resource information, Files and logs. Missing features may require a separate package or different syntax. Do not import an entire newer-version export into an older version without reviewing it.'],
['Keep the previous working version, full package set, encrypted backup, export and device-appropriate Netinstall tools off the router. Restore binary backups to the same device, preferably on their original version. For boot failure, follow the official Netinstall procedure with local access, then validate configuration incrementally.'],
'An OS downgrade is not itself a reason to change RouterBOOT. Reject the change if the tunnel, default route or management access fails acceptance.',
'A v7-to-v6 transition may be unsupported or lose configuration. Check routing syntax and package separation against the device and version. An export does not replace certificates or private keys.',
[['Must RouterBOOT be downgraded too?','No. A bootloader change needs its own documented justification.'],['Does an export recover every secret?','No. Certificates, private keys and other state need separate protection.']])

add('mikrotik-block-port-scanners','MikroTik Firewall: Detect Port Scans Without Blocking Management',
'Deploy scoped TCP scan detection with an approved management allowlist, temporary blocking, counter checks and false-positive review.',
'Scan detection is useful only if it preserves legitimate management access. The psd matcher is a TCP heuristic; default-deny rules and source restrictions remain the primary protection.',
'Illustrative scenario at fictional Arya: security runs authorized scans from 10.20.30.0/24. ether1 belongs to WAN. The input chain protects the router; LAN services need a separate forward policy.',
[ROS,ROSHW,ROSPERM],
'WAN → established/related → management allowlist → psd → temporary list → drop. These rules supplement an existing ruleset; they do not constitute a complete Firewall.',
['Inspect rule order and interface lists first. WAN and mgmt-approved must be defined; the sample allowlist is a lab subnet.',
'Add these rules in Safe Mode. They are appended by default; use WinBox to place them after permitted management traffic and before a general new-connection accept or final drop.',
'Test only with an authorized scanner in staging. Detection/drop counters should rise for a TCP scan without blocking the management subnet. Do not enable unlimited per-packet logging.'],
'Do not trust a management source address that can be spoofed from WAN; edge anti-spoofing matters. Failure to match psd does not authorize traffic. IPv6 needs independent rules. Restrict public management and SNMP access.',
'Monitor CPU, connection count, drop counters and list size. Alert on a scan surge accompanied by load; an isolated scan should not page an operator. Rate-limit logs and forward them through the protected management network.',
['Zero counters suggest rule ordering, WAN membership or traffic traversing forward instead of input. For false positives, inspect shared NAT/scanner behavior and timeout before lowering thresholds. Slow scans and UDP may evade psd; that is a design limitation.'],
['Keep Firewall backups and exports off-device. Roll back only this change’s rules rather than disabling the entire Firewall.',
'Remove an individual list entry only after matching its IP to the incident. Clearing the whole list discards evidence.'],
'Test input, forward and IPv6 independently. Place established traffic before the heuristic and document thresholds and timeouts against false-positive evidence.',
'psd is neither a comprehensive attack detector nor an IDS. FastTrack primarily affects established forward traffic; input results do not establish forward protection.',
[['Does input protect LAN servers?','No. Transit traffic requires a forward policy.'],['Does psd detect every scan?','No. It is a limited heuristic and does not replace default deny or an IDS.']])

add('mikrotik-block-website','MikroTik Web Access Policy: DNS, TLS SNI and HTTPS Limitations',
'Implement a scoped DNS/SNI policy and validate its limits with modern TLS, QUIC, ECH, DoH and managed endpoint controls.',
'IP blocking and string matching are unreliable for CDN-backed sites and modern TLS. A web policy must state its visibility limits and the expected behavior of managed clients.',
'Illustrative scenario at fictional Arya: user-VLAN clients use an internal resolver. example.com is the test target. The router supplies part of the policy; endpoint management governs DoH and VPN bypass.',
[ROS+' Verify type=NXDOMAIN and match-subdomain support using CLI help on the selected patch.',ROSHW,ROSPERM],
'Managed client → organizational resolver → DNS policy; observable TCP TLS → tls-host. QUIC, ECH and VPNs may hide the destination name from the router. A secure web gateway may still be required.',
['Record DNS configuration and Firewall order. Verify LAN/WAN membership. Enable router recursion only where input permits LAN UDP/TCP 53 and blocks WAN access, with these rules placed before the final drop.',
'Use an already approved resolver; do not enable allow-remote-requests without the correct Firewall. Place SNI rules before relevant FastTrack and established accepts. Test fresh connections because existing FastTrack sessions can bypass the rules.',
'Test DNS and TCP TLS independently from a managed Linux client.',
'10.20.30.1 is the router-resolver placeholder. Expect NXDOMAIN from DNS. For the SNI test, resolve through an allowed DNS path so TCP rejection can be measured; DNS failure alone does not prove the matcher works.'],
'Never expose DNS recursion on WAN. Scope enforced DNS to user subnets and approved resolvers, with documented datacenter/VPN exceptions. Avoid blanket CDN IP blocking. Encrypted HTTPS content is not reliably filtered by generic Layer7 rules.',
'Record policy counters, UDP/443 volume, CPU and user impact. Assess application fallback before blocking QUIC. Before-and-after charts should include authorized bypasses and false positives.',
['If a site opens, inspect root/subdomains, caches, DoH, ECH, QUIC, proxies and IPv6 separately. A fragmented ClientHello may not match tls-host. An IP rule may block unrelated CDN services; verify ownership and changing DNS results.'],
['Retain a policy export. Disable only the rules and DNS entries added by this change during rollback.',
'Clear client/resolver caches through the approved procedure and retest the application. Leave unrelated Firewall configuration intact.'],
'Use endpoint management and a secure web gateway where organization-wide enforcement is required. Assign a business owner, documented exceptions and a review date.',
'An address-list entry containing *.example.com is not a general DNS wildcard. Historical content/Layer7 examples do not provide modern HTTPS enforcement. Verify NXDOMAIN and matchers on the exact patch.',
[['Does tls-host block all HTTPS?','No. ECH, QUIC, fragmentation and VPNs limit its visibility.'],['Does one destination IP identify one website?','No. A CDN can share an IP across multiple services.']])

add('mikrotik-openvpn-setup-v7','RouterOS v7 OpenVPN: PKI, Least-Privilege Access and TLS Diagnostics',
'Configure a version-pinned OpenVPN service with individual certificates, matching client settings, return routes and tested forward ACLs.',
'A working tunnel without forward controls can expose more of a datacenter than the client needs. Validate authentication, return routing and service authorization together.',
'Illustrative scenario at fictional Arya: support can reach only SSH on 10.20.30.10. Clients use dedicated certificates, a separate 10.250.0.0/24 pool and split tunneling.',
['RouterOS 7.17 or later with named servers; OpenVPN Community 2.6 on Linux/Windows. Pin the selected patch after staging validation.',ROSHW,ROSPERM+' Use an existing organizational PKI with a CA, a vpn.example.com server certificate with SAN and individual client certificates. Time synchronization and TCP/1194 reachability are required.'],
'Client certificate + PPP user → TCP/1194 → OpenVPN server → pool → forward ACL → server. LAN routing must return 10.250.0.0/24 traffic through this router. NAT does not replace correct return routing.',
['Upload ca.crt and server.p12 from the PKI to Files. Import the private key from a password-protected file; do not keep the CA private key on the edge router.',
'Inspect imported names and replace REPLACE_SERVER_CERT with the actual certificate name. Confirm its private key and valid chain.',
'Place rules before the final drop and before broad LAN accepts. Existing established/related handling must permit responses. This example assumes an already secured Firewall with default deny.',
'Save the complete client.ovpn beside ca.crt, client.crt and client.key. Replace vpn.example.com with the real name covered by the certificate. Protect the client key with a passphrase.',
'On Linux, sudo openvpn --config client.ovpn should report Initialization Sequence Completed. Enter login and key passwords interactively. Test both permitted SSH and denied destinations.'],
'Disable compression. Give each client a separate identity; revoke both certificate and PPP credentials during offboarding. require-client-certificate alone does not bind a certificate to a username. Verify that mapping through policy and negative tests. MFA needs a compatible RADIUS/identity design and is not implemented here.',
'Monitor active PPP sessions, pool utilization, certificate expiry, failed authentication and tunnel logs. Distinguish an individual disconnect from a service outage. An expiry alert below 30 days is an example threshold.',
['For TLS verification failure, inspect time, CA, SAN and key usage. For AUTH_FAILED, check PPP service, password and policy. For SSH timeout on an established tunnel, inspect return routing and forward counters. Match this CBC/SHA256 baseline exactly; do not add GCM without validating compatibility.'],
['Keep an export without secrets, encrypted backups and PKI material in a vault. Test client revocation and CRL behavior on the chosen patch. Rollback disables the named server and ENT-OVPN rules and removes dedicated client routes; one-rule changes need not restore the whole router.'],
'Validate routing, authentication, positive ACLs and negative ACLs in sequence. Allocate a certificate and account per client. The cipher is a compatibility baseline subject to the organization’s cryptographic policy.',
'Versions before 7.17 use different singleton-server syntax. UDP and cipher support vary by version. The historical SHA1/AES-GCM combination was incompatible. The router’s own IP must not be its default-route gateway.',
[['Why can the tunnel connect while SSH fails?','Return routing and forward ACLs are independent of authentication.'],['Do all v7 patches use identical configuration?','No. Named-server configuration changed in 7.17; pin and validate the target patch.']])

add('mikrotik-unequal-dual-wan-load-balancing-ecmp','Weighted Dual-WAN on RouterOS v7: PCC, Return Paths and Failover',
'Build weighted connection distribution with PCC and per-table failover, then verify symmetry, FastTrack exclusions and session limitations.',
'Repeated default routes do not guarantee capacity distribution across 100 and 50 Mbps links. PCC weights connections; each routing table and return path needs a failover test.',
'Illustrative scenario at fictional Arya: LAN is 10.10.10.0/24. WAN1 uses 192.168.30.2/30 with gateway .1, and WAN2 uses 172.30.30.2/30 with gateway .1. Replace these lab addresses with the production IPAM plan.',
[ROS,ROSHW,ROSPERM+' Use a lab without existing policy routing or DNAT. Preconfigure ether1=WAN1, ether2=WAN2 and ether3=LAN with the documented addresses and gateways.'],
'New LAN connection → PCC buckets 0/1 to WAN1 and 2 to WAN2 → connection mark → routing table → srcnat. Inbound replies must use their ingress WAN. This weights connection count, not bytes, and does not combine link speeds for one download.',
['Review the export, routes and FastTrack rules. Exclude marked connections during a canary deployment; an existing FastTrack rule can be temporarily disabled in the lab.',
'Run this on a clean lab with a secured Firewall. Merge with existing production rules and remove duplicate routes/NAT. Add VPN/datacenter subnets to ent-local. Generate hundreds of fresh connections: buckets 0+1 should approach twice bucket 2 in connection count, not necessarily bytes. Disconnect WAN1 in the lab and verify active routes in every table and new-connection success.'],
'NAT is not a Firewall. Deny unsolicited WAN input and permit only approved LAN forwarding. Keep internal traffic out of WAN policy routing. Preserve LAN/console management and test existing DNAT symmetry separately.',
'Measure availability, loss, latency and utilization for each WAN. check-gateway=ping tests only the gateway; it misses upstream failure while the gateway remains alive. Recursive probes or multiple independent targets need separate design and validation.',
['For absent distribution, inspect old connections and FastTrack. For replies leaving the wrong WAN, inspect connection marks and output/prerouting counters. Inactive routes require checking next-hop resolution in main and gateway scope. Pin public-IP-sensitive destinations or evaluate both-addresses classification, then remeasure the weighting.'],
['Keep the pre-change export. Rollback disables ENT-PCC mangle rules, restores previous routes/NAT and disables new routes/NAT. Remove tables only after all references are gone. Do not blindly flush connection state. Public-IP changes can break TCP sessions and require reconnects; failover does not preserve every session.'],
'Distinguish equal-cost ECMP from weighted PCC. One flow does not aggregate two links. Test gateway failure and upstream failure independently.',
'RouterOS v6 route routing-mark syntax differs from v7 routing-table. Repeating gateways is not a dependable weighting design for this baseline. The historical URL is retained while the implementation uses PCC.',
[['Does 2:1 weighting guarantee a 2:1 bandwidth ratio?','No. Weighting applies to connections whose flow sizes differ.'],['Does failover preserve TCP sessions?','A changed public IP can terminate a session and require reconnection.']])
add('windows-cmd-common-network-commands','Windows Network Incident Runbook: DNS, TCP, SMB and Evidence',
'Diagnose Windows connectivity layer by layer, preserve evidence before clearing caches and distinguish TCP reachability from SMB authorization.',
'Successful ping, correct DNS and a reachable TCP service establish different facts. Identify the failing layer before using release/renew or resetting a server network stack.',
'Illustrative scenario at fictional Arya: an application server cannot access files01.corp.example.com over SMB. Test private DNS and TCP/445 from the application subnet to the file server.',
[WIN,WINHW,'CMD and PowerShell are built in. Status reads generally need no Administrator rights. Route/Firewall changes require elevation and an approved change.'],
'Client → DNS → selected route/interface → Firewall → TCP listener → SMB authentication → share/NTFS. The failing stage determines which team owns the correction.',
['Capture evidence in CMD first. The internal domain below is a placeholder.',
'Use PowerShell to test TCP and routing. TcpTestSucceeded: True establishes TCP connectivity, not SMB permissions.',
'Create a unique evidence directory. External programs have their own exit codes.',
'Flush DNS only after comparing suspected stale cache entries with authoritative responses. Repeat the same query and application test afterwards.'],
'Do not include Wi-Fi exports with key=clear in support bundles: they expose secrets. Avoid plaintext net use credentials on the command line; prefer Kerberos with a hostname and the current account. Do not disable the Firewall to troubleshoot.',
'Measure availability and TCP service health separately in Zabbix. Record SMB latency, reconnects and errors. Correlate DNS/network changes with incident timestamps and keep sensitive interface output in restricted tickets.',
['DNS timeout with IP connectivity suggests resolver, port 53 or suffix issues. Failed TCP with successful ping suggests a listener or Firewall/ACL problem. SMB access denied with working TCP points to identity and share/NTFS permissions.',
'Inspect the listener on the file server. An absent listener produces an empty query and a script warning. Unresponsive tracert/pathping hops do not prove application packet loss; routers may rate-limit ICMP.'],
['Diagnostics introduce no service state. Save route/Firewall snapshots before changes and plan rule-specific rollback. ipconfig /release and netsh int ip reset can interrupt management; use them only with console access and a recovery plan. Retain evidence securely.'],
'Test hostname and IP separately. SMB by IP can change Kerberos authentication behavior. netstat/PID output is a snapshot rather than conclusive malware evidence.',
'NetTCPIP cmdlets are available on Windows; PowerShell Core on other operating systems does not provide the same modules. Legacy CMD diagnostics remain useful, while mutations require preflight checks.',
[['Does successful ping prove SMB is healthy?','No. Test TCP/445, authentication and permissions independently.'],['Should DNS cache be cleared first?','No. Record and compare cached and resolver responses before clearing it.']])

add('windows-hardware-info-cmd-vs-dxdiag','Windows Hardware Inventory: CIM, Storage Providers and DxDiag Scope',
'Collect timestamped Windows inventory, distinguish VM abstractions from physical hardware and validate capacity against CMDB and vendor telemetry.',
'A screenshot is insufficient for capacity decisions. Collect comparable, timestamped inventory and distinguish physical hardware from virtual-machine representations.',
'Illustrative scenario at fictional Arya: before a fleet upgrade, operations compares BIOS, cores and RAM with organizational inventory. A VM serial number need not identify the physical chassis.',
[WIN,WINHW,'Use x64 PowerShell, CimCmdlets and Storage. Local reads usually need standard access; remote collection needs delegated permissions and protected WinRM. DxDiag applies to Desktop Experience.'],
'CIM/Storage providers → JSON snapshot → CMDB → baseline comparison. DxDiag targets client graphics/DirectX issues; verify professional GPU capacity using vendor tools.',
['Run the complete read-only script in x64 Windows PowerShell 5.1. It writes to the user TEMP directory; substitute an approved location if policy requires it.',
'JSON includes a UTC timestamp and named objects. Capacity and Size are bytes; divide by PowerShell 1GB for GiB. Verify model and serial against CMDB/vendor consoles. Run DxDiag only where the GUI/binary exists and the report directory is writable.'],
'Serial numbers, hostnames and inventory reveal organizational topology. Restrict report access. Remote CIM requires an approved least-privilege session and WinRM TLS/Kerberos; do not enable Basic without TLS.',
'Alert on unauthorized RAM/BIOS changes and disk health rather than every inventory snapshot. Use Zabbix for health and CMDB for ownership. Healthy HealthStatus is not complete SMART or RAID-controller evidence.',
['Null CIM values in a VM may reflect provider limitations; distinguish Unknown from actual zero. Get-PhysicalDisk can abstract disks behind RAID, so consult controller telemetry. Missing DxDiag on Server Core is not an inventory failure. Remote access denied calls for session/permission checks, not Firewall removal.'],
['Inventory does not change service state. Retain JSON and hashes according to policy. Hardware recovery also needs firmware, drivers, RAID configuration and application backups; a serial number is not a restore procedure.'],
'Use CIM for automation and vendor tools for specialized telemetry. Do not size modern GPUs from the low-precision AdapterRAM property.',
'WMIC is deprecated; its presence on one host does not establish fleet availability. This script uses CIM. Server Core and graphical workstations have different scopes.',
[['Is DxDiag appropriate for every server?','No. It targets graphics/DirectX and may be absent on Server Core.'],['Does Healthy HealthStatus guarantee RAID health?','No. Inspect controller telemetry and vendor tools as well.']])

add('windows-password-reset-secure-access-recovery','Secure Windows Account Recovery: Identity, Delegation and Audit',
'Reset authorized human accounts after verifying identity and dependencies, with delegated rights, secure secret delivery and audited recovery.',
'Resetting the wrong account can disrupt services, scheduled tasks or EFS access. Establish identity type, dependencies and auditing before changing a password.',
'Illustrative scenario at fictional Arya: a human user has forgotten their password. Helpdesk has delegation only on the staff OU; service accounts and Domain Admins are outside this procedure.',
[WIN,WINHW,'Local recovery requires x64 Microsoft.PowerShell.LocalAccounts. AD recovery requires RSAT ActiveDirectory and Reset Password rights on the target OU. Verify the request and user identity first.'],
'Identity verification → account type → delegation → dependency check → reset → login validation → audit. Microsoft Account, Entra, AD and local identities have separate recovery paths. BitLocker uses an independent key.',
['Inspect the human AD account from an approved RSAT workstation. ops.user is a placeholder; match its account and OU to the request before resetting.',
'A successful cmdlet usually has no output. Forced password change can make PasswordLastSet zero or special-valued. The user must log on from a domain workstation with DC connectivity and change the password. Unlock only after confirming lockout and resolving stale credentials.',
'For a human local account, use this separate elevated PowerShell procedure on the target device.',
'local.ops is a placeholder. Recover/rotate Windows LAPS-managed accounts through the organizational LAPS workflow so manual changes do not conflict with its lifecycle.'],
'Never record secrets in transcripts, history or tickets. Assess EFS, certificate private-key and DPAPI credential risks before local resets. Service accounts need gMSA or their own rotation workflow. Release BitLocker recovery keys only after verifying device and key ID.',
'With appropriate Advanced Audit Policy, send Security events such as 4724 and 4740 to the SIEM. Missing events may reflect audit configuration rather than absence of changes. Route sensitive-account reset alerts to IAM.',
['Access denied suggests delegation/elevation; password-policy errors require complexity/history and fine-grained-policy checks. Recurring lockouts often indicate a service/task using old credentials. For unreachable DCs, inspect DNS and the secure channel rather than repeatedly resetting. A Windows Hello PIN is not the account password.'],
['The previous password cannot be rolled back. Deliver the new secret securely and repeat authorized rotation if necessary. Pre-protect EFS recovery certificates, BitLocker keys and break-glass identities. AD system-state recovery is not a single-user reset procedure.'],
'Record request ID, operator, account and timestamp, never the password. State identity verification and delegated permissions explicitly in the Helpdesk runbook.',
'Use provider recovery for Microsoft Account and Entra. Set-ADAccountPassword applies to AD DS only. A password-reset disk applies to local accounts and must exist before the incident.',
[['Does a password reset replace a BitLocker key?','No. BitLocker recovery keys are independent.'],['Can the previous password be rolled back?','No. Set another new credential through the authorized workflow if necessary.']])

add('install-mikrotik-chr-vmware-workstation','MikroTik CHR Lab on VMware Workstation: Isolation and Validation',
'Build an isolated CHR lab with explicit VMnet mapping, restricted management, license-aware measurements and recoverable test configuration.',
'An incorrectly bridged lab can inject test DHCP or routing into the company network. Deploy CHR with explicit VMnet mapping and restricted management access.',
'Illustrative scenario at fictional Arya: a NAT VMnet supplies WAN and a separate Host-only network supplies LAN. The team validates branch exports and Firewall behavior before an upgrade.',
['RouterOS CHR v7 and a licensed Workstation build supported on the host. Record exact router patch and Workstation build.','Lab recommendation: 2 vCPU, 1 GiB RAM, at least 1 GiB disk and two vNICs for CHR. Throughput depends on the host and license.','Official MikroTik VMDK, Virtual Network Editor and administrator rights for VMnet creation. Use the initial console and organizational password/license policies.'],
'NAT VMnet → CHR ether1; Host-only with VMware DHCP disabled → CHR ether2 → client VM. Map management and test networks by name and MAC in inventory.',
['Download the official CHR VMDK and verify its published checksum. Record filename/hash. Create a VM using the existing virtual disk and confirm NIC mapping from its first-boot console.',
'The lab WAN is 192.168.100.10/24, gateway 192.168.100.2; match these to the actual NAT VMnet. LAN is 10.99.0.1/24.',
'This ruleset targets a clean IPv4 lab. Restrict IPv6 separately. The gateway should respond and a LAN client using 10.99.0.1 should traverse allowed paths. SSH/WinBox must not be reachable from the new WAN.'],
'Do not bridge test VMnets to a company NIC. Set a unique admin secret and disable unused services. Protect the host console with access controls/MFA; snapshots contain credentials.',
'Record host/VM CPU, dropped packets and interface counters. The Free license limits throughput; document the license with every benchmark.',
['Missing IP requires checking vNIC mapping, connection-at-power-on and VMnet subnet. Gateway timeout suggests MAC/VMnet or host Firewall. Limited speed requires both license and host-load checks. Never point the default route to CHR’s own address.'],
['Take a labeled pre-test snapshot and export configuration outside the VM. A snapshot is not an independent backup. Review clone/license/system-ID recovery against CHR documentation. Never run duplicate-IP clones simultaneously.'],
'Use this lab to validate syntax and behavior. Production dataplanes require supported hypervisors and workload-based sizing.',
'Free licenses limit upload to 1 Mbps per interface; P1/P10/P-Unlimited have different conditions. A desktop Workstation baseline is not an HA design.',
[['Can a Workstation lab replace a production router?','No. It validates configuration; HA, support and capacity require separate design.'],['Why is throughput low?','Check both the CHR license tier and host resources.']])
add('install-vmware-esxi-vmware-workstation-vmcisr','Nested ESXi on VMware Workstation: Deployment and VMCI Diagnostics',
'Validate nested ESXi in an isolated lab and investigate VMCI errors using exact build information, logs and vendor compatibility guidance.',
'Nested ESXi is useful for migration/API rehearsal, but does not establish bare-metal performance or support. Diagnose VMCI failures from logs and build compatibility.',
'Illustrative scenario at fictional Arya: before changing a vSwitch, the team builds a nested ESXi host and two test VMs. Management is isolated from the company LAN.',
['ESXi 8.x with an authorized ISO and a Workstation build compatible with the host OS. Record exact versions and the applicable error KB before changes.','Suggested lab host: 32 GiB RAM, VT-x/EPT or AMD-V/RVI CPU and SSD. Allocate 4 vCPU, 8 GiB RAM, a suitable boot disk and separate datastore to nested ESXi. These are not performance guarantees.','Enable firmware virtualization; provide administrative Workstation/console access and separate Host-only/NAT networks. Use valid software licenses.'],
'Physical CPU → Workstation virtualization engine → nested ESXi → nested VM. Nested workloads cannot boot if the host hypervisor does not expose their required features.',
['Record Workstation and OS versions. Enable firmware virtualization and select Virtualize Intel VT-x/EPT or AMD-V/RVI in VM Settings.',
'Create a VM with the appropriate VMware ESXi guest type and a supported adapter for that build. Attach the official ISO and install to a verified dedicated disk.',
'Configure management IP, DNS and hostname through DCUI. The sample 10.99.0.11/24 belongs to Host-only and must match VMnet. Use F2 → Configure Management Network → Test Management Network.',
'From the workstation, test TCP connectivity and then Host Client.',
'Expect TcpTestSucceeded: True, then open https://10.99.0.11/. Verify the lab certificate fingerprint against the console. Create a small nested VM and validate boot, networking and storage; Host Client alone is insufficient.'],
'Keep management off the public Internet and use separate lab credentials. Do not disable host VBS, Hyper-V or Secure Boot for a workaround without assessing its security impact and build support.',
'Record host resources, guest ballooning/swapping, datastore latency and Workstation logs. Separate lab alerts from production. Lab oversubscription is not evidence of a production architecture defect.',
['For Module VMCISr power on failed, inspect this VM’s vmware.log, devices and exact-build KB. Removing vmci0 or editing VMX is not a version-independent fix. For unavailable VT-x, check firmware, nested-feature exposure and the active host engine. For missing NICs, check adapter/image compatibility rather than injecting arbitrary drivers.'],
['Back up the powered-off VM, configuration/VMX and host configuration export. A snapshot is useful before tests but does not replace in-guest backups for stateful nested workloads. Roll back VMX workarounds only while powered off, using the recorded version.'],
'Document lab and production scope. Record exact errors/builds in support tickets and apply workarounds only to KB-covered versions.',
'Broadcom documents nested ESXi support restrictions. Successful Workstation installation does not establish production support. VMCISr is a symptom with multiple possible causes.',
[['Is nested ESXi on Workstation supported for production?','Check the vendor support matrix; this procedure covers a lab only.'],['Does deleting a device always fix VMCI failures?','No. Establish the cause using logs and the build-specific KB.']])

add('vmware-esxi-8-installation-basic-configuration','ESXi 8 Deployment: Hardware Compatibility and Production Acceptance',
'Prepare an ESXi host with verified hardware/firmware, management networking, DNS, time synchronization, monitoring and independent recovery access.',
'An installed hypervisor is not service-ready until hardware compatibility and management networking are verified. Validate firmware, DNS, NTP, uplinks and recovery before workloads arrive.',
'Illustrative scenario at fictional Arya: a new host joins a cluster with no workloads yet. Management VLAN30 has two uplinks and an independent console.',
['Supported ESXi 8.x patch with an approved OEM image and compatible vCenter. Check firmware/drivers in the Compatibility Guide.','CPU, NIC, controller and boot device must match the HCL for the build. The example uses two management uplinks and independent storage; size workloads through capacity planning.','Authorized console/iLO/iDRAC, installation credentials, license, forward/reverse DNS, NTP and prepared VLANs. Installation overwrites data on the selected disk.'],
'OOB console → ESXi boot device; management vmk → vSS/vDS uplinks → switch VLAN; separate datastore → VM. Document storage and management failure domains.',
['Match CPU/NIC/controller and firmware to the target build/OEM image. Record the ISO hash and verify the boot device by its serial.',
'Install on the designated boot device after identifying existing datastores and data-bearing disks. Use DCUI for first boot.',
'In F2 → Configure Management Network, select management NICs, the switch-compatible VLAN ID, static IP and DNS. Test gateway/DNS. Sample IP is 10.20.30.11/24 with gateway 10.20.30.1.',
'Open Host Client with the registered hostname and a valid certificate. Enable SSH temporarily for the change window only. Run these read-only ESXi Shell commands.',
'Expect the target build, correct management IP and both uplinks as designed. Configure DNS/NTP and check start policy. Join vCenter, deploy a canary VM and validate networking, datastore and a test workload restart.'],
'Restrict the management subnet, use named vCenter administrators and least privilege, and close Shell/SSH after changes. Enable Lockdown Mode only after testing exceptions and OOB recovery. Use organizational PKI and a protected syslog destination.',
'Use vCenter alarms for uplink, datastore, hardware-sensor and disconnect events. Give Zabbix restricted vCenter API access. Observe NTP, storage latency and boot-device usage; low CPU alone is not health.',
['For lost management, use OOB/DCUI and inspect VLAN/vmnic mapping. Missing NICs require OEM-image and HCL driver/firmware checks. Missing datastores require path/controller investigation, not reformatting.',
'Align VMkernel and physical-switch tagging on trunks; double tagging can sever access. Resolve certificate errors through DNS names and chains rather than globally bypassing validation.'],
['Create a configuration bundle in a temporary ESXi Shell session. Download its returned URL from an approved workstation, then close the Shell.',
'This bundle contains configuration, not VM/datastore backups. Restore has build/UUID requirements; use the vendor KB on a replacement host in maintenance. Keep images, license, VLAN records and recovery credentials outside the host.'],
'Accept a canary before workloads. Stage patches and keep firmware/drivers aligned. Do not choose historical USB/SD boot media without checking the target build’s storage requirements.',
'This baseline is ESXi 8. Recheck lifecycle, support and entitlement before deployment. Nested Workstation tests cannot validate hardware compatibility.',
[['Does a configuration backup include VMs?','No. VMs and datastores need separate backups.'],['Is a detected NIC necessarily supported?','No. Match model, driver, firmware and build to the compatibility matrix.']])

add('vsphere-standard-switch-vs-distributed-switch','vSS to vDS Migration: Uplink Staging and Management Recovery',
'Choose vSphere switching architecture and migrate a canary host incrementally while retaining an independently tested management rollback path.',
'Moving vmk0 and every uplink at once can disconnect both the host and vCenter. Choose vDS together with staged migration and a tested recovery path.',
'Illustrative scenario at fictional Arya: port-group policy has drifted across a six-host cluster. The team migrates to vDS while preserving a vSS uplink on the canary host.',
['vSphere/ESXi 8.x. Confirm compatible vCenter builds and entitlement for vDS/features before design.','Two independent uplinks for this migration example, with consistent physical trunks and MTU. Retain one management uplink on vSS until validation.','vCenter Network configuration permissions and OOB access to each host. LACP requires compatible vDS/physical-switch support and explicit design.'],
'vSS stores local configuration per host. vDS uses vCenter-managed control plane and host dataplanes. A vCenter outage does not necessarily stop existing forwarding, but constrains changes and recovery.',
['Inventory each host’s vSS, port groups, VLANs, MTU, vmk interfaces and uplinks. Run these read-only ESXi Shell checks.',
'Create a vDS compatible with the oldest host. Define management, VM and vMotion distributed port groups with exact VLAN/MTU values. Align security and teaming with the baseline.',
'Move only the canary’s second uplink to vDS and place a test VM on the destination port group. Check VLAN, DNS and application reachability.',
'With OOB ready, migrate management vmk through Add and Manage Hosts. Retain the original vSS uplink until management is accepted. Test the gateway using the actual vmk.',
'vmk0 and the gateway are design placeholders. Test larger MTU end to end with an appropriate DF probe. Move the remaining uplink only after host/vCenter access stabilizes; do not change a second host before accepting the canary.'],
'Enable promiscuous mode, MAC changes or forged transmits only for documented workload needs. Separate network roles from general Administrator access and protect vDS backups/console credentials.',
'Alert on host disconnects, uplink failures, VLAN/MTU drift and packet drops. Collect LACP state and physical-switch errors from networking. LLDP/CDP use depends on topology-disclosure policy.',
['A disconnected VM with healthy vmk suggests VLAN, dvPort or VM policy. For host disconnect, inspect uplink mapping and management VLAN through OOB. Single-host problems suggest trunk/baseline drift. An MTU mismatch may pass small packets while breaking storage or vMotion.'],
['Export vDS/host configuration and back up vCenter before migration. For lost management, use vendor-documented DCUI/OOB network recovery to return vmk to a known vSS/port group. Supply local operators with previous uplink/VLAN names. vCenter must not be the sole recovery path.'],
'Change one host and one uplink at a time. Prove rollback before removing the final vSS uplink. LACP alone does not guarantee application redundancy.',
'vSS supports VLANs and NIC teaming; vDS adds centralized features. Verify LACP/NIOC availability against edition and current contract.',
[['Does a vCenter outage stop all vDS traffic?','Existing host dataplanes generally continue; management and recovery are constrained.'],['Why not move all uplinks together?','The retained vSS uplink preserves management and rollback while the new path is validated.']])

add('netbox-installation-setup-ubuntu','NetBox 4.7.2 on Ubuntu: Secure Deployment, API Access and Restore',
'Deploy a pinned NetBox baseline with PostgreSQL, Redis and TLS, then test least-privilege API access, worker health and isolated recovery.',
'NetBox is a network source of truth. Database loss or excessive API permissions can disrupt inventory and automation. Installation must include identity policy and a testable restore.',
'Illustrative scenario at fictional Arya: networking records three datacenters, VLANs and prefixes. Automation receives read access; inventory-owner groups control writes.',
['Baseline: Ubuntu Server 24.04 LTS, NetBox 4.7.2, Python 3.12, PostgreSQL 16 and Redis 7. Pin patches/plugins after staging tests.','Example capacity: 4 vCPU, 8 GiB RAM, 60 GiB SSD. Measure database/media growth, object count and job load. This single node is not a complete HA implementation.','sudo, git, apt, dedicated PostgreSQL identity, DNS and PKI for the real hostname replacing netbox.example.com. Generate fresh SECRET_KEY and pepper values.'],
'HTTPS/Nginx → loopback Gunicorn → Django/NetBox → PostgreSQL. netbox-rq uses Redis tasks; cache and queue are separate. Protect DB, media, configuration and secrets together.',
['Use a fresh VM with local DB. Install dependencies and record versions first; this does not perform an automatic full OS upgrade.',
'The password command prompts interactively; reuse that value in configuration. createuser/createdb are for a fresh installation only. Keep Redis on loopback. Generate the complete configuration with Python, entering the DB password at its prompt and replacing the sample hostname first.',
'Checks must pass without errors and services must be active. Contrib Gunicorn normally binds 127.0.0.1:8001; inspect its file and ss. Write this complete Nginx configuration with the real hostname/certificate; static alias must reference the same checkout.',
'Save as sites-available/netbox, create the initial symlink, run nginx -t and reload. Certificates must exist before testing. Test curl --fail https://netbox.example.com/login/, login and API reads with a restricted token. Create a sample site/prefix in UI and verify read-only write denial.'],
'Do not bind PostgreSQL/Redis to WAN. Allow organizational HTTPS and management SSH only. Preserve SECRET_KEY/API_TOKEN_PEPPERS in encrypted backups; unplanned rotation can invalidate credentials. Use object permissions, token expiry, SSO/MFA and separate superusers.',
'Monitor login/API probes, worker state, queue age, DB connections, disk and certificate expiry. Restrict metrics endpoints to monitoring. Active Nginx does not establish job completion.',
['For 502, inspect Gunicorn bind/service logs. DisallowedHost requires the real ALLOWED_HOSTS. CSRF 403 requires checking trusted origin and forwarded protocol. Pending jobs require Redis tasks/netbox-rq checks.',
'Do not publish secret-bearing configuration in public tickets. After upgrades, investigate plugin compatibility/release notes; deleting migration history is not a repair.'],
['For a sample 24-hour RPO, use daily database/media/config backups and off-host copies. If media/config are changing, run this export in maintenance without writers. Design PostgreSQL PITR for shorter RPO.',
'Redirection occurs inside the root shell; sudo pg_dump followed by shell redirection alone cannot write a protected path. Transfer the backup to a vault/off-host and record hashes. Restore on an isolated server with matching version/plugins, never the primary DB.',
'Point restore configuration at netbox_restore, restore SECRET_KEY/pepper/media, and disable outgoing automation/webhooks. Validate login, object counts, API and a canary job; measure RTO. Code-only downgrade after migrations is invalid.'],
'Lock versions/plugins, stage migrations, back up before upgrades and test restore. NetBox is neither discovery nor an NMS; inventory needs accountable owners.',
'4.7.2 is this guide’s baseline, not a guarantee for future patches. Python-package installation is experimental in 4.7; use Git/archive here. Match legacy API tokens and newer Bearer usage to the token version.',
[['Is a PostgreSQL backup enough?','No. Retain media, configuration, secret key, pepper and plugin versions.'],['Can code simply be downgraded after a migration?','No. Rollback must account for schema compatibility and the pre-change database backup.']])

add('oxidized-network-device-configuration-backup','Oxidized Network Backups: Versioned Configuration and Restore Tests',
'Deploy Oxidized with restricted device credentials, bare Git output, per-node freshness monitoring and model-specific recovery drills.',
'A configuration file does not prove network recoverability. Record changes, alert on collection failures and test selective restore against actual device models.',
'Illustrative scenario at fictional Arya: 120 switches/routers are polled hourly. Monitor each node’s last successful backup independently of process health.',
[UBUNTU+' Use Oxidized 0.37.0 with Ruby 3.2 on Ubuntu 24.04 from RubyGems, with the application version pinned by --version. Record resolved dependencies in an organizational artifact before production rollout. Validate device models against their firmware.','Suggested 2 vCPU, 4 GiB RAM and disk sized for history. Choose thread count from device latency and AAA load.','Ruby/Bundler and build dependencies; a non-login service identity, vault-provided read credentials and TCP/22 to device management only.'],
'Device SSH → model parser → normalized configuration → bare Git → encrypted off-host copy. Secret removal can limit recovery; credentials and native binary backups need separate protection.',
['This lab example uses a fresh VM. Check executable location with command -v, install the approved gem and record actual versions.',
'Pin the observed version and preserve its artifact before production rollout. Store complete config at /var/lib/oxidized/.config/oxidized/config with mode 600; replace credentials with vault secrets.',
'The sample router.db line is core-sw01.corp.example.com:ios. Verify DNS/SSH fingerprints through a trusted path and negatively test secure/strict-verification behavior for this input version. Permit model-required commands without assigning privilege 15 by default.',
'This is a foreground test. Substitute the actual executable path. Stop it after a successful poll, then install the unit with that same path.',
'Git output is commonly bare: cat on a working-tree path is inappropriate. Inspect ls-tree, then git show HEAD:node-name. Match successful logs to an actually collected node.'],
'Do not expose optional UI/REST publicly; use an authenticated reverse proxy. Git history can retain previously removed secrets, so encrypt/restrict it. Evaluate read-only RouterOS/SwOS model access separately and avoid shared credentials across device groups.',
'Observe per-node last-success time, duration and failure counts. Send sensitive ACL/routing changes for ticket review, not automatic execution. Staleness beyond two intervals is an example threshold; systemd active is insufficient.',
['Failed nodes require DNS/SSH/AAA and firmware-model checks. Bare repos have no working tree; use git show. Repo permission failures require checking service ownership/UMask. For changed host keys, verify fingerprints at the console rather than disabling checks. Incomplete output suggests command authorization or parser issues.'],
['Encrypt and copy the repo, config, node inventory and credential references off-host. Extract a known commit and review diff/syntax on a matching spare model/firmware. Interface/IP changes can break management. Exports omit some keys, licenses and binary state; retain vendor-native backups too.'],
'Require actual-model restore drills, dependency manifests and restricted privilege. Raw NetBox API responses need conversion to Oxidized source format; their schemas differ.',
'SwOS, RouterOS and IOS models/transports differ. 0.37.0 is the baseline; lock transitive dependencies in organizational artifacts as well.',
[['Why is there no config file to cat in the Git repository?','The output can be bare. Use git ls-tree and git show to read its objects.'],['Does an export fully restore a device?','No. Secrets, certificates, licenses and binary state may need separate backups.']])

add('install-dfs-server-windows-server','Windows Server DFS: Namespace, Replication and Recoverable File Services',
'Deploy domain-based DFS-N and DFS-R with reviewed permissions, initial-sync acceptance, backlog monitoring and independent file backups.',
'Namespace provides a stable path; Replication copies files. Neither is a backup. Deletions and overwrites can propagate to other members.',
'Illustrative scenario at fictional Arya: two branches use Company/Data. FS01 supplies initial content to FS02. Users must not write to FS02 before initial synchronization finishes.',
['Windows Server 2022/2025 joined to AD DS with DFSN/DFSR PowerShell modules. Replicated content uses NTFS; DFS-R does not support ReFS.','Two file servers with separate storage. Size staging from the largest files and allow space for conflict/deleted content; inventory determines capacity.','Role-installation rights on both servers and delegated AD namespace/replication access. Prepare SMB/NTFS. The example assumes corp.example.com, FS01/FS02 and existing D: volumes.'],
'Client → AD referral/DFS-N → SMB target. Separately, DFS-R replicates closed files between members. Multi-master replication does not provide cross-site file locking.',
['Prepare roles and paths on both file servers. D: must be suitable NTFS storage. CORP FileUsers represents the actual organizational group.',
'Design/apply NTFS ACLs with the data owner; share permissions do not grant NTFS access. Continue from a management host with modules and delegation.',
'Add-DfsrConnection creates the reverse connection by default; inspect Get-DfsrConnection. Do not repeat creation on existing deployments. AD propagation/initial sync takes time. PrimaryMember selects the initial source only. FS02 starts Offline so clients receive no referrals before acceptance; also restrict direct user access to its share during initial sync. Accept only after a closed canary file reaches FS02 with the same hash and both backlogs reach zero. Run the following commands to bring that target Online only after these checks pass.'],
'Scope SMB and RPC/DFSR to members and consumer subnets using official Windows Firewall guidance. Coordinate dynamic RPC ranges with policy. Review share/NTFS ACLs, SMB signing and access audit. End users should not write to the namespace root.',
'Monitor both backlog directions, DFS Replication logs, staging pressure, disk space and conflict/deleted content. Short backlogs can be normal; sustained growth matters. Specify the monitoring account context for Zabbix checks.',
['A healthy namespace with old files calls for separate DFS-R/backlog investigation. Run these diagnostics from a module-equipped host.',
'The backlog cmdlet displays a limited list; inspect verbose output for the full count. Open files/databases may not replicate. Inspect events for staging/content-freshness issues. Do not delete the DFS-R database as a generic fix.'],
['Use independent VSS-aware file and AD/namespace backups with off-site/immutable copies. Control overwrite propagation during restore: recover to an isolated path, compare ACL/hash, then return selected files through a change record. Rebuild failed members and use documented non-authoritative sync. Do not mark both members primary. RPO depends on actual backups, not DFS-R speed.'],
'Use DFS-R for closed files and compatible workflows. Live databases, active VM disks and cross-branch locking workloads are unsuitable here. Accept initial sync before sending user referrals.',
'DFS-N and DFS-R are separate roles. This is a domain-based namespace; standalone HA differs. Replicated volumes use NTFS in this baseline.',
[['Is DFS-R a backup replacement?','No. Deletes/overwrites can replicate; independent backups remain necessary.'],['Is PrimaryMember a permanent leader?','No. It selects the initial-sync source; normal replication is multi-master.']])
add('sql-server-automatic-backup-job','SQL Server Backup Operations: Agent Jobs, Retention and Restore Validation',
'Operate SQL Server FULL, DIFF and LOG backups with database-level freshness checks, protected retention chains and isolated restore drills.',
'A green Agent Job does not prove every database has a usable backup. RPO/RTO depend on database coverage and restoring the full chain within the required time.',
'Illustrative scenario at fictional Arya: Jira and Confluence use whitelisted databases. SQL backups must be coordinated with application files and home directories; the database alone is not a full application backup.',
['SQL Server 2019/2022 with SQL Server Agent on Windows Server and PowerShell 5.1. Check compression/encryption against edition/build.','Separate backup storage from data/log, size for FULL/DIFF/LOG and off-host copies, and measure actual restore throughput.','DBA backup/restore rights and a restricted Agent proxy for file operations. SQLBackupFiles and the whitelist are implemented in the retained executable sections.'],
'Whitelist → FULL/DIFF/LOG jobs → checksum/audit → encrypted off-host copy → restore drill. VERIFYONLY checks backup readability; it does not replace application validation or CHECKDB.',
['The retained implementation below includes the complete procedure, folder-provisioning PowerShell, three Agent Jobs, cleanup and audit. Save the named scripts, provision whitelist/proxy and manually validate disabled jobs first. Express has no Agent and needs a separately designed scheduler workflow.',
'Read source recovery models and log-reuse state. This query changes no recovery model.',
'Expect fresh FULL/DIFF/LOG according to each database’s schedule. Alert on NULL/stale backups. After SIMPLE-to-FULL, a suitable full or differential is needed to establish the log chain. Enable log backup only after checking that chain. The restore example recovers a standalone FULL on a test instance.'],
'Back up encryption certificates/private keys outside the instance with strong passwords. Grant the service account only required backup-path permissions. Do not enable xp_cmdshell for file operations. Isolate restore systems from production users and outbound integrations.',
'Monitor each database’s latest FULL/DIFF/LOG, audit failures, disk and duration. Existing queries identify missing/stale backups; Agent-level success alone is insufficient. Test actual alert delivery through Database Mail/operators or independent monitoring.',
['OS error 5 requires ACL checks from the SQL service identity, not the SSMS user. Error 3201 requires a server-side file/share path. Unavailable log backup requires model/chain checks. Log gaps require FirstLSN/LastLSN and base-FULL inspection; repeated VERIFYONLY cannot repair a missing chain.'],
['This complete standalone-FULL restore targets an isolated instance. Replace filenames/logical names using actual FILELISTONLY output. D:/RestoreLab must already exist with SQL service permissions.',
'Run this batch only after reviewing output and confirming no same-name database exists. Add MOVE for every additional file when the backup contains more than one data/log file.',
'This is FULL-only, not PITR. For PITR, apply compatible FULL/DIFF with NORECOVERY, then every contiguous LOG through the target STOPAT and RECOVERY as explained in the main implementation. Accept only clean CHECKDB, approved application queries and measured RTO. Import required encryption/TDE certificates and keys securely before restore.'],
'Clean up only after proving retention preserves a valid base and its entire required chain. This small-scale whitelist implementation is retained; large fleets need an organizational solution covering their editions.',
'A newer-engine backup cannot restore to an older SQL engine. Express lacks Agent. The existing scripts and eight-question FAQ are retained.',
[['Does VERIFYONLY replace an actual restore?','No. Restore on an isolated instance, run CHECKDB and validate the application.'],['Is a green Agent Job enough?','No. Check freshness and backup status independently for every database.']])

add('creating-a-bootable-usb','Enterprise Boot Media: Trusted Images, Firmware Compatibility and Recovery Tests',
'Prepare verified boot media with recorded image hashes, correct firmware settings, controlled device selection and spare-server boot acceptance.',
'Bad media or an untrusted ISO can consume the recovery window. Record image provenance, hash, firmware mode and a successful boot test.',
'Illustrative scenario at fictional Arya: datacenter staff prepare spare-server media before failure. Labels record OS, build, hash and the boot-test date.',
['Official Ubuntu 24.04 LTS or Windows Server 2022/2025 ISO; approved stable Rufus on Windows 11. A Windows client Media Creation Tool is not a Server ISO substitute.','USB capacity compatible with the image/firmware; 16 GiB is an example. Use a prepared workstation and spare server, verifying target controller/NIC models first.','Workstation administrator for writing, authorized boot/OOB access, official published hashes and a backup of USB data. Selecting the write target is destructive.'],
'Vendor ISO → signature/checksum trust → media writer → firmware boot → installer/recovery. Installation media is not an application-data backup.',
['Obtain the image and checksum from trusted official channels. Hash calculation is read-only; substitute the actual existing file path.',
'Match the hash exactly to the publisher. A self-generated hash detects later changes but does not establish source trust.',
'In Rufus, identify the USB by actual serial/size, select ISO and check target firmware mode. UEFI generally uses GPT; choose ISO/DD mode per distribution guidance. Use the official Server image/process for Windows Server.',
'Before Start, have a second operator or approved change control verify the device. All USB data is erased. After completion/eject, use the spare server’s temporary boot menu.',
'Keep Secure Boot enabled where the image/chain supports it. Accept only after reaching the installer, recognizing storage/NICs and accessing a test backup from recovery. Do not install to a production disk during this test.'],
'Control ISO/media custody. Do not place passwords or unattended secrets on shared USB media. Sensitive server boot requires OOB controls/audit; disabling Secure Boot is not the default.',
'No persistent service is introduced. Record media inventory, last boot test and recalls in CMDB. Installation USBs do not require a Zabbix service check; manage image review/expiry through asset policy.',
['If USB is absent from the menu, inspect port, firmware mode and media. Missing storage requires OEM drivers/controller mode/HCL checks, not formatting. For Secure Boot violations, check signature/image compatibility and vendor documentation. For large Windows files on FAT32, use an approved writer/image workflow rather than arbitrary partition conversion.'],
['Media can be rebuilt from an approved ISO, checksum, writer version and settings stored as artifacts. Actual recovery also needs workload backups, encryption keys and valid drivers. Test recovery-environment backup access before an incident.'],
'Boot-test on a spare of the target model. Recovery media, installation media and data backup are separate artifacts.',
'Use Legacy BIOS/MBR only for an actual legacy requirement. A client Media Creation Tool is not the Windows Server download process; retain vendor ISO handling.',
[['Is installation USB a server backup?','No. It supplies installation/recovery tools; application data needs separate backup.'],['Must Secure Boot be disabled?','Only for a documented incompatibility and an approved decision; keep it enabled when compatible.']])

add('http-vs-https-ssl-certificate-impact','Production HTTPS: Certificate Lifecycle, Trust Chains and HSTS Recovery',
'Validate HTTPS through real client paths, manage certificate renewal and stage HSTS with explicit compatibility and recovery requirements.',
'Expired certificates or incomplete chains can interrupt APIs and automation together. HTTPS identity verification depends on the certificate lifecycle as well as encryption.',
'Illustrative scenario at fictional Arya: an API sits behind a TLS proxy. Browsers and Linux jobs use different trust stores. Rollout starts with canary clients and a short HSTS policy.',
[UBUNTU+' Use repository OpenSSL 3.x, curl and Nginx. Require at least TLS 1.2 and enable TLS 1.3 according to client policy.',HW,'Actual DNS replacing app.example.com, a trusted internal/public CA, SAN certificate, full chain and restricted private key. sudo is required only for proxy configuration.'],
'DNS/SNI → TLS handshake → chain/hostname verification → HTTP request → backend. Define the trust boundary from TLS termination to the backend too.',
['Replace app.example.com with the actual endpoint. Test the certificate/chain without verification bypasses.',
'Expect Verify return code: 0 (ok), correct hostname and the required endpoint status. For internal CA, use an approved trust store or --cacert rather than -k.',
'The Nginx article supplies the complete TLS/redirect configuration. After deploying it, add this directive only inside the HTTPS server block. This directive is not a standalone Nginx configuration.',
'Expect the header only on HTTPS with a short max-age. Increase it after validating every hostname and renewal. includeSubDomains/preload require a complete inventory and recovery plan.'],
'SSL is historical terminology; SSLv2/v3 are not acceptable baselines. Restrict keys to root and serve a valid chain. Assess replay before 0-RTT on state-changing requests. A fixed-hostname redirect avoids trusting arbitrary incoming Host values.',
'Probe SAN, chain and expiry through the actual client path; the disk file may differ from the served certificate. Test both TLS and API behavior. Example expiry alerts are 30/14/7 days.',
['For expiry, check actual client/server time and notAfter. For name mismatch, inspect DNS/SAN/SNI; for unknown issuer, inspect intermediates and CA trust. Browser-only failures may involve mixed content, HSTS/cache or trust stores. Upstream HTTP errors need not be client TLS failures. OpenSSL without -verify_return_error may continue with warnings; interpret the result correctly.'],
['Back up keys/certificates/configuration in a vault. Retain an older still-valid chain for deployment rollback where appropriate. Reload after renewal and probe remotely. HSTS is client-cached: max-age=0 requires valid HTTPS and does not guarantee instant recovery for every client. Preload removal has a separate process and delay.'],
'Assign certificate ownership, automate renewal and canary-test trust. Do not use -k for acceptance. HTTPS alone does not secure application logic or compromised endpoints.',
'TLS 1.3 differs from TLS 1.2 in cipher/handshake behavior. Validate older-client policy using official guidance. HSTS requires working trusted HTTPS; a redirect is not HSTS.',
[['Does redirect replace HSTS?','No. Browsers acquire HSTS policy through trusted HTTPS.'],['Why is a valid certificate on disk insufficient?','The service may still serve an older certificate; probe from the real client path.']])

add('imap-vs-pop3-email-protocol-comparison','Enterprise IMAP and POP3: Authentication, Synchronization and Retention',
'Choose mail retrieval around multi-device state, provider authentication policies and independent retention, then validate TLS and client behavior.',
'POP3 deletion settings can hide mail from other devices, while IMAP synchronization is not a backup. Choose protocols alongside organizational retention and authentication policy.',
'Illustrative scenario at fictional Arya: mobile/desktop users need shared folders/read state, so IMAP is selected. A legacy POP3 workflow is tested with a dedicated mailbox and retention review before migration.',
['Provider-compatible IMAP4/POP3 client and OAuth; OpenSSL 3.x for diagnostics. Apply the current Exchange Online policy; assess on-premises Exchange separately.','Existing workstation with mailbox quota, cache and archive capacity determined by retention. This is not a mail-server installation.','Mail-admin protocol authorization, a test mailbox, trusted certificates and TCP/993 or 995 egress. SMTP submission is a separate sending path.'],
'Client ↔ IMAP mailbox state; POP3 → download/optional deletion; SMTP submission sends independently. OAuth belongs to provider authentication; TLS protects transport.',
['Check approved tenant/mailbox protocol policy first. Do not enable POP/IMAP fleet-wide by default. The provider may reject Basic authentication.',
'Replace the sample hostnames with organizational servers. Validate chain/hostname before entering credentials.',
'After the banner, use credential-free commands. This transcript is IMAP only.',
'Expect tagged OK responses and advertised capabilities. Test POP3S TLS separately.',
'After its banner, enter CAPA then QUIT. Configure OAuth sign-in and the test mailbox in an approved client. Verify test-message receipt, folders/read-state synchronization between devices and authorized submission. TLS success does not establish login success.'],
'Do not recommend Basic/app passwords without provider support and policy approval. Follow OAuth/MFA requirements. Avoid plaintext 110/143 without enforced STARTTLS. 993/995 use implicit TLS; 587 uses provider-approved STARTTLS submission.',
'Monitor authentication failures, mailbox quota, delivery delay and sync errors. Synthetic checks need a dedicated restricted mailbox; never expose credentials in dashboards. MTA and IMAP/POP monitoring have different scopes.',
['Working TLS with rejected login suggests disabled protocols, OAuth scope or account policy. Missing mail suggests subscriptions, POP deletion policy or cache. Sending failure with healthy retrieval requires independent SMTP/auth checks. Back up local-only mail/PST before deleting a profile.'],
['IMAP sync and POP leave-on-server are not backups or retention controls. Define provider-compatible mailbox backup/retention/legal hold; securely export local-only mail before migration. Test message restore into an isolated mailbox, checking headers, dates and attachments.'],
'For multiple devices, IMAP or the provider’s official client generally provides better synchronization. Provider constraints and OAuth compatibility determine the choice. Define server-side retention independently of client behavior.',
'POP3 does not invariably delete messages; client/server settings determine this. SMTP sends mail, not IMAP. Do not generalize Exchange Online policy to on-premises Exchange.',
[['Is IMAP an email backup?','No. Deletions synchronize; backup and retention must be independent.'],['Does working retrieval prove sending works?','No. SMTP submission has a separate path and authentication.']])

if __name__ == '__main__':
    assert len(EN) == 25, len(EN)
    from article_comparisons import apply_editorial
    apply_editorial(EN, 'en')
    target = Path(__file__).resolve().parents[1] / 'docs/enterprise-articles/english-runbooks.json'
    target.write_text(json.dumps(EN,ensure_ascii=False,indent=2),encoding='utf-8')
    print('Prepared',len(EN),'English counterparts.')
