"""Maintained bilingual RouterOS v7 article; commands are shared between languages."""
from pathlib import Path
from html import escape
import json

ROOT = Path(__file__).resolve().parents[4]
PACKAGE = Path(__file__).parent
SLUG = 'mikrotik-ping-triggered-policy-routing'
sections = []
def node(tag, en, fa):
    return f'<{tag} data-en="{escape(en, quote=True)}" data-fa="{escape(fa, quote=True)}">{escape(en)}</{tag}>'
def p(en, fa): return node('p', en, fa)
def code(value): return '<pre dir="ltr"><code class="language-routeros">'+escape(value.strip())+'</code></pre>'
def section(key, en, fa, body):
    sections.append((key, en, fa, '<section id="'+key+'">'+node('h2', en, fa)+body+'</section>'))
def table(headers, rows):
    return '<div class="table-responsive"><table><thead><tr>'+''.join(node('th', *h) for h in headers)+'</tr></thead><tbody>'+''.join('<tr>'+''.join(node('td', *cell) for cell in row)+'</tr>' for row in rows)+'</tbody></table></div>'

control = r'''/interface bridge
add name=PBR-Control protocol-mode=none comment="PBR Control Interface"
/ip address
add address=10.255.255.1/32 interface=PBR-Control comment="Enable PBR"
add address=10.255.255.2/32 interface=PBR-Control comment="Disable PBR"'''
localnets = r'''/ip firewall address-list
add list=LOCAL-NETS address=192.168.10.0/24 comment="LAN example"
add list=LOCAL-NETS address=192.168.20.0/24 comment="Internal VLAN example"
add list=PBR-ELIGIBLE address=192.168.10.0/24 comment="Stable FastTrack exclusion for trigger-capable clients"'''
enable = r'''/ip firewall mangle
add chain=prerouting in-interface-list=LAN src-address=192.168.10.0/24 \
    src-address-list=!PBR-REMOVE protocol=icmp icmp-options=8:0 \
    dst-address=10.255.255.1 action=add-src-to-address-list \
    address-list=PBR-ACTIVE address-list-timeout=none-dynamic \
    passthrough=yes comment="Enable PBR using ICMP trigger"'''
disable = r'''/ip firewall mangle
add chain=prerouting in-interface-list=LAN src-address=192.168.10.0/24 \
    protocol=icmp icmp-options=8:0 dst-address=10.255.255.2 \
    action=add-src-to-address-list address-list=PBR-REMOVE \
    address-list-timeout=10s passthrough=yes comment="Disable PBR request"'''
routing = r'''/routing table
add fib name=VPN-ROUTE
/ip route
add dst-address=0.0.0.0/0 gateway=l2tp-vpn-example \
    routing-table=VPN-ROUTE comment="PBR default route"'''
mark = r'''/ip firewall mangle
add chain=prerouting in-interface-list=LAN src-address-list=PBR-ACTIVE \
    dst-address-list=!LOCAL-NETS dst-address-type=!local \
    action=mark-routing new-routing-mark=VPN-ROUTE passthrough=no \
    comment="Route PBR clients using VPN-ROUTE"'''
worker = '''/system script
add name=PBR-Remove-Worker policy=read,write,test dont-require-permissions=no source={
    :if ([:len [/system script job find where script="PBR-Remove-Worker"]] > 1) do={
        :return
    }
    :foreach request in=[/ip firewall address-list find where list="PBR-REMOVE"] do={
        :local clientIP ""
        :do {
            :set clientIP [/ip firewall address-list get $request address]
            :local active [/ip firewall address-list find where list="PBR-ACTIVE" and address=$clientIP]
            :if ([:len $active] > 0) do={
                /ip firewall address-list remove $active
                :log info ("PBR disabled for client " . $clientIP)
            }
            /ip firewall address-list remove $request
        } on-error={
            :if ([:len [/ip firewall address-list find where list="PBR-REMOVE" and address=$clientIP]] > 0) do={
                :log warning ("PBR removal failed; queued retry for " . $clientIP)
            }
        }
    }
}'''
scheduler = r'''/system scheduler
add name=PBR-Remove-Scheduler start-time=startup interval=1s \
    on-event=PBR-Remove-Worker policy=read,write,test \
    comment="Process queued PBR disable requests"'''
nat = r'''/ip firewall nat
add chain=srcnat src-address-list=PBR-ACTIVE out-interface=l2tp-vpn-example \
    action=masquerade comment="NAT PBR traffic"'''
inputrules = r'''/ip firewall address-list
add list=PBR-CONTROL-IPS address=10.255.255.1 comment="Enable trigger destination"
add list=PBR-CONTROL-IPS address=10.255.255.2 comment="Disable trigger destination"
/ip firewall filter
add chain=input in-interface-list=LAN src-address=192.168.10.0/24 \
    dst-address-list=PBR-CONTROL-IPS protocol=icmp icmp-options=8:0 \
    action=accept comment="Allow authorized PBR echo requests"
add chain=input dst-address-list=PBR-CONTROL-IPS action=drop \
    comment="Deny other access to PBR control addresses"'''
ft = '''/ip firewall filter
print detail where action=fasttrack-connection
# Only after reviewing the existing rule and assigning this example comment:
{
    :local ft [/ip firewall filter find where action="fasttrack-connection" and comment="Example reviewed FastTrack"]
    :if ([:len $ft] != 1) do={ :error "Identify exactly one reviewed FastTrack rule first" }
    /ip firewall filter set $ft src-address-list=!PBR-ELIGIBLE dst-address-list=!PBR-ELIGIBLE
}'''
diagnostics = '''/ip firewall address-list print where list="PBR-ACTIVE"
/ip firewall address-list print where list="PBR-REMOVE"
/ip firewall mangle print stats
/routing table print
/ip route print detail where routing-table="VPN-ROUTE"
/ip firewall connection print where src-address~"^192[.]168[.]10[.]50(:|$)"
/system scheduler print detail where name="PBR-Remove-Scheduler"
/log print where message~"PBR"'''

section('introduction', '1. Introduction', '۱. مقدمه',
    p('English Version', 'Persian Version — نسخه فارسی')+
    p('A client can request an alternate IPv4 Internet path by pinging one control address, then return to ordinary routing by pinging another. The router uses the source address of the echo request as the client identity. This is useful for temporary VPN routing, a second ISP, routing experiments, troubleshooting and temporary access to a special path without logging in to MikroTik.', 'Client با Ping کردن یک آدرس کنترلی، مسیر IPv4 اینترنت خود را تغییر می‌دهد و با Ping آدرس دوم به مسیر عادی برمی‌گردد. روتر IP مبدأ Echo Request را شناسه Client در نظر می‌گیرد. کاربردها شامل عبور موقت از VPN، استفاده از ISP دوم، آزمایش Routing، عیب‌یابی و دسترسی موقت به مسیر خاص بدون Login به MikroTik است.')+
    p('This runbook targets RouterOS v7. Every network, client, interface, list and gateway below is fictional. It assumes an existing working LAN, main default route, firewall and authenticated, running l2tp-vpn-example tunnel. Creating the tunnel, credentials and its upstream Internet service is outside this configuration. No configuration from the hosting environment is used.', 'این Runbook مخصوص RouterOS v7 است. تمام شبکه‌ها، Clientها، Interfaceها، Listها و Gatewayهای زیر مثال هستند. پیش‌فرض، LAN فعال، Default Route سالم در main، Firewall موجود و Tunnel احراز هویت‌شده و فعال با نام فرضی l2tp-vpn-example است. ساخت Tunnel، Credential و سرویس اینترنت سمت مقابل در این Config انجام نمی‌شود. هیچ اطلاعاتی از محیط میزبانی وارد مثال نشده است.')+
    p('The examples steer client-originated IPv4 traffic. IPv6, router-originated traffic and Internet connections initiated by a router DNS proxy need separate policies. This is an operator control mechanism, not an authentication protocol or a VPN leak-prevention policy.', 'مثال‌ها ترافیک IPv4 ایجادشده توسط Client را هدایت می‌کنند. IPv6، ترافیک تولیدشده توسط خود روتر و اتصال اینترنتی DNS Proxy روتر به Policy مستقل نیاز دارند. این روش ابزار کنترل مسیر است؛ پروتکل احراز هویت یا Policy جلوگیری از نشت VPN نیست.'))

flow = '''Normal:  Client -> main -> Default ISP
Enable:  Client -> Ping 10.255.255.1 -> PBR-ACTIVE
                -> Mangle -> VPN-ROUTE -> VPN / Secondary Gateway
Disable: Client -> Ping 10.255.255.2 -> PBR-REMOVE
                -> Script -> Remove from PBR-ACTIVE -> main'''
section('architecture', '2. Architecture', '۲. معماری', code(flow)+
    p('The example client is 192.168.10.50 on LAN 192.168.10.0/24. Internal services use 192.168.20.0/24, which may represent an example VLAN 20. LAN is an interface list, not a physical port. The control bridge has no member ports. Echo requests enter prerouting; local delivery and input filtering follow. A successful ping reply is useful feedback, but address-list membership is the authoritative state.', 'Client مثال 192.168.10.50 در LAN با شبکه 192.168.10.0/24 قرار دارد. سرویس‌های داخلی از 192.168.20.0/24 استفاده می‌کنند که می‌تواند VLAN فرضی 20 باشد. LAN یک Interface List است، نه پورت فیزیکی. Bridge کنترلی هیچ Member Port ندارد. Echo Request ابتدا وارد prerouting و سپس مسیر Local Delivery و input می‌شود. پاسخ موفق Ping بازخورد مفیدی است، اما عضویت Address List وضعیت واقعی را مشخص می‌کند.')+
    p('Enable applies to subsequent eligible packets; disable is asynchronous, normally processed at the next one-second scheduler tick. Disable wins while a removal request is queued: the enable rule excludes PBR-REMOVE. Wait for that list to clear before enabling again. Continuous pings are repeated commands, so stop the disable ping before issuing enable.', 'فعال‌سازی روی Packetهای واجد شرایط بعدی اثر می‌گذارد؛ غیرفعال‌سازی غیرهم‌زمان است و معمولاً در اجرای بعدی Scheduler یک‌ثانیه‌ای پردازش می‌شود. تا وقتی درخواست حذف در صف است، Disable اولویت دارد؛ Rule فعال‌سازی PBR-REMOVE را مستثنا می‌کند. برای Enable مجدد، صبر کنید صف پاک شود. Ping پیوسته فرمان تکراری است؛ قبل از Enable، Ping مربوط به Disable را متوقف کنید.'))

section('technical-limitation', '3. Root Cause / Technical Limitation', '۳. محدودیت فنی Firewall',
    p('Firewall actions can add the packet source with action=add-src-to-address-list. There is no remove-src-from-address-list action in the RouterOS v7 mangle action set. Therefore the second trigger adds a short-lived removal request; a script performs the deletion. Adding a client to PBR-REMOVE alone does not delete PBR-ACTIVE.', 'Firewall با action=add-src-to-address-list مبدأ Packet را به List اضافه می‌کند. در Actionهای Mangle در RouterOS v7 گزینه remove-src-from-address-list وجود ندارد. بنابراین Trigger دوم یک درخواست حذف کوتاه‌عمر ثبت می‌کند و Script حذف را انجام می‌دهد. عضویت در PBR-REMOVE به‌تنهایی PBR-ACTIVE را حذف نمی‌کند.')+
    '<p><a href="https://manual.mikrotik.com/docs/cli-reference/ip/firewall/mangle/">RouterOS mangle action reference</a></p>')

section('control-interface', '4. Control Interface', '۴. Interface کنترلی',
    p('Create an empty bridge to own both control addresses. The /32 prefix defines an individual host address, avoiding an unnecessary connected subnet and any implication that other control addresses are on-link. The LAN client sends these destinations through its existing default gateway; do not assign them to the client or add bridge ports.', 'یک Bridge خالی برای نگهداری هر دو آدرس کنترلی بسازید. Prefix برابر /32 یک Host Address تعریف می‌کند؛ Subnet متصل اضافی نمی‌سازد و سایر آدرس‌های کنترلی را On-link فرض نمی‌کند. Client این مقصدها را از Default Gateway موجود ارسال می‌کند؛ آن‌ها را روی Client تنظیم نکنید و به Bridge پورت اضافه نکنید.')+code(control)+
    p('Verify that the bridge exists without ports and both addresses are enabled. This bridge does not replace the LAN bridge or an existing VLAN interface.', 'وجود Bridge بدون پورت و فعال بودن هر دو IP را بررسی کنید. این Bridge جایگزین LAN Bridge یا Interface مربوط به VLAN موجود نیست.')+code('/interface bridge print detail where name="PBR-Control"\n/interface bridge port print where bridge="PBR-Control"\n/ip address print where interface="PBR-Control"'))

section('local-networks', '5. Local Networks', '۵. شبکه‌های داخلی',
    p('List every internal routed subnet that must retain main-table reachability. A remote private network is not automatically local: add the actual internal prefixes required by the example topology. PBR-ELIGIBLE is a separate stable population for FastTrack exclusion and covers all clients allowed to use the triggers, even while inactive.', 'تمام Subnetهای داخلی مسیریابی‌شده را که باید از main قابل دسترس بمانند در List قرار دهید. هر شبکه خصوصی دوردست الزاماً Local نیست؛ Prefixهای داخلی موردنیاز توپولوژی مثال را ثبت کنید. PBR-ELIGIBLE جمعیت ثابت Clientهای مجاز برای استثنای FastTrack است و آن‌ها را حتی در حالت غیرفعال پوشش می‌دهد.')+code(localnets)+
    p('Verify both internal prefixes and the eligible range. Local exceptions retain normal routing; they do not grant firewall access or create missing routes.', 'هر دو Prefix داخلی و محدوده Clientهای مجاز را بررسی کنید. استثنای Local فقط Routing عادی را حفظ می‌کند؛ مجوز Firewall نمی‌دهد و Route گمشده را ایجاد نمی‌کند.')+code('/ip firewall address-list print where list="LOCAL-NETS"\n/ip firewall address-list print where list="PBR-ELIGIBLE"'))

section('enable-trigger', '6. Enable Trigger', '۶. Trigger فعال‌سازی',
    p('Only LAN sources in the example subnet can activate PBR. icmp-options=8:0 matches IPv4 ICMP Echo Request: type 8, code 0. The extra pending-removal exclusion avoids an enable request immediately being undone by the worker. passthrough=yes allows the packet to continue through mangle and local delivery.', 'فقط مبدأهای LAN در Subnet مثال می‌توانند PBR را فعال کنند. icmp-options=8:0 یعنی IPv4 ICMP Echo Request با Type 8 و Code 0. استثنای درخواست حذف معلق مانع می‌شود Worker بلافاصله Enable جدید را خنثی کند. passthrough=yes پردازش بعدی Mangle و تحویل Local را ادامه می‌دهد.')+code(enable)+
    p('none-dynamic keeps the dynamic entry until explicit removal or reboot. It is not disk-persistent. For the first rollout, use src-address=192.168.10.50/32 on both trigger rules; expand to the shown /24 only after validation. Verify a single enable ping produces a dynamic host entry and increments the enable counter.', 'none-dynamic رکورد Dynamic را تا حذف صریح یا Reboot نگه می‌دارد؛ روی دیسک پایدار نیست. در Rollout اولیه روی هر دو Trigger از src-address=192.168.10.50/32 استفاده کنید و پس از تأیید، محدوده را به /24 نمایش‌داده‌شده گسترش دهید. یک Ping فعال‌سازی باید رکورد Dynamic مربوط به Host ایجاد کند و Counter فعال‌سازی را افزایش دهد.')+code('/ip firewall address-list print where list="PBR-ACTIVE"\n/ip firewall mangle print stats where comment="Enable PBR using ICMP trigger"'))

section('disable-trigger', '7. Disable Trigger', '۷. Trigger غیرفعال‌سازی',
    p('The second echo destination queues the source in PBR-REMOVE for ten seconds. This is a queue lifetime, not the access lifetime. The worker must run within that window; if it is stopped or failing, the request can expire without disabling the client. Monitor scheduler health and retry the ping after repair. For loaded routers consider a longer queue timeout, such as one minute.', 'مقصد دوم Echo، مبدأ را برای ده ثانیه در PBR-REMOVE قرار می‌دهد. این زمان عمر صف است، نه مدت دسترسی. Worker باید در این بازه اجرا شود؛ اگر متوقف یا دچار خطا باشد، درخواست ممکن است بدون غیرفعال‌شدن Client منقضی شود. سلامت Scheduler را پایش کنید و پس از اصلاح دوباره Ping بزنید. در روترهای پربار می‌توان عمر صف را مثلاً یک دقیقه در نظر گرفت.')+code(disable)+
    p('Verify the disable counter increases and PBR-ACTIVE loses the client after the worker runs. PBR-REMOVE may already be empty by the time it is printed; that is expected after successful processing.', 'افزایش Counter غیرفعال‌سازی و حذف Client از PBR-ACTIVE پس از اجرای Worker را بررسی کنید. ممکن است هنگام Print، PBR-REMOVE از قبل خالی شده باشد؛ بعد از پردازش موفق طبیعی است.')+code('/ip firewall mangle print stats where comment="Disable PBR request"\n/ip firewall address-list print where list="PBR-REMOVE"'))

section('routing-table', '8. RouterOS v7 Routing Table', '۸. Routing Table در RouterOS v7',
    p('Create the FIB-enabled table before referring to it in new-routing-mark. The illustrated interface gateway is suitable for an already established point-to-point L2TP tunnel. Confirm upstream forwarding and a return path; an active route alone does not prove Internet access.', 'Table با fib را پیش از استفاده در new-routing-mark بسازید. Gateway مبتنی بر Interface نمایش‌داده‌شده برای Tunnel نقطه‌به‌نقطه L2TP که از قبل برقرار است مناسب است. Forwarding سمت مقابل و مسیر برگشت را تأیید کنید؛ Route فعال به‌تنهایی دسترسی اینترنت را ثابت نمی‌کند.')+code(routing)+
    p('Verify VPN-ROUTE appears with FIB enabled and its default route has the active flag. RouterOS v7 uses routing-table on routes; do not substitute the v6 route property routing-mark.', 'وجود VPN-ROUTE با FIB فعال و Flag فعال روی Default Route آن را بررسی کنید. در RouterOS v7 روی Route از routing-table استفاده می‌شود؛ آن را با Property نسخه v6 یعنی routing-mark جایگزین نکنید.')+code('/routing table print\n/ip route print detail where routing-table="VPN-ROUTE"\n/interface print detail where name="l2tp-vpn-example"')+
    p('A production egress can be a VPN interface, WireGuard peer, GRE path, a secondary ISP next hop or a recursive route. These are alternatives, not interchangeable gateway strings. For an example Ethernet ISP, resolve the next hop through main as below; main must have reachability to that next hop. On multi-access Ethernet, use a next-hop IP rather than an interface-only default route.', 'خروجی Production می‌تواند VPN Interface، Peer در WireGuard، مسیر GRE، Next Hop مربوط به ISP دوم یا Recursive Route باشد. این‌ها گزینه‌های جایگزین هستند و رشته Gateway یکسان ندارند. برای ISP اترنت مثال، Next Hop را طبق فرمان زیر از main Resolve کنید؛ main باید به آن Next Hop دسترسی داشته باشد. در Ethernet چنددسترسی برای Default Route از IP مربوط به Next Hop استفاده کنید، نه فقط نام Interface.')+code('/ip route add dst-address=0.0.0.0/0 gateway=192.0.2.1@main routing-table=VPN-ROUTE comment="Alternative secondary ISP example"')+
    p('Use this alternative instead of the L2TP default, not alongside it unless equal-cost routing is intended. For WireGuard, configure the correct peer allowed-address ranges and keep the endpoint reachable through the underlay. GRE needs its own remote forwarding and return routing. Recursive routing requires explicit resolver routes and compatible scope/target-scope settings. Validate the chosen design separately.', 'این جایگزین را به‌جای Default مربوط به L2TP استفاده کنید؛ هم‌زمان اضافه نکنید مگر ECMP مدنظر باشد. در WireGuard محدوده allowed-address مربوط به Peer و دسترسی Endpoint از Underlay را تنظیم کنید. GRE به Forwarding سمت مقابل و Routing برگشت نیاز دارد. Recursive Routing به Resolver Route صریح و تنظیم سازگار scope/target-scope نیاز دارد. طراحی انتخاب‌شده را جداگانه آزمون کنید.')+
    '<p><a href="https://help.mikrotik.com/docs/spaces/ROS/pages/59965508/Policy%20Routing">RouterOS v7 policy routing</a></p>')

section('mangle-policy', '9. Mangle Policy Routing', '۹. Policy Routing با Mangle',
    p('Mark only active-client traffic arriving from LAN, with an Internet destination rather than an internal subnet or a router-owned address. Keep both trigger rules before this mark rule, and review any earlier PCC, routing marks, jump chains or terminating actions. passthrough=no prevents later mangle rules from overwriting this decision for a matched packet.', 'فقط ترافیک Client فعال که از LAN وارد می‌شود و مقصد آن اینترنت است، نه Subnet داخلی یا آدرس متعلق به روتر، Mark شود. هر دو Trigger را قبل از این Rule قرار دهید و PCC، Routing Mark، Jump Chain و Actionهای خاتمه‌دهنده قبلی را بررسی کنید. passthrough=no اجازه نمی‌دهد Rule بعدی Mangle تصمیم این Packet منطبق را بازنویسی کند.')+code(mark)+table([('Matcher', 'شرط'), ('Purpose', 'کارکرد')], [
    [('src-address-list=PBR-ACTIVE','src-address-list=PBR-ACTIVE'),('Selects enabled source clients.','Clientهای فعال را با IP مبدأ انتخاب می‌کند.')],
    [('dst-address-list=!LOCAL-NETS','dst-address-list=!LOCAL-NETS'),('Excludes listed internal destination subnets.','Subnetهای مقصد داخلی ثبت‌شده را مستثنا می‌کند.')],
    [('dst-address-type=!local','dst-address-type=!local'),('Excludes every address owned by this router, including both triggers. It does not exclude all private networks.','تمام آدرس‌های متعلق به خود روتر، از جمله Triggerها را مستثنا می‌کند؛ به معنی استثنای تمام شبکه‌های خصوصی نیست.')],
    [('new-routing-mark=VPN-ROUTE','new-routing-mark=VPN-ROUTE'),('Selects the pre-created v7 routing table for matching packets.','Table ساخته‌شده در v7 را برای Packet منطبق انتخاب می‌کند.')]])+
    p('Verify the counter rises on a fresh Internet connection from 192.168.10.50. An internal-only test should not raise this rule’s counter. Other existing mangle rules can still mark excluded traffic, so audit the complete ruleset.', 'افزایش Counter در اتصال اینترنتی تازه از 192.168.10.50 را بررسی کنید. تست صرفاً داخلی نباید Counter این Rule را افزایش دهد. Ruleهای دیگر موجود هنوز می‌توانند ترافیک مستثناشده را Mark کنند؛ کل Ruleset را بررسی کنید.')+code('/ip firewall mangle print stats where comment="Route PBR clients using VPN-ROUTE"\n/ip firewall mangle print detail'))

section('removal-script', '10. Removal Script', '۱۰. Script حذف',
    p('The worker queries the exact client address inside PBR-ACTIVE rather than scanning every active client for every request. Both lists are reserved for this mechanism and contain individual host entries; do not place aggregate prefixes, ranges or DNS names in them. Manual aggregate entries would require different removal semantics.', 'Worker به‌جای پیمایش تمام Clientهای فعال برای هر درخواست، IP دقیق Client را در PBR-ACTIVE جست‌وجو می‌کند. هر دو List به این مکانیزم اختصاص دارند و شامل Host Entry هستند؛ Prefix تجمیعی، Range یا نام DNS داخل آن‌ها قرار ندهید. رکورد دستی تجمیعی به منطق حذف متفاوتی نیاز دارد.')+
    p('The job guard avoids normal scheduler overlap. Per-request error handling tolerates an entry expiring during processing; a failed deletion leaves the request available for retry until its timeout. A successful state change produces one info log; repeated disable requests for an inactive client are silent. Permissions are explicit, and permission checks remain enabled.', 'Guard مربوط به Job از هم‌پوشانی معمول اجرای Scheduler جلوگیری می‌کند. مدیریت خطای هر درخواست، انقضای رکورد حین پردازش را تحمل می‌کند؛ حذف ناموفق درخواست را تا پایان Timeout برای Retry نگه می‌دارد. تغییر موفق وضعیت یک Log با سطح info ایجاد می‌کند؛ Disable تکراری Client غیرفعال Log ندارد. Permissionها صریح هستند و بررسی Permission غیرفعال نشده است.')+code(worker)+
    p('Verify manually after queuing one disable request: the worker should remove that exact host from both lists and log the transition. Review warnings and scheduler run-count; a growing run-count alone does not prove successful removal. This is a small operational queue, not a durable transactional message system.', 'پس از ثبت یک درخواست Disable، اجرای دستی را بررسی کنید: Worker باید همان Host را از هر دو List حذف و تغییر وضعیت را Log کند. Warningها و run-count را بررسی کنید؛ افزایش run-count به‌تنهایی حذف موفق را ثابت نمی‌کند. این یک صف عملیاتی کوچک است، نه سیستم پیام تراکنشی و پایدار.')+code('/system script run PBR-Remove-Worker\n/ip firewall address-list print where list="PBR-ACTIVE"\n/ip firewall address-list print where list="PBR-REMOVE"\n/log print where message~"PBR"')+
    '<p><a href="https://manual.mikrotik.com/docs/developer-guides/scripting/">RouterOS scripting and execution permissions</a></p>')

section('scheduler', '11. Scheduler', '۱۱. Scheduler',
    p('Firewall list actions cannot invoke this removal logic themselves. Run the worker every second with permissions matching the script. Calling the script by name uses its script permissions; the scheduler needs sufficient rights to execute it. start-time=startup with a nonzero interval establishes recurring scheduling after boot; do not rely on an immediate boot-time cleanup.', 'Action مربوط به List در Firewall این منطق حذف را اجرا نمی‌کند. Worker را هر ثانیه با Permission سازگار با Script اجرا کنید. فراخوانی Script با نام، Permission خود Script را استفاده می‌کند؛ Scheduler باید مجوز کافی برای اجرای آن داشته باشد. start-time=startup همراه interval غیرصفر زمان‌بندی تکرارشونده پس از Boot را برقرار می‌کند؛ به پاک‌سازی فوری در لحظه Boot تکیه نکنید.')+code(scheduler)+
    p('Verify enabled status, interval=1s, next-run and an increasing run-count. Test the actual disable operation. A disabled worker, insufficient rights or scheduler delay beyond ten seconds can lose the short-lived request.', 'فعال بودن، interval=1s، next-run و افزایش run-count را بررسی کنید و عملیات Disable واقعی را تست کنید. Worker غیرفعال، Permission ناکافی یا تأخیر بیش از ده ثانیه ممکن است درخواست کوتاه‌عمر را از بین ببرد.')+code('/system scheduler print detail where name="PBR-Remove-Scheduler"\n/system script print detail where name="PBR-Remove-Worker"')+
    '<p><a href="https://help.mikrotik.com/docs/spaces/ROS/pages/40992881/Scheduler">Scheduler properties</a></p>')

section('fasttrack', '12. FastTrack', '۱۲. FastTrack',
    p('FastTrack forwards much of an established connection outside the normal firewall processing path and uses main-table routing. A connection requiring a custom routing mark must be excluded in both directions. Some packets still take the slow path, so nonzero mangle counters do not prove that FastTrack is harmless.', 'FastTrack بخش بزرگی از Packetهای Established را خارج از مسیر عادی پردازش Firewall عبور می‌دهد و از Routing جدول main استفاده می‌کند. اتصال نیازمند Routing Mark اختصاصی باید در هر دو جهت مستثنا شود. بعضی Packetها هنوز Slow Path را طی می‌کنند؛ Counter غیرصفر Mangle بی‌اثر بودن FastTrack را ثابت نمی‌کند.')+
    p('The commonly suggested src-address-list=!PBR-ACTIVE and dst-address-list=!PBR-ACTIVE exclude currently active clients. They do not reliably undo FastTrack already attached to a connection before enable. They also make a connection eligible again immediately after disable. For this dynamic scenario, permanently exclude the trigger-capable population with PBR-ELIGIBLE, then start fresh sessions or selectively clear that population’s old tracked sessions during maintenance.', 'استثنای رایج src-address-list=!PBR-ACTIVE و dst-address-list=!PBR-ACTIVE Clientهای فعلی فعال را مستثنا می‌کند، اما FastTrack اتصال ایجادشده پیش از Enable را به‌طور قابل اتکا لغو نمی‌کند. پس از Disable نیز اتصال دوباره واجد شرایط می‌شود. برای این سناریوی Dynamic، جمعیت مجاز Trigger را با PBR-ELIGIBLE به‌صورت ثابت مستثنا کنید و Session تازه بسازید یا در Maintenance اتصال‌های قدیمی همان Clientها را انتخابی پاک کنید.')+
    p('Inspect the existing firewall before any FastTrack change. The following guarded example applies only to one reviewed rule whose example comment was explicitly assigned. If it already has address-list conditions, integrate the exception into its existing logic rather than overwriting those conditions. Audit every FastTrack rule and retain the ordinary established/related accept rule that serves slow-path traffic. Do not insert broad accept rules merely to bypass FastTrack.', 'پیش از تغییر FastTrack، Firewall فعلی را بررسی کنید. مثال Guardدار زیر فقط به یک Rule بررسی‌شده با Comment فرضی که عمداً تعیین شده اعمال می‌شود. اگر Rule از قبل شرط Address List دارد، استثنا را در منطق موجود ادغام کنید و شرط قبلی را بازنویسی نکنید. تمام FastTrack Ruleها را بررسی و Rule عادی پذیرش established/related برای Slow Path را حفظ کنید. صرفاً برای دورزدن FastTrack یک accept گسترده اضافه نکنید.')+code(ft)+
    p('Verify no FastTrack rule can match eligible client traffic in either direction. Inspect a newly opened connection from the example client: it must not carry the FastTrack flag. Changing a filter rule does not by itself flush already tracked connections. Excluding a full subnet increases CPU work; measure capacity before expanding the eligible range.', 'تأیید کنید هیچ FastTrack Rule در هیچ جهت با ترافیک Client مجاز Match نمی‌شود. اتصال تازه Client مثال نباید Flag مربوط به FastTrack داشته باشد. تغییر Filter به‌تنهایی Connectionهای موجود را پاک نمی‌کند. استثنای یک Subnet کامل بار CPU را بیشتر می‌کند؛ قبل از گسترش محدوده ظرفیت را اندازه‌گیری کنید.')+code('/ip firewall filter print detail where action=fasttrack-connection\n/ip firewall connection print detail where src-address~"^192[.]168[.]10[.]50(:|$)"')+
    '<p><a href="https://manual.mikrotik.com/docs/firewall-and-quality-of-service/packet-flow-in-routeros/">Packet flow and FastTrack routing</a></p>')

section('nat', '13. NAT', '۱۳. NAT',
    p('Use masquerade when the example tunnel egress requires translation to its assigned address. Install this scoped rule before any earlier source-NAT rule that would match the same traffic with a different translation. If a site-to-site tunnel already routes the LAN prefix back, NAT may be unnecessary or harmful to source visibility. A VPN interface alone does not imply that NAT is required.', 'اگر خروجی Tunnel مثال به ترجمه مبدأ به آدرس اختصاص‌یافته خود نیاز دارد، از masquerade استفاده کنید. این Rule محدود را قبل از Source NAT قبلی که همین ترافیک را با ترجمه متفاوت Match می‌کند قرار دهید. اگر Tunnel نوع Site-to-site مسیر برگشت Prefix مربوط به LAN را دارد، NAT ممکن است غیرضروری باشد یا مشاهده مبدأ اصلی را مختل کند. صرف وجود VPN Interface به معنی نیاز به NAT نیست.')+code(nat)+
    p('Verify the NAT counter on a new connection, remote reachability and return traffic. NAT decisions are stored per connection; membership or rule changes do not rewrite existing mappings. For a fixed-address secondary ISP, a reviewed src-nat rule may be preferable; match the actual example egress and intended source translation.', 'Counter مربوط به NAT را با اتصال تازه، دسترسی مقصد و ترافیک برگشت بررسی کنید. تصمیم NAT در Connection ذخیره می‌شود؛ تغییر عضویت یا Rule، Mapping قبلی را بازنویسی نمی‌کند. برای ISP دوم با آدرس ثابت، src-nat بررسی‌شده ممکن است مناسب‌تر باشد؛ خروجی مثال و ترجمه مبدأ موردنظر را دقیق Match کنید.')+code('/ip firewall nat print stats where comment="NAT PBR traffic"\n/ip firewall nat print detail')+
    '<p><a href="https://help.mikrotik.com/docs/spaces/ROS/pages/3211299/NAT">RouterOS NAT and connection mapping</a></p>')

section('connection-tracking', '14. Connection Tracking', '۱۴. Connection Tracking',
    p('Tracking remembers connection state, NAT mappings and flags such as FastTrack. It does not mean every established connection is unconditionally pinned to its original gateway. Without FastTrack, this packet-based mark rule can reroute subsequent packets immediately, while their old NAT identity remains. The result can be broken sessions or asymmetric replies rather than a clean migration. Existing routing/connection-mark designs may retain their own path decisions.', 'Connection Tracking وضعیت اتصال، Mapping مربوط به NAT و Flagهایی مثل FastTrack را نگه می‌دارد؛ این به معنی Pin شدن قطعی تمام Established Connectionها به Gateway اولیه نیست. بدون FastTrack، Rule مبتنی بر Packet می‌تواند Packet بعدی را فوراً تغییر مسیر دهد، در حالی که هویت NAT قبلی باقی مانده است. نتیجه ممکن است قطع Session یا پاسخ نامتقارن باشد، نه مهاجرت سالم اتصال. طراحی‌های موجود مبتنی بر Connection Mark نیز ممکن است تصمیم مسیر خود را حفظ کنند.')+
    p('Test with new sessions first. Only for troubleshooting, preview exact client-originated connections and then remove that same selection if a deliberate session reset is acceptable. This disconnects active TCP, UDP and application sessions from the client. It is not part of either trigger script and does not clear the entire router table or match neighboring addresses.', 'ابتدا با Session تازه تست کنید. فقط برای Troubleshooting، اتصال‌های ایجادشده توسط Client دقیق را ببینید و اگر Reset عمدی Session قابل قبول است همان انتخاب را حذف کنید. این کار Sessionهای TCP، UDP و برنامه‌های فعال Client را قطع می‌کند. جزئی از Scriptهای Trigger نیست و کل Table روتر یا آدرس‌های همسایه را Match نمی‌کند.')+code('''/ip firewall connection print detail where src-address~"^192[.]168[.]10[.]50(:|$)"
# Troubleshooting only: interrupts this client's active sessions.
/ip firewall connection remove [find where src-address~"^192[.]168[.]10[.]50(:|$)"]''')+
    p('The anchors, literal-dot character classes and port/address boundary prevent an accidental substring match on another host. This targets original-direction client sources; inspect dst-address and reply tuples separately if inbound sessions also require reset. Verify that only the intended rows disappeared, then open a fresh connection.', 'Anchorها، Character Class نقطه و مرز Port/Address مانع Match تصادفی Substring مربوط به Host دیگر می‌شوند. انتخاب فقط مبدأ جهت اصلی اتصال‌های Client را پوشش می‌دهد؛ برای Reset اتصال ورودی، dst-address و Reply Tuple را جداگانه بررسی کنید. تأیید کنید فقط Rowهای موردنظر حذف شده‌اند و سپس اتصال تازه باز کنید.')+
    '<p><a href="https://help.mikrotik.com/docs/spaces/ROS/pages/130220087/Connection%2Btracking">Connection tracking fields and flags</a></p>')

section('testing', '15. Testing', '۱۵. آزمون',
    p('Before rollout, confirm both trigger IPs are unused, LAN contains the client-facing L3 interface, and the tunnel can carry a fresh test connection. Capture the baseline public IPv4 using a trusted IP-check service of your choice; no real service domain is embedded here. Use an IPv4-specific check so an unrelated IPv6 path does not mask the result.', 'قبل از Rollout تأیید کنید Trigger IPها استفاده نشده‌اند، LAN شامل Interface لایه ۳ سمت Client است و Tunnel اتصال آزمایشی تازه را عبور می‌دهد. Public IPv4 پایه را با سرویس قابل اعتماد انتخاب خود بررسی کنید؛ هیچ Domain واقعی سرویس در مثال درج نشده است. بررسی را مخصوص IPv4 انجام دهید تا مسیر مستقل IPv6 نتیجه را پنهان نکند.')+code(diagnostics)+
    p('These are the core router diagnostics. Expect an active custom default route, a rising PBR mangle counter only for enabled Internet traffic, and a removal log after disable. The address-anchored connection query is safer than an unescaped substring search.', 'این‌ها Diagnosticهای اصلی روتر هستند. انتظار می‌رود Default Route اختصاصی فعال باشد، Counter مربوط به PBR فقط برای اینترنت Client فعال افزایش یابد و پس از Disable، Log حذف ثبت شود. Query مربوط به Connection با Anchor آدرس از جست‌وجوی Substring بدون Escape امن‌تر است.')+
    p('From the client, send one enable echo, confirm membership, and open a fresh IPv4 IP-check session. Then send one disable echo, wait for the worker, confirm absence from PBR-ACTIVE and repeat with a fresh session. Standard Windows and Linux one-shot commands are shown separately.', 'از Client یک Echo فعال‌سازی ارسال، عضویت را تأیید و Session تازه بررسی IPv4 باز کنید. سپس یک Echo غیرفعال‌سازی ارسال، منتظر Worker بمانید، نبودن Client در PBR-ACTIVE را تأیید و با Session تازه بررسی را تکرار کنید. فرمان تک‌درخواست Windows و Linux جداگانه نمایش داده شده‌اند.')+code('''# Windows client
ping -n 1 10.255.255.1
# Check public IPv4 with a fresh connection, then:
ping -n 1 10.255.255.2

# Linux client
ping -c 1 10.255.255.1
# Check public IPv4 with a fresh connection, then:
ping -c 1 10.255.255.2''')+
    p('Verify local services on both example subnets in every state. A shared upstream exit can have the same public IP on both paths; in that case use router counters and packet-path observation rather than treating identical public IPs as definitive failure. Do not leave both trigger pings running.', 'دسترسی سرویس‌های داخلی هر دو Subnet مثال را در تمام وضعیت‌ها بررسی کنید. خروجی مشترک Upstream ممکن است Public IP یکسان بدهد؛ در این حالت Counter و مشاهده مسیر Packet را بررسی کنید و IP یکسان را به‌تنهایی شکست تست ندانید. هر دو Ping مربوط به Trigger را پیوسته اجرا نگذارید.'))

section('expected-result', '16. Expected Result', '۱۶. نتیجه مورد انتظار', table([('State','وضعیت'),('Trigger','Trigger'),('Address List','Address List'),('Routing Table','Routing Table')], [
    [('Normal','عادی'),('No trigger','بدون Trigger'),('None','بدون عضویت'),('main','main')],
    [('Enabled','فعال'),('Ping 10.255.255.1','Ping 10.255.255.1'),('PBR-ACTIVE','PBR-ACTIVE'),('VPN-ROUTE','VPN-ROUTE')],
    [('Disabled','غیرفعال'),('Ping 10.255.255.2','Ping 10.255.255.2'),('Removed after worker','حذف پس از Worker'),('main','main')]])+
    p('The table describes eligible Internet packets after state processing. Internal destinations and router-owned addresses always remain excluded from this PBR rule. Other policy rules and existing sessions still need the checks described above.', 'جدول مربوط به Packet اینترنت واجد شرایط پس از پردازش وضعیت است. مقصد داخلی و آدرس متعلق به روتر همیشه از این Rule مستثنا می‌ماند. سایر Policy Ruleها و Sessionهای موجود همچنان به بررسی‌های توضیح‌داده‌شده نیاز دارند.'))

issues = [
('Client never enters the list','Client وارد List نمی‌شود', 'Wrong LAN membership, source restriction or an earlier raw/mangle action.', 'عضویت اشتباه LAN، محدودیت مبدأ یا Action قبلی در raw/mangle.', '/interface list member print where list="LAN"\n/ip firewall mangle print stats\n/ip firewall raw print stats', 'The client-facing L3 interface is a LAN member; enable counter rises on a new echo.', 'Interface لایه ۳ سمت Client عضو LAN است و Counter فعال‌سازی با Echo جدید افزایش می‌یابد.', 'Correct membership and source restrictions; put triggers before conflicting policy rules. Do not add the control bridge to LAN as a substitute.', 'عضویت و محدودیت مبدأ را اصلاح و Triggerها را قبل از Policy متعارض قرار دهید؛ Bridge کنترلی جای Interface ورودی Client نیست.'),
('Trigger ping has no reply','Ping مربوط به Trigger پاسخ ندارد', 'Missing /32 address, client route, or input firewall drop. The request can still reach mangle before input rejects it.', 'نبود IP با /32، Route مربوط به Client یا Drop در input؛ درخواست ممکن است قبل از ردشدن در input به Mangle برسد.', '/ip address print where interface="PBR-Control"\n/ip firewall filter print stats where chain="input"\n/ip firewall address-list print where list="PBR-ACTIVE"', 'Two enabled /32 addresses and authorized echo accept counters; inspect list state separately.', 'دو آدرس /32 فعال و Counter پذیرش Echo مجاز؛ وضعیت List را جدا بررسی کنید.', 'Fix client gateway and control addresses; position scoped input permissions before general ICMP accepts and final drops.', 'Gateway مربوط به Client و آدرس‌ها را اصلاح و مجوز محدود input را قبل از accept عمومی ICMP و Drop نهایی قرار دهید.'),
('Membership changes, route does not','Client عضو می‌شود ولی مسیر عوض نمی‌شود', 'Mark rule not reached, wrong source/destination match or competing PCC/routing marks.', 'Rule مربوط به Mark اجرا نمی‌شود، Match اشتباه است یا PCC/Routing Mark متعارض وجود دارد.', '/ip firewall mangle print detail\n/ip firewall mangle print stats\n/routing rule print detail', 'The PBR counter rises for a new nonlocal IPv4 connection; correct routing mark and no earlier terminating action.', 'Counter مربوط به PBR برای اتصال تازه IPv4 غیرLocal افزایش می‌یابد؛ Mark درست و بدون Action خاتمه‌دهنده قبلی.', 'Review prerouting order and all policy interactions; verify with new IPv4 sessions.', 'ترتیب prerouting و تعامل تمام Policyها را بررسی و با Session تازه IPv4 تست کنید.'),
('Internal services become unreachable','شبکه داخلی از دسترس خارج می‌شود', 'An internal prefix is missing or another policy marks internal traffic.', 'Prefix داخلی ثبت نشده یا Policy دیگر ترافیک داخلی را Mark می‌کند.', '/ip firewall address-list print where list="LOCAL-NETS"\n/ip route print detail where routing-table="main"\n/ip firewall mangle print detail', 'Both internal prefixes are listed, reachable in main, and excluded by all relevant policy rules.', 'هر دو Prefix داخلی در List و main قابل دسترس هستند و Policyهای مرتبط آن‌ها را مستثنا می‌کنند.', 'Add the exact missing internal prefixes; repair main routes and competing rules. !local alone is insufficient.', 'Prefix داخلی دقیق را اضافه و Routeهای main و Rule متعارض را اصلاح کنید؛ !local به‌تنهایی کافی نیست.'),
('Internet stops when enabled','اینترنت پس از Enable قطع می‌شود', 'Upstream tunnel forwarding, return routing, DNS or MTU/MSS failure.', 'خرابی Forwarding سمت Tunnel، Routing برگشت، DNS یا MTU/MSS.', '/interface print detail where name="l2tp-vpn-example"\n/ip route print detail where routing-table="VPN-ROUTE"\n/ip firewall filter print stats where chain="forward"', 'Running interface, active default route and allowed forward/return traffic; IP and DNS tests both succeed.', 'Interface در حال اجرا، Default فعال و Forward/Return مجاز؛ تست IP و DNS هر دو موفق.', 'Test IP reachability before DNS; repair upstream Internet/return path and forwarding policy. Investigate MTU if only large transfers fail.', 'قبل از DNS دسترسی IP را تست و مسیر اینترنت/برگشت سمت مقابل و Forward را اصلاح کنید؛ اگر فقط انتقال بزرگ خراب است MTU را بررسی کنید.'),
('VPN default is inactive','Route مربوط به VPN فعال نیست', 'Tunnel disconnected, disabled route or unusable gateway.', 'Tunnel قطع است، Route غیرفعال یا Gateway غیرقابل استفاده است.', '/ip route print detail where routing-table="VPN-ROUTE"\n/interface print detail where name="l2tp-vpn-example"', 'Default route carries the active flag and tunnel carries the running flag.', 'Default Route دارای Flag فعال و Tunnel دارای Flag Running است.', 'Restore the preconfigured tunnel and verify the route is enabled. Do not assume the interface name proves the tunnel is established.', 'Tunnel ازپیش‌تنظیم‌شده را بازیابی و فعال بودن Route را تأیید کنید؛ نام Interface برقرار بودن Tunnel را ثابت نمی‌کند.'),
('FastTrack bypasses PBR','FastTrack موجب Bypass می‌شود', 'An eligible flow matched a FastTrack rule or was FastTracked before rollout.', 'Flow مجاز با FastTrack Rule منطبق شده یا پیش از Rollout FastTrack بوده است.', '/ip firewall filter print detail where action="fasttrack-connection"\n/ip firewall connection print detail where src-address~"^192[.]168[.]10[.]50(:|$)"', 'New eligible flows have no FastTrack flag; both direction exceptions exist on every applicable rule.', 'Flow تازه مجاز Flag مربوط به FastTrack ندارد و استثنای هر دو جهت در همه Ruleهای مرتبط وجود دارد.', 'Use stable PBR-ELIGIBLE exclusions and reset only selected old client sessions if necessary.', 'استثنای ثابت PBR-ELIGIBLE اعمال و در صورت نیاز فقط Sessionهای قدیمی انتخاب‌شده Client را Reset کنید.'),
('Required NAT is missing','NAT موردنیاز وجود ندارد', 'The egress has no LAN return route and no matching source translation, or an earlier NAT rule wins.', 'خروجی Route برگشت LAN و ترجمه مبدأ منطبق ندارد یا NAT قبلی اول Match می‌شود.', '/ip firewall nat print stats\n/ip firewall nat print detail', 'The intended egress NAT rule matches new connections; remote return traffic reaches the client.', 'NAT خروجی موردنظر اتصال تازه را Match می‌کند و پاسخ سمت مقابل به Client می‌رسد.', 'Install or reposition scoped NAT when required; for routed site-to-site traffic fix the return route instead.', 'در صورت نیاز NAT محدود را نصب یا جابه‌جا کنید؛ برای Site-to-site مسیریابی‌شده، Route برگشت را اصلاح کنید.'),
('Old sessions do not switch cleanly','Session قبلی بلافاصله سالم تغییر مسیر نمی‌دهد', 'Old NAT identity, FastTrack state or another connection-mark design survives the toggle.', 'هویت NAT قبلی، وضعیت FastTrack یا طراحی Connection Mark دیگری باقی مانده است.', '/ip firewall connection print detail where src-address~"^192[.]168[.]10[.]50(:|$)"', 'Compare an old flow with a new flow; new flow uses the intended path and mapping.', 'Flow قدیمی را با تازه مقایسه کنید؛ Flow تازه مسیر و Mapping موردنظر را دارد.', 'Reconnect applications first; selectively remove tracked sessions only after accepting the interruption.', 'ابتدا برنامه را دوباره متصل کنید؛ فقط با پذیرش قطع Session رکوردهای انتخاب‌شده را حذف کنید.'),
('Routing table is missing','Routing Table ساخته نشده', 'mark-routing was configured before the v7 table or the table was deleted.', 'mark-routing قبل از ساخت Table در v7 تنظیم شده یا Table حذف شده است.', '/routing table print\n/ip firewall mangle print detail', 'VPN-ROUTE exists with fib enabled and matches new-routing-mark exactly.', 'VPN-ROUTE با fib وجود دارد و دقیقاً با new-routing-mark یکسان است.', 'Create the table first, then its routes and mark rule; check spelling and case.', 'ابتدا Table، سپس Route و Rule مربوط به Mark را بسازید؛ املا و حروف نام را بررسی کنید.'),
('Gateway cannot resolve','Gateway در Table قابل Resolve نیست', 'An IP next hop lacks main reachability or recursive scope/target-scope is wrong.', 'Next Hop مبتنی بر IP در main قابل دسترس نیست یا scope/target-scope مربوط به Recursive اشتباه است.', '/ip route print detail where routing-table="VPN-ROUTE"\n/ip route print detail where routing-table="main"\n/ip arp print where address="192.0.2.1"', 'IP-gateway routes have a resolved immediate-gw and active flag; Ethernet neighbor resolves where applicable.', 'Route مبتنی بر IP دارای immediate-gw Resolveشده و Flag فعال است؛ همسایه Ethernet در صورت کاربرد Resolve می‌شود.', 'Use the reviewed 192.0.2.1@main example with a valid connected underlay; repair resolver routes. Do not add an arbitrary main default as a blind fix.', 'از مثال بررسی‌شده 192.0.2.1@main با Underlay متصل معتبر استفاده و Resolver Route را اصلاح کنید؛ Default تصادفی main راه‌حل کورکورانه نیست.'),
('Disable never completes','Disable کامل نمی‌شود', 'Scheduler disabled, permission mismatch, worker failure or request timeout.', 'Scheduler غیرفعال، Permission ناسازگار، خطای Worker یا انقضای درخواست.', '/system scheduler print detail where name="PBR-Remove-Scheduler"\n/log print where message~"PBR"\n/ip firewall address-list print where list="PBR-REMOVE"', 'Enabled one-second worker, advancing run-count, successful removal log, and no active entry for the client.', 'Worker فعال یک‌ثانیه‌ای، run-count افزایشی، Log حذف موفق و نبود رکورد فعال Client.', 'Repair permissions and worker; reissue one disable ping. Increase queue lifetime if scheduler latency warrants it.', 'Permission و Worker را اصلاح و یک Ping مربوط به Disable دوباره ارسال کنید؛ در صورت تأخیر Scheduler عمر صف را افزایش دهید.')
]
body = p('Use state, counters and fresh sessions together. Output below describes expected properties, not guaranteed numeric rule IDs or interface flags on every device.', 'وضعیت، Counter و Session تازه را کنار هم بررسی کنید. خروجی‌های زیر ویژگی مورد انتظار را توضیح می‌دهند، نه Rule ID عددی یا Flag تضمین‌شده یکسان روی همه دستگاه‌ها.')
for en, fa, cause, causefa, cmd, expected, expectedfa, solution, solutionfa in issues:
    body += node('h3', en, fa)+p('Cause: '+cause, 'علت: '+causefa)+p('Diagnostic commands:', 'فرمان‌های Diagnostic:')+code(cmd)+p('Expected output: '+expected, 'خروجی مورد انتظار: '+expectedfa)+p('Solution: '+solution, 'راه‌حل: '+solutionfa)
section('troubleshooting', '17. Troubleshooting', '۱۷. عیب‌یابی', body)

section('security', '18. Security Considerations', '۱۸. ملاحظات امنیتی',
    p('Keep the control addresses inaccessible from WAN. LAN-only trigger matchers protect state changes even if a broad input rule permits ping from elsewhere; input policy must separately restrict replies and all other services on these router-owned addresses. Add the following scoped destination list and input rules, then position allow followed by deny before broad input accepts and final drops.', 'آدرس‌های کنترلی از WAN قابل دسترسی نباشند. شرط LAN روی Trigger تغییر وضعیت را محدود می‌کند، حتی اگر Rule عمومی input به مبدأ دیگری پاسخ Ping بدهد؛ Policy مربوط به input باید جداگانه پاسخ و تمام سرویس‌های دیگر روی این آدرس‌های روتر را محدود کند. List مقصد و Ruleهای محدود زیر را اضافه و به‌ترتیب Allow و Deny قبل از accept عمومی input و Drop نهایی قرار دهید.')+code(inputrules)+
    p('Verify an authorized LAN client receives an echo reply and an unauthorized internal or WAN source cannot reach either control IP. Existing established/related accepts and rule ordering must be reviewed; appending these rules below an earlier broad accept does not enforce the restriction. Do not expose control prefixes through WAN forwarding, published routes or DNAT.', 'تأیید کنید Client مجاز LAN پاسخ Echo دریافت می‌کند و مبدأ داخلی غیرمجاز یا WAN به هیچ‌یک از IPهای کنترلی دسترسی ندارد. accept مربوط به established/related و ترتیب Ruleها را بررسی کنید؛ افزودن زیر accept گسترده محدودیت را اعمال نمی‌کند. Prefix کنترلی را از طریق WAN Forwarding، Route منتشرشده یا DNAT در دسترس قرار ندهید.')+code('/ip firewall filter print detail where chain="input"\n/ip firewall filter print stats where dst-address-list="PBR-CONTROL-IPS"')+
    p('A ping does not authenticate a person. Any authorized source can toggle its own state, and a spoofed LAN source can potentially toggle another client. Enforce access at the edge with suitable VLAN separation, source validation and DHCP/IP binding controls. For a strict allowlist, narrow both trigger source ranges and the input allow rule to approved hosts; keep the stable FastTrack exclusion covering that complete population.', 'Ping شخص را احراز هویت نمی‌کند. هر مبدأ مجاز می‌تواند وضعیت خود را تغییر دهد و جعل IP در LAN ممکن است وضعیت Client دیگر را تغییر دهد. کنترل دسترسی را در لبه با جداسازی VLAN، اعتبارسنجی مبدأ و کنترل مناسب DHCP/IP Binding اعمال کنید. برای Allowlist سخت‌گیرانه، مبدأ هر دو Trigger و input allow را به Hostهای مجاز محدود و استثنای ثابت FastTrack را شامل تمام آن جمعیت نگه دارید.')+
    p('Do not use this mechanism as a VPN kill switch. Review lookup fall-through, gateway health and explicit drop/blackhole policy if traffic must never escape through main. The presented design does not guarantee fail-closed behavior when the custom route disappears. IPv6 can still follow a separate Internet route.', 'این مکانیزم را VPN Kill Switch در نظر نگیرید. اگر ترافیک نباید هرگز از main خارج شود، Lookup Fall-through، سلامت Gateway و Policy صریح Drop/Blackhole را بررسی کنید. طراحی ارائه‌شده هنگام حذف Route اختصاصی رفتار Fail-closed را تضمین نمی‌کند. IPv6 نیز می‌تواند مسیر اینترنت جداگانه داشته باشد.'))

section('best-practices', '19. Production Best Practices', '۱۹. توصیه‌های Production',
    p('Before changes, save a binary backup and a readable export, transfer them to protected storage, and use RouterOS terminal Safe Mode (Ctrl+X). Exports may include sensitive topology even without exposed passwords; keep operational backups out of public documentation. Take a new backup after successful validation.', 'قبل از تغییر، Binary Backup و Export قابل خواندن بگیرید، به فضای محافظت‌شده منتقل کنید و در Terminal از Safe Mode با Ctrl+X استفاده کنید. Export حتی بدون Password آشکار می‌تواند توپولوژی حساس داشته باشد؛ Backup عملیاتی را وارد مستند عمومی نکنید. پس از آزمون موفق نیز Backup جدید بگیرید.')+code('/system backup save name=pbr-before-example\n/export file=pbr-before-example')+
    p('Verify both files exist, are downloaded securely and correspond to the target router/version. Safe Mode protects an interactive change session, not an unlimited bulk import; apply in small reviewed stages and verify connectivity before committing.', 'وجود هر دو فایل، دانلود امن و تطابق با روتر/نسخه هدف را تأیید کنید. Safe Mode برای Session تعاملی تغییر است، نه Import انبوه نامحدود؛ تغییر را در مرحله‌های کوچک بررسی‌شده اعمال و قبل از Commit اتصال را تأیید کنید.')+code('/file print where name~"pbr-before-example"')+
    p('Comment each persistent rule and route; the dynamic entries are generated by their commented trigger rule. Reserve the operational lists, create the table before marking, order triggers before PBR marks, audit preceding rules, exclude every required internal prefix, and check all FastTrack/NAT interactions. Use logging for state transitions and monitor warning volume rather than logging every packet.', 'برای هر Rule و Route پایدار Comment بگذارید؛ Entryهای Dynamic توسط Trigger دارای Comment ساخته می‌شوند. Listهای عملیاتی را اختصاصی نگه دارید، Table را قبل از Mark بسازید، Trigger را قبل از Mark قرار دهید، Rule قبلی را بررسی، تمام Prefixهای داخلی لازم را مستثنا و تعامل همه FastTrack/NATها را کنترل کنید. به‌جای Log هر Packet، تغییر وضعیت را ثبت و حجم Warning را پایش کنید.')+
    p('Pilot 192.168.10.50/32 first, test enable/disable and internal services, then expand authorization. Measure CPU impact of stable FastTrack exclusions and the one-second job. Keep documentation examples anonymous. Review the exact installed RouterOS v7 release in a lab before deployment; documentation review and website tests are not device execution tests.', 'ابتدا 192.168.10.50/32 را Pilot کنید، Enable/Disable و سرویس‌های داخلی را تست و سپس مجوز را گسترش دهید. اثر استثنای ثابت FastTrack و Job یک‌ثانیه‌ای بر CPU را اندازه‌گیری کنید. مثال‌های مستند را ناشناس نگه دارید. Release دقیق RouterOS v7 نصب‌شده را قبل از استقرار در Lab بررسی کنید؛ بازبینی مستند و تست سایت معادل اجرای فرمان روی دستگاه نیست.'))

full = '\n\n'.join([control, localnets, routing, enable, disable, mark, worker, scheduler, inputrules, nat])
(PACKAGE/'complete-example.rsc').write_text('# Example only; review prerequisites and firewall ordering before applying.\n'+full+'\n', encoding='utf-8')
section('complete-configuration', '20. Complete Example Configuration', '۲۰. پیکربندی کامل مثال',
    p('Apply this once to the reviewed example environment in the sequence shown. The existing LAN interface list and working point-to-point tunnel must already exist; ordinary main routing and established/related forwarding must already work. This is an additive example, not an idempotent installer or a replacement firewall. Do not execute both individual section commands and the full block, or run the block twice: duplicate rules and name conflicts would result.', 'این Config را یک‌بار به محیط مثال بررسی‌شده و به‌ترتیب زیر اعمال کنید. Interface List موجود LAN و Tunnel نقطه‌به‌نقطه فعال باید از قبل وجود داشته باشند؛ Routing عادی main و Forward مربوط به established/related باید سالم باشند. این مثال افزایشی است، نه Installer تکرارپذیر یا Firewall جایگزین. بخش‌های جداگانه و Block کامل را هر دو اجرا نکنید و Block را دوبار اجرا نکنید؛ Rule تکراری و تضاد نام ایجاد می‌شود.')+
    p('Step 1: back up, enter Safe Mode and inspect LAN, tunnel, input, mangle, NAT and all FastTrack rules. Step 2: integrate the stable FastTrack exceptions described in section 12 before client activation. Existing criteria must be preserved; the guarded example intentionally stops unless the reviewed rule is uniquely identified. Step 3: apply the following infrastructure and policy block; omit the final NAT rule if the selected routed design does not require it.', 'مرحله ۱: Backup، Safe Mode و بررسی LAN، Tunnel، input، mangle، NAT و تمام FastTrack Ruleها. مرحله ۲: استثنای ثابت FastTrack بخش ۱۲ را قبل از فعال‌سازی Client ادغام کنید. شرط موجود باید حفظ شود؛ مثال Guardدار عمداً بدون شناسایی یکتای Rule بررسی‌شده متوقف می‌شود. مرحله ۳: Block زیر را اعمال کنید؛ اگر طراحی مسیریابی‌شده انتخاب‌شده به NAT نیاز ندارد، آخرین Rule آن را اجرا نکنید.')+code(full)+
    p('Step 4: review placement. On an existing router these add commands append rules: move the two input rules together before broad input accepts/drops, put trigger rules before policy-routing marks, and place scoped NAT before a conflicting earlier srcnat rule. There is no universal safe numeric move target. Integrate with PCC, security filtering and any other routing policies rather than blindly moving everything to position zero.', 'مرحله ۴: جایگاه Ruleها را بررسی کنید. add روی روتر موجود Rule را در انتها اضافه می‌کند؛ دو Rule مربوط به input را کنار هم قبل از accept/drop عمومی، Triggerها را قبل از Routing Mark و NAT محدود را قبل از srcnat قبلی متعارض جابه‌جا کنید. شماره مقصد move امن و عمومی وجود ندارد. با PCC، فیلتر امنیتی و Policyهای دیگر ادغام کنید؛ همه Ruleها را کورکورانه به موقعیت صفر منتقل نکنید.')+
    p('Step 5: verify the complete state below, stop ongoing trigger pings, test the single pilot host with new sessions and confirm internal access in all states. Commit Safe Mode only after validation. The full block does not provision a VPN or automatically modify an unknown FastTrack ruleset.', 'مرحله ۵: وضعیت کامل زیر را بررسی، Ping پیوسته Trigger را متوقف، Host آزمایشی را با Session تازه تست و دسترسی داخلی را در تمام وضعیت‌ها تأیید کنید. Safe Mode را فقط پس از تأیید Commit کنید. Block کامل VPN ایجاد نمی‌کند و Ruleset ناشناخته FastTrack را خودکار تغییر نمی‌دهد.')+code(diagnostics))

faqs = [
('Can MikroTik remove an IP from an address list directly from a firewall rule?', 'آیا MikroTik می‌تواند IP را مستقیماً با Firewall Rule از Address List حذف کند؟', 'No. The v7 firewall action set has addition actions but no source-address removal action. Queue a request and let a script remove the exact host entry.', 'خیر. Actionهای Firewall در v7 گزینه افزودن دارند، اما Action حذف مبدأ ندارند. درخواست را در صف قرار دهید تا Script همان Host Entry را حذف کند.'),
('Does this work with WireGuard?', 'آیا این روش با WireGuard کار می‌کند؟', 'Yes, with a validated WireGuard route, peer allowed-address coverage, endpoint underlay reachability and return routing or appropriate NAT. The L2TP gateway example must be adapted to that topology.', 'بله؛ Route معتبر WireGuard، پوشش allowed-address مربوط به Peer، دسترسی Endpoint از Underlay و Routing برگشت یا NAT مناسب لازم است. Gateway مثال L2TP باید با آن توپولوژی تطبیق داده شود.'),
('Can I use a second ISP instead of a VPN?', 'آیا می‌توان به‌جای VPN از ISP دوم استفاده کرد؟', 'Yes. Use the second ISP next hop in VPN-ROUTE, resolve it through a reachable underlay such as main, and review NAT and return-path symmetry. The table name is only an example label.', 'بله. Next Hop مربوط به ISP دوم را در VPN-ROUTE قرار دهید، آن را از Underlay قابل دسترس مثل main Resolve و NAT و تقارن مسیر برگشت را بررسی کنید. نام Table صرفاً برچسب مثال است.'),
('Does FastTrack affect policy routing?', 'آیا FastTrack روی Policy Routing اثر دارد؟', 'Yes. Non-main routing must be excluded in both directions. Use a stable trigger-eligible population for this scenario; active-list exclusions alone do not fix flows FastTracked before enable.', 'بله. Routing خارج از main باید در هر دو جهت مستثنا شود. در این سناریو جمعیت ثابت مجاز Trigger را مستثنا کنید؛ استثنای List فعال به‌تنهایی Flowهای FastTrackشده قبل از Enable را اصلاح نمی‌کند.'),
('Will existing connections immediately switch routes?', 'آیا اتصال‌های موجود بلافاصله تغییر مسیر می‌دهند؟', 'Do not expect seamless migration. Packets may receive a new routing mark while the previous NAT mapping remains, or FastTrack/other policy state may retain the earlier path. Test fresh sessions first.', 'انتظار مهاجرت بدون اختلال نداشته باشید. Packet ممکن است Mark جدید بگیرد ولی Mapping قبلی NAT باقی بماند، یا FastTrack/Policy دیگر مسیر قبلی را حفظ کند. ابتدا Session تازه را تست کنید.'),
('Can multiple clients use the same trigger?', 'آیا چند Client می‌توانند از یک Trigger استفاده کنند؟', 'Yes. Each echo adds its source independently. Clients sharing an upstream NAT identity will appear as one source to this router, so this mechanism cannot distinguish them.', 'بله. هر Echo مبدأ خود را مستقل اضافه می‌کند. Clientهای دارای NAT مشترک در بالادست، برای این روتر یک مبدأ دیده می‌شوند و این مکانیزم آن‌ها را تفکیک نمی‌کند.'),
('Can I automatically expire PBR access after a specific time?', 'آیا می‌توان دسترسی PBR را بعد از زمان مشخص خودکار منقضی کرد؟', 'Yes. Replace none-dynamic on the enable rule with a finite value such as 30m. Each new matching trigger refreshes the timeout. Verify this on the target release; a strict nonrenewable entitlement needs separate state. Keep stable FastTrack exclusions after expiry and reconnect sessions as needed.', 'بله. none-dynamic در Rule فعال‌سازی را با زمان محدود مثل 30m جایگزین کنید. هر Trigger منطبق جدید Timeout را تمدید می‌کند. این رفتار را روی Release هدف بررسی کنید؛ دسترسی با پایان قطعی غیرقابل تمدید به State جدا نیاز دارد. استثنای ثابت FastTrack را پس از انقضا حفظ و در صورت نیاز Sessionها را دوباره برقرار کنید.')
]
section('conclusion', 'Conclusion', 'جمع‌بندی', p('Two ICMP destinations provide a simple per-source control surface for RouterOS v7 policy routing. The operational requirements are precise local exclusions, a reachable custom table, a monitored removal worker, stable FastTrack exclusions and correct return routing/NAT. Treat route toggles as path changes for fresh traffic, not as a promise that existing sessions will migrate intact.', 'دو مقصد ICMP یک روش کنترل ساده بر اساس IP مبدأ برای Policy Routing در RouterOS v7 فراهم می‌کنند. الزامات عملیاتی شامل استثنای دقیق شبکه داخلی، Table اختصاصی قابل دسترس، Worker حذف پایش‌شده، استثنای ثابت FastTrack و Routing برگشت/NAT صحیح است. تغییر Route را تغییر مسیر ترافیک تازه بدانید، نه تضمین مهاجرت سالم Session موجود.'))
section('faq', 'FAQ', 'پرسش‌های متداول', ''.join('<div class="article-faq-item">'+node('h3', q, qfa)+p(a, afa)+'</div>' for q,qfa,a,afa in faqs))

titles = {'en':'MikroTik Ping-Triggered Policy Routing with Address Lists', 'fa':'MikroTik Policy Routing با Ping Trigger و Address List'}
descriptions = {'en':'A RouterOS v7 runbook for ping-controlled client routing, address-list removal, internal-network exclusions, FastTrack, NAT and operational verification.', 'fa':'راهنمای RouterOS v7 برای تغییر مسیر Client با Ping، حذف از Address List، استثنای شبکه داخلی، FastTrack، NAT و آزمون عملیاتی.'}
localizations = {lang: {'title':titles[lang], 'meta_title':titles[lang], 'description':descriptions[lang], 'keywords':['MikroTik','RouterOS v7','Policy Routing','Ping Trigger','Address List','FastTrack'], 'faq':[[q,a] if lang=='en' else [qfa,afa] for q,qfa,a,afa in faqs]} for lang in ['en','fa']}
toc = ''.join('<li class="article-nav-item"><a href="#'+key+'">'+node('span', en, fa)+'</a></li>' for key,en,fa,body in sections)
body = ''.join(s[3] for s in sections)
schema = {'@context':'https://schema.org','@type':'Article','headline':titles['en'],'description':descriptions['en'],'inLanguage':'en','datePublished':'2026-10-05T00:00:00+03:30','dateModified':'2026-10-05'}
image = '/assets/img/articles/banners/mikrotik-ping-triggered-policy-routing.png'
# Site metadata is generated by the importer; no operational domains are embedded in this runbook.
html = '<!doctype html><html lang="en" dir="ltr" data-article-language="en"><head><meta charset="UTF-8"><title>'+escape(titles['en'])+'</title><meta name="description" content="'+escape(descriptions['en'],quote=True)+'"><meta property="og:title" content="'+escape(titles['en'],quote=True)+'"><meta name="article:content-language" content="en"><meta name="robots" content="index, follow"><script type="application/ld+json">'+json.dumps(schema,ensure_ascii=False)+'</script><script id="article-localizations" type="application/json">'+json.dumps(localizations,ensure_ascii=False)+'</script></head><body class="article-page theme-mikrotik"><header><nav><ul>'+toc+'</ul></nav></header><main><section class="article-hero article-header hero">'+node('span','MikroTik','میکروتیک').replace('<span ','<span class="article-category" ',1)+node('h1',titles['en'],titles['fa']).replace('<h1 ','<h1 class="article-title hero-title" ',1)+node('p',descriptions['en'],descriptions['fa']).replace('<p ','<p class="article-excerpt hero-subtitle" ',1)+'<img class="article-hero-thumbnail" src="'+image+'" alt="MikroTik policy routing"></section><article class="article-body" lang="en" dir="ltr">'+body+'</article></main></body></html>\n'
target = ROOT/'resources/legacy/articles'/f'{SLUG}.html'
target.write_text(html,encoding='utf-8')
(PACKAGE/'metadata.json').write_text(json.dumps(localizations,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
print(f'Generated {target.name}: {len(sections)} bilingual sections, {len(html)} characters.')
